export const CAPTIONS_PIP2: { t: number; h: string }[] = [
  { t:   0.00, h: 'i tell you' },
  { t:   0.50, h: 'there\'s a backstory' },
  { t:   1.38, h: 'with the <gr>89x</gr>' },
  { t:   2.60, h: 'on <y>pippin</y> in' },
  { t:   3.80, h: 'a <r>bear</r> <r>market.</r>' },
  { t:   5.10, h: '<y>pippin</y> was a' },
  { t:   5.84, h: 'play of mine from' },
  { t:   6.54, h: 'early <y>2025,</y>' },
  { t:   7.66, h: 'and it seemed' },
  { t:   8.52, h: 'to have gone <r>dead</r> in' },
  { t:   9.58, h: '<y>august</y> of <y>2025.</y>' },
  { t:  10.80, h: 'not only did the' },
  { t:  11.38, h: '<y>twitter</y> profile go' },
  { t:  12.28, h: '<r>dead</r> in <y>august</y>' },
  { t:  12.98, h: 'with <y>pippin,</y> but' },
  { t:  13.70, h: 'it went <r>dead.</r>' },
  { t:  14.44, h: 'in terms of' },
  { t:  14.76, h: 'getting into a' },
  { t:  15.18, h: 'centralized <y>exchange,</y> <y>pippin</y>' },
  { t:  16.48, h: 'started <gr>ripping.</gr>' },
  { t:  17.42, h: 'and i was like, why' },
  { t:  18.04, h: 'is this happening?' },
  { t:  18.84, h: 'we\'re getting pinged' },
  { t:  19.66, h: 'over and over' },
  { t:  21.04, h: 'and over again.' },
  { t:  22.18, h: 'like, oh, my <y>god.</y>' },
  { t:  23.88, h: 'oh, my <y>god.</y>' },
  { t:  25.40, h: 'oh, my <y>god.</y>' },
  { t:  26.18, h: 'started <gr>ripping</gr> like' },
  { t:  27.54, h: 'it started going' },
  { t:  28.18, h: '<gr>up</gr> and <gr>up</gr> and' },
  { t:  29.22, h: '<gr>up,</gr> and eventually' },
  { t:  30.40, h: 'it was like an' },
  { t:  31.18, h: '<gr>89x</gr> by the time' },
  { t:  32.58, h: 'we got out of it' },
  { t:  34.12, h: 'took some <gr>profits,</gr>' },
  { t:  35.12, h: 'made tons of' },
  { t:  35.66, h: '<gr>money.</gr>' },
];
