export const CAPTIONS_PIP2: { t: number; h: string }[] = [
  { t:   0.00, h: 'i tell you' },
  { t:   0.50, h: 'there\'s a backstory' },
  { t:   1.38, h: 'with the' },
  { t:   1.84, h: '<gr>89x</gr> on' },
  { t:   2.88, h: '<y>pippin</y> in a' },
  { t:   3.98, h: '<r>bear</r> <r>market.</r>' },
  { t:   5.10, h: '<y>pippin</y> was a' },
  { t:   5.84, h: 'play of mine from' },
  { t:   6.54, h: 'early <y>2025,</y>' },
  { t:   7.66, h: 'and it seemed' },
  { t:   8.52, h: 'to have gone <r>dead</r> in' },
  { t:   9.58, h: '<y>august</y> of <y>2025.</y>' },
  { t:  10.80, h: 'not only did the' },
  { t:  11.38, h: '<y>twitter</y> profile go' },
  { t:  12.28, h: '<r>dead</r> in <y>august</y>' },
  { t:  12.98, h: 'with <y>pippin,</y> but' },
  { t:  13.70, h: 'it went <r>dead.</r>' },
  { t:  14.44, h: 'in terms of' },
  { t:  14.76, h: 'getting into a' },
  { t:  15.18, h: 'centralized <y>exchange,</y>' },
  { t:  16.16, h: '<y>pippin</y> started <gr>ripping.</gr>' },
  { t:  17.42, h: 'and i was like, why' },
  { t:  18.04, h: 'is this happening?' },
  { t:  18.84, h: 'we\'re getting pinged' },
  { t:  19.66, h: 'over and' },
  { t:  20.58, h: 'over and over' },
  { t:  21.62, h: 'again.' },
  { t:  22.18, h: 'like, oh, my' },
  { t:  22.94, h: '<y>god.</y>' },
  { t:  23.88, h: 'oh, my <y>god.</y>' },
  { t:  25.40, h: 'oh, my <y>god.</y>' },
  { t:  26.18, h: 'started <gr>ripping</gr>' },
  { t:  27.24, h: 'like it started' },
  { t:  27.92, h: 'going <gr>up</gr> and' },
  { t:  28.64, h: '<gr>up</gr> and <gr>up,</gr> and' },
  { t:  29.80, h: 'eventually it was' },
  { t:  30.82, h: 'like an <gr>89x</gr>' },
  { t:  31.96, h: 'by the time we' },
  { t:  32.84, h: 'got out of it' },
  { t:  34.12, h: 'took some <gr>profits,</gr>' },
  { t:  35.12, h: 'made tons of' },
  { t:  35.66, h: '<gr>money.</gr>' },
];
