export const CAPTIONS_TUT_RHM: { t: number; h: string }[] = [
  { t:   0.42, h: 'in my opinion' },
  { t:   1.16, h: 'what is the best meme' },
  { t:   1.98, h: 'on the <gr>robinhood</gr>' },
  { t:   2.54, h: 'chain i would' },
  { t:   3.88, h: 'without a doubt' },
  { t:   4.75, h: '<y>unequivocally</y> i go' },
  { t:   6.70, h: 'for what if what if' },
  { t:   7.88, h: 'is my my' },
  { t:   8.78, h: 'favorite' },
  { t:   9.60, h: 'what if is a' },
  { t:  10.51, h: '<y>concept?</y>' },
  { t:  10.78, h: 'it\'s a beautiful' },
  { t:  11.62, h: 'phrase' },
  { t:  12.77, h: 'i can\'t believe' },
  { t:  13.44, h: 'that nobody ever' },
  { t:  14.22, h: 'thought of it' },
  { t:  14.78, h: 'before in a' },
  { t:  15.30, h: 'meme coin.' },
  { t:  15.80, h: 'what if this' },
  { t:  16.72, h: 'happens?' },
  { t:  17.10, h: 'i know i say it' },
  { t:  17.80, h: 'all the time' },
  { t:  18.67, h: 'everybody does.' },
  { t:  19.86, h: 'what if such and such' },
  { t:  21.74, h: 'happens?' },
  { t:  23.29, h: 'so that\'s beautiful' },
  { t:  24.68, h: '<gr>cooper</gr> is' },
  { t:  25.93, h: 'a real dog.' },
  { t:  26.61, h: 'it is the' },
  { t:  27.28, h: 'office dog' },
  { t:  28.48, h: 'of <gr>robinhood.</gr>' },
  { t:  29.26, h: 'it\'s a real dog' },
  { t:  31.04, h: 'and that is why it\'s' },
  { t:  32.36, h: 'my second favorite' },
  { t:  33.30, h: 'meme.' },
  { t:  33.72, h: 'besides, you know' },
  { t:  35.55, h: 'besides what if' },
  { t:  36.80, h: 'it gives me' },
  { t:  37.56, h: 'that <gr>toshi</gr> vibe' },
  { t:  38.62, h: 'being the cat' },
  { t:  39.34, h: 'of brian armstrong' },
  { t:  40.04, h: 'and we have the' },
  { t:  40.76, h: 'office dog and' },
  { t:  42.24, h: 'the <gr>robinhood.</gr>' },
  { t:  43.19, h: 'the <gr>robinhood</gr> headquarters' },
  { t:  44.24, h: 'right?' },
  { t:  44.70, h: 'so cool.' },
  { t:  46.28, h: 'i think <gr>tendies</gr>' },
  { t:  47.00, h: 'is pretty good' },
  { t:  48.50, h: 'it\'s a very' },
  { t:  49.46, h: 'funny and stupid' },
  { t:  50.62, h: 'like <y>concept.</y>' },
  { t:  52.01, h: 'that\'s i think' },
  { t:  53.20, h: 'that it\'ll make get it' },
  { t:  55.30, h: 'a potential <gr>robinhood</gr>' },
  { t:  56.84, h: 'app listing' },
  { t:  58.33, h: 'you know just like' },
  { t:  59.02, h: '<gr>fartcoin</gr>' },
  { t:  60.63, h: 'that\'ll be number' },
  { t:  61.26, h: '<y>three.</y>' },
  { t:  61.88, h: 'i want to go' },
  { t:  62.32, h: 'through a few' },
  { t:  62.82, h: 'of them that i like' },
  { t:  63.96, h: '<gr>yolo,</gr> this is' },
  { t:  64.94, h: 'pretty good because' },
  { t:  65.64, h: 'look what it\'s' },
  { t:  66.12, h: 'doing right here' },
  { t:  67.74, h: 'it went up and' },
  { t:  68.66, h: 'pumped it pumped' },
  { t:  69.30, h: 'hard over here' },
  { t:  71.06, h: 'and then it\'s' },
  { t:  71.96, h: 'really maintaining this' },
  { t:  73.00, h: 'level right down' },
  { t:  73.78, h: 'here, man it\'s like look' },
  { t:  74.70, h: 'at that.' },
  { t:  75.45, h: 'but i think' },
  { t:  76.44, h: 'this would be' },
  { t:  76.88, h: 'my number <y>four.</y>' },
  { t:  77.70, h: 'maybe <gr>swappy</gr> would' },
  { t:  78.42, h: 'be like my' },
  { t:  78.68, h: 'number <y>five</y>' },
];
