# Sequential regen of the 15 remaining carousel slides for 3 YT posts
# (also covers the IG carousel that shares ai-tug-of-war images).
# Uses chatgpt-profile + the per-call 15-45s pre-launch delay built into generate-image.js.

$YTCHAT = "https://chatgpt.com/c/69ffc14c-3994-83ea-8f79-48845459ecfa"
$REF_DIR = "C:\Users\mnede\Documents\Claude\social-media\schedule-tweets\images\reference\carousels\version1"

$jobs = @(
  # ── hard-fork-23-days-pricing-in (5 slides) ─────────────────────────
  @{ id='4f83d205'; slug='01-hook-community-mad'; ref="$REF_DIR\yt-posts-e5f8a2c4-01-zombie-hook.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'HOT TAKE'. Below in large neon green all-caps 'COMMUNITY MAD'. A glowing teal Kaspa coin in the corner with a crowd of angry small character silhouettes glowering at it. Data panel elements with abstract sentiment graphics. Match the visual style and layout of the attached reference image." }
  @{ id='9b639801'; slug='02-fork-23-days-no-pump'; ref="$REF_DIR\yt-posts-a7e2f4b8-02-ppi-data.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'HARD FORK 23 DAYS'. Below in large neon green all-caps 'NO PUMP'. A large glowing countdown timer in the center showing 23. A flat horizontal price line beside it. Data panel elements with abstract calendar countdown graphics. Match the visual style and layout of the attached reference image." }
  @{ id='2e48acb6'; slug='03-priced-in-everyone-knows'; ref="$REF_DIR\yt-posts-6f54e3d5-03-the-problem.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'EVERYONE KNOWS'. Below in large neon green all-caps 'IT IS PRICED IN'. A glowing megaphone broadcasting to a crowd of speech bubbles all showing the same date. Data panel elements with abstract information-spread graphics. Match the visual style and layout of the attached reference image." }
  @{ id='45a965bc'; slug='04-real-pump-after-crowd'; ref="$REF_DIR\yt-posts-cbf76e06-04-the-solution.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'REAL PUMP'. Below in large neon green all-caps '60-120 DAYS LATER'. A glowing teal Kaspa coin launching upward on a delayed chart trajectory after a flat consolidation. Data panel elements with abstract market-discovery graphics. Match the visual style and layout of the attached reference image." }
  @{ id='ec8141d7'; slug='05-engagement-question'; ref="$REF_DIR\yt-posts-c9e1b4d5-05-question.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline reading 'KAS PUMPS WHEN?'. Below in large neon green all-caps 'BEFORE, ON, AFTER?'. A large stylized question mark glowing in the center with three branching arrows (before / on / after the fork date). Data panel elements with abstract timing fork. Match the visual style and layout of the attached reference image." }

  # ── institutions-infrastructure-kaspa-checklist (5 slides) ───────────
  @{ id='21eb4251'; slug='01-hook-no-memes'; ref="$REF_DIR\yt-posts-828eee71-01-hook.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'INSTITUTIONS'. Below in large neon green all-caps 'DON'T BUY MEMES'. A glowing infrastructure-themed icon (server racks or vault) in the foreground with faded meme-coin silhouettes pushed aside. Data panel elements with abstract institutional-portfolio graphics. Match the visual style and layout of the attached reference image." }
  @{ id='1b7d1287'; slug='02-box-1-security'; ref="$REF_DIR\yt-posts-89869680-02-btc-failure.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'BOX 1'. Below in large neon green all-caps 'SECURITY'. A glowing shield icon with checkmark in the center. Network hash-rate distribution lines radiating outward. A small neon green checkmark next to a Bitcoin coin and a Kaspa coin. Data panel elements with abstract security-audit graphics. Match the visual style and layout of the attached reference image." }
  @{ id='7a7b7b9a'; slug='03-box-2-instant-settlement'; ref="$REF_DIR\yt-posts-6f54e3d5-03-the-problem.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'BOX 2'. Below in large neon green all-caps 'INSTANT SETTLEMENT'. A glowing clock icon with hands moving at lightning speed. A glowing teal Kaspa coin transmitting between two nodes. Data panel elements with abstract throughput graphics. Match the visual style and layout of the attached reference image." }
  @{ id='b1c1a8db'; slug='04-box-3-4-decentralized-stress'; ref="$REF_DIR\yt-posts-cbf76e06-04-the-solution.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'BOX 3 & 4'. Below in large neon green all-caps 'DECENTRALIZED + STABLE'. A glowing distributed network mesh icon and a stress-test shield icon side by side. Data panel elements with abstract decentralization and stability indicators. Match the visual style and layout of the attached reference image." }
  @{ id='01b045a8'; slug='05-engagement-question'; ref="$REF_DIR\yt-posts-c9e1b4d5-05-question.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline reading 'WHICH BOX TRIPS'. Below in large neon green all-caps 'COMPETITORS FIRST?'. A large stylized question mark glowing in the center surrounded by four glowing checkbox icons (security, settlement, decentralization, stress). Data panel elements with abstract elimination graphics. Match the visual style and layout of the attached reference image." }

  # ── ai-tug-of-war-tipping-kaspa-retail (5 slides; shared with IG carousel) ─
  @{ id='3b47b002'; slug='01-hook-not-the-fed'; ref="$REF_DIR\yt-posts-e5f8a2c4-01-zombie-hook.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'NOT THE FED'. Below in large neon green all-caps 'HOLDING CRYPTO BACK'. A faded Federal Reserve building icon being crossed out. Data panel elements with abstract macro-blame graphics. Match the visual style and layout of the attached reference image." }
  @{ id='34c57330'; slug='02-its-wages-ai-eating-jobs'; ref="$REF_DIR\yt-posts-89869680-02-btc-failure.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'IT'S WAGES'. Below in large neon green all-caps 'AI EATING JOBS'. A glowing AI brain icon consuming small briefcase icons. A flat wage chart in the background. Data panel elements with abstract labor-market graphics. Match the visual style and layout of the attached reference image." }
  @{ id='3fbe9e4d'; slug='03-adp-up-tug-tipping'; ref="$REF_DIR\yt-posts-6f54e3d5-03-the-problem.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'ADP UP 4 MONTHS'. Below in large neon green all-caps 'TUG TIPPING'. A large tug-of-war rope graphic with a labor-market hiring side gaining ground. ADP-themed chart bars rising in the background. Data panel elements with abstract employment graphics. Match the visual style and layout of the attached reference image." }
  @{ id='3f6c059c'; slug='04-retail-flows-back-crypto'; ref="$REF_DIR\yt-posts-cbf76e06-04-the-solution.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline at top reading 'RETAIL FLOWS BACK'. Below in large neon green all-caps 'INTO CRYPTO'. A glowing teal Kaspa coin surrounded by a stream of small upward-flowing arrows representing retail money. Data panel elements with abstract capital-rotation graphics. Match the visual style and layout of the attached reference image." }
  @{ id='ed5b9124'; slug='05-engagement-question'; ref="$REF_DIR\yt-posts-c9e1b4d5-05-question.png"; prompt="Bold crypto news graphic, near-black background, dramatic lighting, bold all-caps white and neon green typography. No human faces. 1:1 square. Bold all-caps white headline reading 'WHEN DOES IT TIP?'. Below in large neon green all-caps 'Q2 Q3 Q4 LATER?'. A large stylized question mark glowing in the center with four branching timeline markers. Data panel elements with abstract quarter-marker graphics. Match the visual style and layout of the attached reference image." }
)

cd "C:\Users\mnede\Documents\Claude\social-media\repurpose"
$i = 0
foreach ($job in $jobs) {
  $i++
  $start = Get-Date
  Write-Host "[$($start.ToString('HH:mm:ss'))] [$i/$($jobs.Count)] $($job.id)-$($job.slug)"
  node generate-image.js `
    "--image-id=$($job.id)" `
    "--slug=$($job.slug)" `
    "--prefix=yt-posts" `
    "--chat-url=$YTCHAT" `
    "--reference-image=$($job.ref)" `
    "--prompt=$($job.prompt)"
  $end = Get-Date
  Write-Host "[$($end.ToString('HH:mm:ss'))] [$i/$($jobs.Count)] done in $([math]::Round(($end - $start).TotalSeconds))s"
  Write-Host ""
}
Write-Host "All $($jobs.Count) slides regenerated."
