// captionsEcAkita.ts - batch early-crash / clip #1 `akita-3b-robinhood` (variant: full).
// Title (Mike's exact 4b wording, "Robin Hood" normalized per persona terminology):
//   "Here's why Robinhood chain tokens will pass 6 billion."
//
// GENERATED by the canonical caption skill (video-creation/skills/captions/captions.md, montserrat
// preset). NEVER hand-edited below this header. Regenerate the array byte-identically with the TWO
// commands below, in this order (the first rebuilds the patched word source, the second the array;
// re-apply this header by hand afterwards, as on captionsEcMoon.ts):
//   python video-creation/shorts/early-crash/akita-3b-robinhood/_patch_words.py
//   python video-creation/skills/captions/build_captions.py \
//     --words video-creation/shorts/early-crash/akita-3b-robinhood/whisper-words-verified.json \
//     --style montserrat --var CAPTIONS_EC_AKITA \
//     --colorize "y=$120k,858,billion,3,10,20,million gr=robinhood,$if,cashcat" \
//     --out video-creation/remotion/src/captionsEcAkita.ts
//
// ⛔ SOURCE IS `whisper-words-verified.json`, NOT the shipped `whisper-words.json`. The shipped word
// pass SILENTLY OMITS speech (remotion-shorts-build SKILL, checklist item 3), and `_patch_words.py`
// restores three runs it drops, each re-transcribed off THIS clip's own audio at SHORT windows:
//   * "ooh." 43.14-43.66      - fills a 1.70 s hole between "holy crap." and "man, that's crazy"
//   * "look at that." 65.62-66.62 - fills a 3.42 s hole between "hold on." and "look at that."
//   * "right?" 106.48-106.70 + the swallowed "if" 106.74-106.88 - the shipped pass emits ONE garbage
//     0.04-probability token there, which captioned the protected doubling as a single
//     "...this happen, if things like this happen..."; eight independent reads return
//     "...this happen, RIGHT? if things like this happen...". Restoring it regroups 11 caption lines
//     (105.74-115.60), so a render made before the patch is STALE even though it looks complete.
// Building from the unpatched file loses all three. Diff the two builds before trusting any render.
//
// Caption gates from tighten-plan.json, each VERIFIED against THIS clip's OWN audio (the flags are
// read off the MASTER transcript and are often wrong; rejections are recorded in build_captions.py's
// early-crash/akita-3b-robinhood block):
//   * 1057.5 "it shut up" -> "it shot up" (16.94/17.96)  * "$120K market cap" (20.62)
//   * word-salad 1094.6-1103.2 captioned from audio -> "look at that. god candle. holy crap, man."
//   * word-salad 1147.2-1153.4 captioned from audio -> "let me hover over that candle. where is it?"
//   * "Robin Hood" -> robinhood x3 (89.50 / 110.32 / 113.44)  * "cash gap" -> cashcat (123.86)
//   * the What If ticker is $IF, never $WHATIF (125.12)
//   * REJECTED, gate wrong vs audio: "hover over IT right now" (52.54; no 1x pass produces the "it")
//     and "how far IT might go" (117.68; short staggered windows return "how far might go").
// Every KEPT persona doubling is on screen verbatim, never deduped ("akita, akita inu" /
// "down down down down" via PROTECTED_DOUBLES, "look at that" x6, the "holy crap"/"oh my god"
// doubles, "hold on" x3, "3 billion, 3 billion", "a freaking inu" x2, "my point, my point is",
// "we're the early ones / we are the early ones", "if things like this happen" x2,
// "in a bull run, in a parabolic bull run", "how far, how far", "10 or 20 billion" x2), and no
// removed fragment appears (no "the previous cycles", no "the date is uh it's february", neither cut
// "you know" tic, no "i mean", no doubled "to the").
export const CAPTIONS_EC_AKITA: { t: number; h: string }[] = [
  { t:   0.00, h: 'so these are' },
  { t:   0.88, h: 'like some of the 2021' },
  { t:   2.10, h: 'meme coins that' },
  { t:   3.18, h: 'went like to a' },
  { t:   4.38, h: '<y>billion</y> or more' },
  { t:   5.46, h: 'like exploded without' },
  { t:   7.00, h: 'any centralized exchanges.' },
  { t:   8.72, h: 'just absolutely explode' },
  { t:  10.38, h: 'in the bull run.' },
  { t:  11.06, h: 'this is akita' },
  { t:  12.28, h: 'akita inu.' },
  { t:  13.36, h: 'and you can see here' },
  { t:  14.66, h: 'the date, right?' },
  { t:  15.62, h: 'february 1st, 2021.' },
  { t:  16.94, h: 'it came out, it shot' },
  { t:  17.96, h: 'up and went back down.' },
  { t:  19.46, h: 'it was down, down, down' },
  { t:  20.62, h: 'down, <y>$120k</y> market' },
  { t:  23.00, h: 'cap.' },
  { t:  23.54, h: 'all right.' },
  { t:  23.78, h: 'then it goes up.' },
  { t:  24.76, h: 'then it goes to a' },
  { t:  25.42, h: 'couple <y>million.</y>' },
  { t:  26.10, h: 'it comes down.' },
  { t:  26.64, h: 'it goes up and it' },
  { t:  27.40, h: 'goes to a' },
  { t:  27.74, h: '<y>million.</y>' },
  { t:  28.06, h: 'it comes down.' },
  { t:  28.76, h: 'now mind you, i\'m' },
  { t:  29.08, h: 'showing you this' },
  { t:  29.66, h: 'for a reason.' },
  { t:  30.42, h: 'so this didn\'t' },
  { t:  30.90, h: 'get any centralized' },
  { t:  31.80, h: 'exchanges.' },
  { t:  32.48, h: 'it was a' },
  { t:  33.02, h: 'freaking inu.' },
  { t:  33.64, h: 'this was 2021 when' },
  { t:  35.36, h: 'there was an' },
  { t:  35.88, h: 'inu craze.' },
  { t:  36.56, h: 'and then look what' },
  { t:  37.14, h: 'happened.' },
  { t:  37.64, h: 'look at that.' },
  { t:  38.44, h: 'god candle.' },
  { t:  39.32, h: 'holy crap, man.' },
  { t:  41.44, h: 'holy crap.' },
  { t:  43.14, h: 'ooh.' },
  { t:  44.02, h: 'man.' },
  { t:  44.46, h: 'that\'s crazy.' },
  { t:  45.30, h: 'right?' },
  { t:  45.80, h: 'look at that.' },
  { t:  46.56, h: 'look at that.' },
  { t:  47.08, h: 'how it kept' },
  { t:  47.58, h: 'going.' },
  { t:  48.42, h: 'look at that.' },
  { t:  49.56, h: 'holy crap.' },
  { t:  50.26, h: 'look at that wick.' },
  { t:  51.10, h: 'holy crap.' },
  { t:  51.90, h: 'crazy.' },
  { t:  52.32, h: 'right?' },
  { t:  52.54, h: 'let me hover' },
  { t:  52.92, h: 'over right now.' },
  { t:  53.72, h: 'it says the high is' },
  { t:  55.00, h: '<y>858</y> <y>million.</y>' },
  { t:  56.50, h: 'now i\'m going' },
  { t:  57.04, h: 'to go over here to' },
  { t:  58.38, h: 'the right.' },
  { t:  58.82, h: 'now watch this.' },
  { t:  59.84, h: 'oh my god.' },
  { t:  61.24, h: 'oh my god.' },
  { t:  61.84, h: 'here.' },
  { t:  62.12, h: 'hold on.' },
  { t:  62.36, h: 'hold on.' },
  { t:  62.60, h: 'hold on.' },
  { t:  65.62, h: 'look at that.' },
  { t:  67.84, h: 'look at that.' },
  { t:  69.36, h: 'holy crap.' },
  { t:  70.90, h: 'holy crap.' },
  { t:  72.10, h: 'oh my god.' },
  { t:  74.36, h: 'look at that.' },
  { t:  75.64, h: '<y>3</y> <y>billion.</y>' },
  { t:  76.48, h: 'let me hover' },
  { t:  76.90, h: 'over that candle.' },
  { t:  77.74, h: 'where is it?' },
  { t:  79.06, h: 'right here.' },
  { t:  79.92, h: 'right?' },
  { t:  80.08, h: 'yeah.' },
  { t:  80.26, h: 'is this the <y>3</y>' },
  { t:  81.00, h: '<y>billion,</y> <y>3</y> <y>billion</y>' },
  { t:  81.88, h: 'market cap?' },
  { t:  82.62, h: 'a freaking inu' },
  { t:  83.46, h: 'without any centralized' },
  { t:  84.68, h: 'exchanges.' },
  { t:  85.78, h: 'a freaking inu.' },
  { t:  86.78, h: 'oh, this is, this is' },
  { t:  87.36, h: 'my point.' },
  { t:  87.82, h: 'my point is' },
  { t:  88.42, h: 'like a' },
  { t:  89.50, h: 'the <gr>robinhood</gr> chain' },
  { t:  90.40, h: 'is probably going' },
  { t:  91.08, h: 'to be amazing.' },
  { t:  92.26, h: 'there\'s going to' },
  { t:  92.72, h: 'be a lot of' },
  { t:  93.56, h: 'liquidity coming in' },
  { t:  94.62, h: 'and anybody who' },
  { t:  95.38, h: 'is in it' },
  { t:  95.80, h: 'right now' },
  { t:  97.14, h: 'anybody here right' },
  { t:  98.08, h: 'now.' },
  { t:  98.58, h: 'oh man.' },
  { t:  99.32, h: 'if you play your' },
  { t:  99.96, h: 'cards right, man' },
  { t: 100.88, h: 'everybody\'s going to' },
  { t: 101.54, h: 'be set because' },
  { t: 102.38, h: 'we\'re the early' },
  { t: 103.08, h: 'ones.' },
  { t: 103.36, h: 'like we are the' },
  { t: 104.42, h: 'early ones.' },
  { t: 105.10, h: 'if things like' },
  { t: 105.74, h: 'this happen, right?' },
  { t: 106.74, h: 'if things like' },
  { t: 107.36, h: 'this happen, imagine' },
  { t: 108.30, h: 'what happened to' },
  { t: 109.12, h: 'a token that\'s' },
  { t: 110.32, h: 'on the <gr>robinhood</gr>' },
  { t: 111.08, h: 'chain and gets' },
  { t: 112.60, h: 'listed in the' },
  { t: 113.44, h: '<gr>robinhood</gr> app in' },
  { t: 114.56, h: 'a bull run in a' },
  { t: 115.60, h: 'parabolic bull run.' },
  { t: 116.60, h: 'just imagine how' },
  { t: 117.68, h: 'far, how far' },
  { t: 118.76, h: 'might go.' },
  { t: 119.44, h: 'this went to <y>3</y>' },
  { t: 120.18, h: '<y>billion.</y>' },
  { t: 120.78, h: 'you know, could' },
  { t: 121.12, h: 'we see like a <y>10</y>' },
  { t: 122.30, h: 'or <y>20</y> <y>billion</y>' },
  { t: 123.38, h: 'token?' },
  { t: 123.86, h: 'could <gr>cashcat</gr> and' },
  { t: 125.12, h: '<gr>$if,</gr> could it' },
  { t: 125.98, h: 'go to <y>10</y> or <y>20</y>' },
  { t: 126.84, h: '<y>billion?</y>' },
  { t: 127.22, h: 'it\'s very possible.' },
];
