// captionsWobf.ts — captions for "The October Bottom Is Getting Front-Run"
// batch whatif, clip #1, slug october-bottom-front-run (variant: full)
// Built from the spine's small-model Whisper words via captions/build_captions.py --style montserrat,
// then hand-applied the delegated STT fixes:
//   micro-strategy -> microstrategy | super-volcano -> supervolcano | "turn green" -> "turned green"
//   hook cleaned to the declarative "90% of people in crypto always lose".
// Color: <y> numbers, <r> danger/down, <gr> up/win. No em dashes.
export const CAPTIONS_WOBF: { t: number; h: string }[] = [
  { t:   0.00, h: '<y>90%</y> of people' },
  { t:   1.12, h: 'in crypto always' },
  { t:   1.68, h: 'lose. and if' },
  { t:   3.04, h: '<y>90%</y> of the' },
  { t:   3.94, h: 'people think that' },
  { t:   4.90, h: 'there\'s going to' },
  { t:   5.40, h: 'be a bottom' },
  { t:   5.92, h: 'in october, then' },
  { t:   6.76, h: 'there\'s probably not' },
  { t:   7.56, h: 'going to be' },
  { t:   7.84, h: 'a bottom in' },
  { t:   8.32, h: 'october.' },
  { t:   8.78, h: 'the bottom might' },
  { t:   9.84, h: 'be front-run, so' },
  { t:  11.62, h: 'it\'ll be before' },
  { t:  12.64, h: 'october, and most' },
  { t:  13.82, h: 'likely it is' },
  { t:  14.56, h: 'behind us, but' },
  { t:  15.30, h: 'it could be' },
  { t:  15.68, h: 'in front of' },
  { t:  16.16, h: 'us by a few' },
  { t:  17.10, h: 'weeks.' },
  { t:  17.58, h: 'i say that' },
  { t:  18.20, h: 'september is also' },
  { t:  19.18, h: 'going to be' },
  { t:  19.68, h: '<gr>green,</gr> because i' },
  { t:  20.42, h: 'mean, everybody who\'s' },
  { t:  21.28, h: 'not a four-year' },
  { t:  21.78, h: 'cycle zombie is' },
  { t:  22.96, h: 'obviously aware that' },
  { t:  24.62, h: 'the four-year cycle' },
  { t:  25.42, h: 'zombies are going' },
  { t:  26.14, h: 'to try to buy back' },
  { t:  27.14, h: 'in october.' },
  { t:  27.66, h: 'so a lot of' },
  { t:  28.32, h: 'people are going' },
  { t:  28.66, h: 'to get their' },
  { t:  29.08, h: 'last buys in' },
  { t:  29.96, h: '<gr>september.</gr>' },
  { t:  30.58, h: 'my perfect example' },
  { t:  31.78, h: 'i\'ve always given' },
  { t:  32.76, h: 'is what happened' },
  { t:  33.56, h: 'last september.' },
  { t:  35.14, h: 'it\'s always been' },
  { t:  36.08, h: 'known that every' },
  { t:  37.22, h: 'single september in' },
  { t:  38.60, h: 'the post-halving year' },
  { t:  39.80, h: 'is always <r>red.</r>' },
  { t:  41.04, h: 'so people knew' },
  { t:  41.96, h: 'that, and they said, i\'m' },
  { t:  43.06, h: 'going to sell' },
  { t:  43.68, h: 'before september to' },
  { t:  44.82, h: 'get out of' },
  { t:  45.46, h: 'there, and they' },
  { t:  45.88, h: 'turned august <r>red,</r>' },
  { t:  47.64, h: 'and then september' },
  { t:  48.18, h: 'turned <gr>green.</gr>' },
  { t:  48.96, h: 'like how the hell?' },
  { t:  49.78, h: 'everybody\'s going to' },
  { t:  50.32, h: 'be buying back' },
  { t:  51.10, h: 'in october.' },
  { t:  51.98, h: 'how is it' },
  { t:  52.50, h: 'going to be' },
  { t:  52.82, h: '<r>red?</r>' },
  { t:  53.16, h: 'i mean, i tell you' },
  { t:  53.80, h: 'how.' },
  { t:  54.08, h: 'that has to be some' },
  { t:  55.00, h: 'catastrophic black swan' },
  { t:  57.04, h: 'event.' },
  { t:  57.50, h: 'microstrategy <r>collapses</r>' },
  { t:  59.96, h: 'and china <r>invades</r>' },
  { t:  61.68, h: 'taiwan' },
  { t:  62.88, h: 'and the yellowstone' },
  { t:  64.42, h: 'supervolcano <r>explodes</r> at' },
  { t:  66.78, h: 'the same time' },
  { t:  67.50, h: 'right?' },
  { t:  67.86, h: 'so that ain\'t' },
  { t:  68.38, h: 'happening.' },
  { t:  69.04, h: 'and if it does, the' },
  { t:  69.92, h: 'four-year cycle zombies' },
  { t:  70.92, h: 'will be jumping' },
  { t:  71.62, h: 'on my socials' },
  { t:  72.72, h: 'saying, haha, there\'s' },
  { t:  73.90, h: 'a four-year cycle.' },
  { t:  74.98, h: 'october had a' },
  { t:  75.54, h: 'bottom.' },
  { t:  75.94, h: 'yeah, they wouldn\'t' },
  { t:  77.14, h: 'be ducking for' },
  { t:  77.74, h: 'cover there.' },
  { t:  78.34, h: 'just be like, haha, i\'m' },
  { t:  79.78, h: 'a four-year cycle' },
  { t:  80.46, h: '<r>zombie.</r>' },
];
