export const CAPTIONS_EC_TENDIES: { t: number; h: string }[] = [
  { t:   0.00, h: 'the only ones that' },
  { t:   0.96, h: 'really float my' },
  { t:   1.68, h: 'boat is obviously' },
  { t:   2.78, h: 'is what if it\'s' },
  { t:   3.70, h: 'cooper and then' },
  { t:   4.38, h: 'there\'s <gr>tendies</gr> even' },
  { t:   5.12, h: 'though i haven\'t' },
  { t:   5.52, h: 'gotten any, but' },
  { t:   6.40, h: 'this is the only one' },
  { t:   7.04, h: 'because it\'s like' },
  { t:   7.78, h: 'it\'s funny and' },
  { t:   8.62, h: 'stupid.' },
  { t:   8.96, h: 'you know, this' },
  { t:   9.44, h: 'reminds me of' },
  { t:   9.88, h: 'like the <gr>fartcoin</gr>' },
  { t:  10.62, h: 'concept, like, oh' },
  { t:  11.92, h: 'that\'s stupid.' },
  { t:  12.46, h: 'but, you know, it\'s kind' },
  { t:  13.18, h: 'of funny if' },
  { t:  13.62, h: 'people will buy' },
  { t:  14.14, h: 'into it.' },
  { t:  14.56, h: 'and it\'s probably' },
  { t:  15.28, h: 'the type of meme that' },
  { t:  16.62, h: '<gr>vlad</gr> will want to list' },
  { t:  18.06, h: 'on the <gr>robinhood</gr>' },
  { t:  18.72, h: 'app from <y>16</y>' },
  { t:  19.88, h: '<y>million</y> right now.' },
  { t:  20.78, h: 'if it goes on the' },
  { t:  21.92, h: '<gr>robinhood</gr> app in' },
  { t:  22.72, h: 'a bull run over a' },
  { t:  23.66, h: '<y>billion,</y> you know' },
  { t:  24.62, h: 'we\'ll see, we\'ll see how' },
  { t:  25.54, h: 'far it goes.' },
  { t:  26.36, h: 'it could like' },
  { t:  26.80, h: 'it could be' },
  { t:  27.26, h: '<y>insane.</y>' },
  { t:  27.66, h: 'like imagine this' },
  { t:  28.52, h: 'goes to like <y>10</y>' },
  { t:  29.32, h: '<y>billion.</y>' },
  { t:  29.64, h: 'just imagine.' },
  { t:  30.38, h: 'nothing\'s financial advice' },
  { t:  31.60, h: 'here, right?' },
  { t:  32.28, h: 'nothing\'s financial advice.' },
  { t:  33.50, h: 'are you out of your' },
  { t:  34.16, h: 'mind?' },
];
