// captionsEcAkitaImpact.ts - batch early-crash / clip #6 `akita-3b-robinhood-impact` (variant: impact).
// Title (Mike's exact 4b wording): "Watch This: $3 Billion. A Freaking Inu."
//
// GENERATED by the canonical caption skill (video-creation/skills/captions/captions.md, montserrat
// preset). NEVER hand-edited below this header; regenerate byte-identically with:
//   python video-creation/skills/captions/build_captions.py \
//     --words video-creation/shorts/early-crash/akita-3b-robinhood-impact/whisper-words-verified.json \
//     --style montserrat --var CAPTIONS_EC_AKI \
//     --colorize "y=3,billion gr=inu" \
//     --out video-creation/remotion/src/captionsEcAkitaImpact.ts
//
// ⚠ BUILT FROM `whisper-words-verified.json`, NOT the shipped word pass. The shipped
// `whisper-words.json` SILENTLY OMITTED SPEECH in both of its >1.5 s holes (7.12-12.32 and
// 17.58-19.62): in each hole the content zone is one of Mike's own reaction-meme inserts and he keeps
// talking over it. `_patch_words.py` (in the clip folder, idempotent, fully documented) restores the
// two dropped "look at that." runs at 9.76 and 18.80, each measured on 3-4 SHORT staggered windows of
// the ENCODE-MATCHED CONTROL that agree to within 0.04 s, and confirmed by a whole-file pass of the
// final render. A missing phrase cannot be fixed with a PHRASE_CORRECTION, which is exactly why the
// contract prescribes the patched-words route.
//
// Every STT fix lives in build_captions.py PHRASE_CORRECTIONS (early-crash 2026-08-08 block), so
// nothing here is hand-authored. This clip is the IMPACT cut of clip #1's material, so clip #1's own
// whisper pass (captionsEcAkita.ts, from ITS whisper-words-verified.json) is a SECOND INDEPENDENT 1x
// pass over the same seconds of audio and is cited as such. Caption gates from tighten-plan.json,
// each VERIFIED against THIS clip's OWN word pass plus isolated re-transcribes of its own final spine
// (medium.en windows + a large-v3 whole-clip pass):
//   * GATE "1147.2-1153.4 is Whisper salad, caption from AUDIO ONLY" -> CONFIRMED and handled. This
//     clip's own pass reads "let me hover over that candle. What? Where is some right here?"; medium.en
//     on an isolated 19.30-21.90 s returns "3 billion. Let me hover over that candle.", so the hover
//     line needed NO fix. Only "where is some" is not English: 21.70-24.70 s returns "where's um right
//     here right yeah" and 21.30-23.10 s returns "kind of what where's um" -> renders "what? where's"
//     (the "um" is a filler and the house style drops fillers; no word is invented).
//   * GATE "ear-verify 1152.84-1155.82 'right here, right, yeah'" -> CONFIRMED as shipped. medium.en
//     (21.70-24.70) returns "right here right yeah" and large-v3 whole-clip returns "Right here. Yeah,".
//     No rule added.
//   * 'i freaking knew' x2 -> 'a freaking inu' (26.62 / 29.48). The clip's punchline and Mike's title.
//     Isolated, this cut never names Akita, so medium.en reads "I'm freaking a new" / "I'm freakin'
//     emu" and the shipped pass reads "knew" at p 0.52 and p 0.04. large-v3 whole-clip on this spine
//     returns "a freaking enu without any centralized exchanges", and clip #1's pass (same audio, full
//     context) returns "A freaking Inu" BOTH times at p 0.88 / 0.95. Audio was never altered.
//   * phantom leading 'And' (0.00-0.44, p 0.18) dropped: the cut's in-point IS the onset of "now", and
//     medium.en (0.00-3.40), large-v3 whole-clip and clip #1 (56.50 s) all open "now i'm going".
//   * 'i watched this' -> 'now watch this.' (3.02). medium.en (2.30-4.80) = "to the right. Now watch
//     this.", large-v3 whole-clip = "to the right now watch this", clip #1 = "now watch this." (58.82).
//   * 'is this the 3 billion' (24.42) kept as shipped: this pass and clip #1's pass agree.
//   * '3 billion' is NOT dollarised - clip #1 renders this identical spoken moment as bare "3 billion"
//     and the two shorts are cut from the same seconds of stream. Only the code-drawn THUMBNAIL carries
//     the "$" (Mike's own title wording).
//   * PROTECTED verbatim per tighten-plan.json, all present and NOT deduped: "oh my god" x2 (3.92 /
//     5.36), "hold on" x3 (6.28 / 6.52 / 6.78 - the plan calls it "hold up" off the MASTER transcript;
//     this clip's audio and clip #1 both say "hold on"), "look at that" (now x4: 9.76 / 12.32 / 18.80
//     restored + shipped), "holy crap" x2 (13.52 / 15.02), the "to the, to the, to the right" nav
//     stutter (1.66-2.78), "3 billion, 3 billion market cap" (25.16) and "a freaking inu" x2 (26.62 /
//     29.48). NO PROTECTED_DOUBLES entry was needed: cleanup()'s stutter collapse only eats ADJACENT
//     identical tokens and none of these repeats is adjacent (verified on the built array below).
//   * No tickers or brand names are spoken in this clip, so there are no terminology corrections.
//   * NO em dashes anywhere (checked mechanically before render).
export const CAPTIONS_EC_AKI: { t: number; h: string }[] = [
  { t:   0.00, h: 'now i\'m going' },
  { t:   0.82, h: 'to go over here to' },
  { t:   1.66, h: 'the, to the, to the' },
  { t:   2.78, h: 'right.' },
  { t:   3.02, h: 'now watch this.' },
  { t:   3.92, h: 'oh my god.' },
  { t:   5.36, h: 'oh my god.' },
  { t:   6.00, h: 'here.' },
  { t:   6.28, h: 'hold on.' },
  { t:   6.52, h: 'hold on.' },
  { t:   6.78, h: 'hold on.' },
  { t:   9.76, h: 'look at that.' },
  { t:  12.32, h: 'look at that.' },
  { t:  13.52, h: 'holy crap.' },
  { t:  15.02, h: 'holy crap.' },
  { t:  16.20, h: 'oh my god.' },
  { t:  18.80, h: 'look at that.' },
  { t:  19.62, h: '<y>3</y> <y>billion.</y>' },
  { t:  20.60, h: 'let me hover' },
  { t:  21.04, h: 'over that candle.' },
  { t:  21.86, h: 'what?' },
  { t:  22.18, h: 'where\'s' },
  { t:  22.94, h: 'right here?' },
  { t:  23.96, h: 'right?' },
  { t:  24.24, h: 'yeah.' },
  { t:  24.42, h: 'is this the <y>3</y>' },
  { t:  25.16, h: '<y>billion,</y> <y>3</y> <y>billion</y>' },
  { t:  26.02, h: 'market cap?' },
  { t:  26.62, h: 'a freaking <gr>inu</gr>' },
  { t:  27.56, h: 'without any centralized' },
  { t:  28.84, h: 'exchanges.' },
  { t:  29.48, h: 'a freaking <gr>inu.</gr>' },
];
