export const CAPTIONS_KEX: { t: number; h: string }[] = [
  { t:   0.00, h: 'so i have my' },
  { t:   0.82, h: 'excavator that i' },
  { t:   1.92, h: 'sold here.' },
  { t:   2.48, h: 'i was here full time' },
  { t:   3.48, h: 'in 2020 and' },
  { t:   4.26, h: 'there was a' },
  { t:   4.72, h: 'huge hurricane.' },
  { t:   5.46, h: 'my town right' },
  { t:   6.26, h: 'here, where i' },
  { t:   6.96, h: 'am in the gulf' },
  { t:   7.44, h: 'coast, took a' },
  { t:   8.26, h: 'direct hit from' },
  { t:   9.16, h: 'hurricane sally.' },
  { t:  11.12, h: 'and then it was like' },
  { t:  11.92, h: 'i got a big' },
  { t:  12.62, h: 'property and i' },
  { t:  13.50, h: 'lost like <y>100</y>' },
  { t:  14.24, h: 'trees, man.' },
  { t:  14.92, h: 'it was just all' },
  { t:  15.44, h: 'laying on the' },
  { t:  15.92, h: 'floor.' },
  { t:  16.02, h: 'it was just' },
  { t:  16.70, h: 'devastating.' },
  { t:  17.16, h: 'i was like, jeez, why' },
  { t:  18.16, h: 'would i pay' },
  { t:  18.98, h: 'another crew like' },
  { t:  20.54, h: '$20,000 or' },
  { t:  21.62, h: 'something to come' },
  { t:  22.66, h: 'clean out my' },
  { t:  23.26, h: 'property when i' },
  { t:  23.82, h: 'can just buy an' },
  { t:  24.76, h: 'excavator and do' },
  { t:  25.54, h: 'it myself?' },
  { t:  26.20, h: 'you know, just' },
  { t:  26.86, h: 'every weekend to' },
  { t:  27.66, h: 'spend like, you' },
  { t:  28.32, h: 'know, eight hours' },
  { t:  29.10, h: 'or something doing' },
  { t:  29.92, h: 'it and just have fun' },
  { t:  30.88, h: 'doing it.' },
  { t:  31.30, h: 'and i got an' },
  { t:  31.88, h: 'excavator and then' },
  { t:  32.54, h: 'it was like, then it' },
  { t:  33.26, h: 'was like, i went and' },
  { t:  33.96, h: 'sold my excavator' },
  { t:  34.82, h: 'so i can buy more' },
  { t:  35.60, h: '<g>kaspa.</g>' },
  { t:  36.44, h: 'yeah, <g>kaspa\'s</g> been' },
  { t:  37.38, h: 'really <r>weak.</r>' },
  { t:  38.18, h: 'like i know' },
  { t:  38.82, h: 'whenever something dumps' },
  { t:  40.08, h: 'like whenever <o>bitcoin</o>' },
  { t:  40.82, h: 'goes <r>down,</r> <g>kaspa</g>' },
  { t:  42.10, h: 'goes <r>down</r> and of' },
  { t:  42.78, h: 'course, right?' },
  { t:  43.34, h: 'when <o>bitcoin</o> goes' },
  { t:  44.02, h: 'back up, <g>kaspa</g>' },
  { t:  44.92, h: 'stays <r>down.</r>' },
  { t:  45.58, h: 'and then <o>bitcoin</o>' },
  { t:  46.14, h: 'goes <r>down</r> again' },
  { t:  47.50, h: '<g>kaspa</g> goes <r>down</r>' },
  { t:  48.20, h: 'some more.' },
  { t:  48.84, h: 'and then <o>bitcoin</o>' },
  { t:  49.36, h: 'goes back up' },
  { t:  50.32, h: '<g>kaspa</g> stays <r>down</r>' },
  { t:  51.14, h: 'there.' },
  { t:  51.42, h: 'yeah, it\'s not.' },
  { t:  52.18, h: 'i think the' },
  { t:  52.72, h: 'pain is gonna' },
  { t:  53.28, h: 'be relieved soon' },
  { t:  54.24, h: 'enough.' },
  { t:  54.46, h: 'even if it' },
  { t:  54.92, h: 'takes another year' },
  { t:  55.70, h: 'to be relieved.' },
  { t:  56.42, h: 'all this pain is' },
  { t:  57.26, h: 'gonna be <gr>worth</gr>' },
  { t:  57.72, h: 'it in the long run.' },
  { t:  58.48, h: 'i mean, i' },
  { t:  59.02, h: 'guess i\'m prepared' },
  { t:  59.96, h: 'man.' },
  { t:  60.14, h: 'i\'m battle-hardened.' },
  { t:  61.02, h: 'i\'m like, i\'m like, i\'m' },
  { t:  62.86, h: 'ready for some' },
  { t:  63.52, h: 'more pain, man.' },
  { t:  64.28, h: 'i don\'t care.' },
  { t:  65.74, h: 'i\'m ready for' },
  { t:  66.46, h: 'some pain.' },
];
