// captionsTC.ts — captions for batch what-if-1000x, clip #1 "1000x-math-ten-coins" (variant: long)
// Built with the CANONICAL caption skill: video-creation/skills/captions/captions.md, preset
// `montserrat` (build_captions.py -> build_montserrat, max 3 words / 5 if all <=4 chars).
// Source words: whisper-words.json (Whisper medium, transcribed on THIS exact 73.56 s spine).
// Every brand / number / fumble fix lives in build_captions.py PHRASE_CORRECTIONS (never hand-edited
// here): house coin -> housecoin, two x -> 2x, five x -> 5x, a thousand dollars -> $1,000,
// 900 k -> 900k, thousand x's -> 1000x's, god damn -> goddamn, "maybe the, your winner" -> "maybe
// your winner". The doubled "on, on" collapses in cleanup()'s stutter rule.
// Colour tags: <y> money/multiples, <o> housecoin (amber, matches the token), <r> failure/lose/
// random, <gr> winner/flying/pop/moon/buy, <g> research/investigate. No em dashes on screen.
export const CAPTIONS_TC: { t: number; h: string }[] = [
  { t:   0.00, h: 'if you put <y>$1,000</y> into' },
  { t:   1.74, h: '<y>10</y> different good' },
  { t:   3.12, h: 'coins, but you\'ve' },
  { t:   3.86, h: '<g>researched</g> them.' },
  { t:   4.80, h: 'let\'s say if you have' },
  { t:   5.60, h: 'a <r>failure</r> rate' },
  { t:   6.50, h: 'of <y>50%</y> and you <r>lose</r>' },
  { t:   8.50, h: 'money on, five' },
  { t:   9.84, h: 'of those, right?' },
  { t:  10.76, h: 'coin number six' },
  { t:  11.76, h: 'maybe it\'s going' },
  { t:  12.38, h: 'to like underperform.' },
  { t:  13.32, h: 'you only get a <y>2x</y>' },
  { t:  14.30, h: 'coin number seven.' },
  { t:  15.32, h: 'you might get' },
  { t:  15.70, h: 'a <y>5x</y> one' },
  { t:  16.60, h: 'number eight.' },
  { t:  17.20, h: 'you might get' },
  { t:  17.74, h: 'a <y>10x</y> coin' },
  { t:  18.72, h: 'number nine.' },
  { t:  19.36, h: 'you might get' },
  { t:  19.76, h: 'your <y>50x</y> and then' },
  { t:  20.86, h: 'maybe your <gr>winner,</gr>' },
  { t:  22.34, h: 'your real <gr>winner</gr>' },
  { t:  22.96, h: 'is going to' },
  { t:  23.36, h: 'do like a <y>900x</y> or' },
  { t:  24.80, h: '<y>1000x.</y>' },
  { t:  25.44, h: 'so you\'re going' },
  { t:  25.86, h: 'to make that' },
  { t:  26.28, h: 'money.' },
  { t:  26.48, h: 'but if you' },
  { t:  26.98, h: 'identify a group' },
  { t:  28.30, h: 'of good memes' },
  { t:  29.88, h: 'right?' },
  { t:  30.44, h: 'that you think' },
  { t:  31.36, h: 'will probably run' },
  { t:  32.20, h: 'again and you' },
  { t:  33.02, h: 'just invest in' },
  { t:  33.82, h: 'them.' },
  { t:  34.10, h: 'but the ones that do' },
  { t:  35.24, h: 'could just go' },
  { t:  36.16, h: '<gr>flying.</gr>' },
  { t:  36.78, h: 'maybe <o>housecoin</o> will' },
  { t:  37.64, h: 'be one of them.' },
  { t:  38.34, h: 'maybe it won\'t.' },
  { t:  39.02, h: 'right.' },
  { t:  39.42, h: 'if <o>housecoin</o> does' },
  { t:  40.98, h: 'fly at a <y>900k</y>' },
  { t:  43.08, h: 'market cap, i' },
  { t:  43.96, h: 'mean, you could' },
  { t:  45.18, h: 'be looking at' },
  { t:  45.98, h: '<y>1000x.</y>' },
  { t:  46.76, h: 'there\'s going to' },
  { t:  47.18, h: 'be a lot of' },
  { t:  48.18, h: '<y>1000x\'s</y> out there' },
  { t:  49.50, h: 'right now as' },
  { t:  50.30, h: 'the time to <gr>buy</gr>' },
  { t:  51.16, h: 'because those bulls' },
  { t:  52.18, h: 'start running.' },
  { t:  52.74, h: 'they\'re going to' },
  { t:  53.10, h: 'start running probably' },
  { t:  54.18, h: 'pretty soon.' },
  { t:  54.82, h: 'you can\'t just be' },
  { t:  55.70, h: '<r>random</r> about your' },
  { t:  56.44, h: 'plays, right?' },
  { t:  57.26, h: 'you have to like' },
  { t:  57.98, h: 'really <g>investigate</g> what' },
  { t:  59.34, h: 'you\'re buying because' },
  { t:  60.16, h: 'you\'re buying <y>10</y>' },
  { t:  61.12, h: 'different coins and' },
  { t:  62.04, h: 'you\'re expecting <y>1000x</y>' },
  { t:  63.30, h: 'on them.' },
  { t:  63.62, h: 'you have to' },
  { t:  64.04, h: 'really put in' },
  { t:  64.52, h: 'a lot of' },
  { t:  64.90, h: '<g>research</g> on all' },
  { t:  65.58, h: '<y>10,</y> all the' },
  { t:  66.18, h: 'coins in my' },
  { t:  66.74, h: 'community that we' },
  { t:  67.42, h: 'call.' },
  { t:  67.68, h: 'we sit on some good' },
  { t:  68.42, h: 'ones and some' },
  { t:  69.20, h: 'really good ones' },
  { t:  69.80, h: 'and every now' },
  { t:  70.36, h: 'and then it just like' },
  { t:  71.36, h: '<gr>pop</gr> and just go to' },
  { t:  72.34, h: 'the goddamn <gr>moon,</gr>' },
  { t:  73.30, h: 'man.' },
];
