export const CAPTIONS_KDI: { t: number; h: string }[] = [
  { t:   0.00, h: '<g>kaspa</g> today dip' },
  { t:   1.46, h: 'below <y>2.6</y> cents.' },
  { t:   3.06, h: 'it was like <y>2.59</y>' },
  { t:   4.84, h: 'cents.' },
  { t:   5.46, h: 'that\'s when i' },
  { t:   6.06, h: 'bought some more.' },
  { t:   7.00, h: 'yeah wow, this' },
  { t:   7.58, h: 'gives an <gr>opportunity</gr>' },
  { t:   8.26, h: 'to buy more.' },
  { t:   9.00, h: 'i know in the long' },
  { t:   9.60, h: 'run you got' },
  { t:  10.16, h: '<gr>conviction,</gr> right?' },
  { t:  10.82, h: 'in the long run' },
  { t:  11.34, h: '<g>kaspa</g> is going' },
  { t:  11.94, h: 'to be <gr>flying</gr>' },
  { t:  12.54, h: 'same thing with' },
  { t:  13.14, h: '<g>tao</g>' },
];
