export const CAPTIONS_CRD: { t: number; h: string }[] = [
  { t:   0.00, h: 'why do i' },
  { t:   0.86, h: 'think <gr>cooper</gr> is' },
  { t:   1.56, h: 'pretty good?' },
  { t:   2.18, h: 'yeah, i\'m not' },
  { t:   3.00, h: 'looking from a' },
  { t:   3.58, h: 'dev perspective.' },
  { t:   4.22, h: 'i\'m just looking' },
  { t:   4.84, h: 'at him from the idea' },
  { t:   5.74, h: 'that it is not kind' },
  { t:   6.94, h: 'of stupid.' },
  { t:   7.54, h: 'i mean, it\'s not' },
  { t:   8.22, h: 'stupid.' },
  { t:   8.74, h: 'you know, it\'s not a' },
  { t:   9.50, h: 'dog with a pipe.' },
  { t:  10.34, h: 'so meet the' },
  { t:  10.92, h: 'honorary member of' },
  { t:  11.72, h: 'our design team' },
  { t:  12.54, h: '<gr>cooper.</gr>' },
  { t:  13.12, h: 'so this is a dog.' },
  { t:  14.50, h: 'this is a real dog' },
  { t:  15.78, h: 'in the <gr>robinhood</gr>' },
  { t:  16.66, h: 'office.' },
  { t:  17.54, h: 'you\'re like, <b>toshi</b>' },
  { t:  18.30, h: 'is like brian' },
  { t:  19.16, h: 'armstrong\'s real cat' },
  { t:  20.58, h: 'and so on.' },
  { t:  21.22, h: 'so this is a real' },
  { t:  22.20, h: 'dog and it\'s a' },
  { t:  23.36, h: '<gr>robinhood</gr> dog in' },
  { t:  24.44, h: 'the headquarters.' },
  { t:  25.00, h: 'so apparently based' },
  { t:  26.36, h: 'on what i see here' },
  { t:  27.26, h: 'so somebody made' },
  { t:  27.98, h: 'a meme out of it' },
  { t:  29.04, h: 'and retweeted, they' },
  { t:  29.86, h: 'retweeted the <gr>robinhood</gr>' },
  { t:  31.02, h: 'post about <gr>cooper.</gr>' },
  { t:  31.76, h: 'if there\'s anything' },
  { t:  32.56, h: 'second to what' },
  { t:  33.36, h: 'if like in my' },
  { t:  34.30, h: 'opinion, what if' },
  { t:  34.94, h: 'should be the' },
  { t:  35.38, h: 'on the top of' },
  { t:  36.28, h: '<gr>robinhood</gr> meme, right?' },
  { t:  37.02, h: 'but if there\'s' },
  { t:  37.52, h: 'anything second to' },
  { t:  38.34, h: 'that, just because' },
  { t:  39.08, h: 'of that, this is it.' },
  { t:  39.84, h: 'i can\'t think' },
  { t:  40.38, h: 'of another and' },
  { t:  41.34, h: 'still insanely early' },
  { t:  42.28, h: 'right?' },
  { t:  42.64, h: 'because it\'s a' },
  { t:  43.52, h: '<y>2.37</y> market cap.' },
  { t:  45.08, h: 'i\'m sorry.' },
  { t:  46.06, h: 'i, a <y>237k</y>' },
  { t:  47.78, h: 'market cap.' },
  { t:  48.56, h: 'now' },
  { t:  49.50, h: 'the other one' },
  { t:  50.16, h: 'is like' },
  { t:  51.16, h: 'if we go look at' },
  { t:  51.98, h: 'russell' },
  { t:  52.98, h: 'is the dog of' },
  { t:  53.88, h: 'brian armstrong.' },
  { t:  56.66, h: 'russell, and we' },
  { t:  57.68, h: 'did a nice <y>12x</y> on' },
  { t:  59.00, h: 'this and the end of' },
  { t:  59.72, h: 'last year in my' },
  { t:  60.68, h: 'group, <gr>cooper</gr> is' },
  { t:  61.22, h: 'just like a' },
  { t:  61.88, h: 'couple of days' },
  { t:  62.36, h: 'old.' },
  { t:  62.90, h: 'it\'s six days old.' },
  { t:  64.22, h: 'i\'m actually considering' },
  { t:  65.28, h: '<gr>cooper</gr> right now.' },
];
