// captionsEcEndure.ts - batch early-crash / clip #5 `endure-the-pain` (variant: full).
// Title (Mike's exact 4b wording, the "Meme Coin Truth: " prepend is his):
//   "Meme Coin Truth: You'll Be Lucky You Endured the Pain"
//
// GENERATED by the canonical caption skill (video-creation/skills/captions/captions.md, montserrat
// preset). NEVER hand-edited below this header; regenerate byte-identically with:
//   python video-creation/shorts/early-crash/endure-the-pain/_patch_words.py
//   python video-creation/skills/captions/build_captions.py //     --words video-creation/shorts/early-crash/endure-the-pain/whisper-words-verified.json //     --style montserrat --var CAPTIONS_EC_ENDURE //     --colorize 'o=bitcoin gr=robinhood y=lucky' //     --out video-creation/remotion/src/captionsEcEndure.ts
//
// The ONE word this clip's shipped whisper pass DROPPED is restored by `_patch_words.py` (which
// documents every rejected fix too); no PHRASE_CORRECTIONS entry exists for this clip, because a
// missing word cannot be expressed as one. Caption gates from tighten-plan.json (clip #5), each
// VERIFIED against THIS clip's OWN whisper-words.json plus isolated medium.en re-transcribes of its
// own final spine (the flags derive from the MASTER transcript and are wrong as often as right):
//   * 'we're not feeling yet' (1526.20) -> 'we're not feeling IT yet'. CONFIRMED, and the missing
//     token is patched in: word-timed 20.40-22.80 puts "it" at 21.44-21.64 (p 0.96) and a tight
//     20.60-22.20 pass reads the same. Renders as 'we're not feeling' / 'it yet.'
//   * opener: gate expected 'good news is' (the drawled pre-'the' was relocked out) and allowed
//     'The good news is' IF heard. It IS heard - the shipped pass and an isolated 0.00-2.60 pass
//     both return "The good news is that eventually" - so 'the good news is that' ships.
//   * 'the Alps' -> 'the alts' (381.26): already 'alts' in this clip's own pass; isolated
//     7.60-9.20 confirms "buying the alts". No rule added.
//   * 'Robin Hood' -> 'Robinhood' (383.04): already ONE token in this clip's own pass; isolated
//     9.20-10.80 confirms "onto the Robinhood chain". No rule added.
//   * 'he hasn't checked out' -> 'who hasn't checked out' (395.06): REJECTED on this clip's audio.
//     The 'who' is already earlier in the sentence: the shipped pass and an isolated 16.60-19.80
//     pass both read "for anybody WHO'S in crypto right now AND hasn't checked out".
//   * 'the the pain' stutter -> 'the pain': already ONE stretched 'the' token upstream, so nothing
//     collapses and no PROTECTED_DOUBLES entry is needed.
//   * the REMOVED fragment 'is we're going to start the bull run' (tighten span 1536.58-1538.55)
//     appears NOWHERE in the word stream. Verified absent from the built array.
//   * PROTECTED persona devices, kept verbatim and verified present in the array below:
//     - the six-limb anaphora chain (2.76-8.64 here) INCLUDING the deliberate doubled 'buying
//       crypto' ('buy crypto.' 3.14 and 'be buying crypto.' 5.42). Non-adjacent, so cleanup()'s
//       stutter collapse never sees it and no PROTECTED_DOUBLES key is required.
//     - the escalating doubling 'eventually we're going to feel it' (21.92) / 'eventually we're
//       going to start feeling it' (23.00). Both survive intact.
//   * Colour is minimal, matching the steady-conviction register: <o>bitcoin</o> (house orange),
//     <gr>robinhood</gr> (green, same as the sibling early-crash clips) and one <y>lucky</y> on the
//     title word at the climax. No numbers are spoken in this clip.
//   * NO em dashes anywhere (checked mechanically before render).
export const CAPTIONS_EC_ENDURE: { t: number; h: string }[] = [
  { t:   0.00, h: 'the good news is that' },
  { t:   1.42, h: 'eventually in the' },
  { t:   2.16, h: 'long run, people' },
  { t:   2.82, h: 'are going to' },
  { t:   3.14, h: 'buy crypto.' },
  { t:   3.76, h: 'people are going' },
  { t:   4.12, h: 'to be buying' },
  { t:   4.50, h: '<o>bitcoin.</o>' },
  { t:   5.12, h: 'they\'re going to' },
  { t:   5.42, h: 'be buying crypto.' },
  { t:   6.20, h: 'they\'re going to' },
  { t:   6.44, h: 'be buying meme' },
  { t:   7.00, h: 'coins.' },
  { t:   7.42, h: 'they\'re going to' },
  { t:   7.70, h: 'be buying the' },
  { t:   8.24, h: 'alts.' },
  { t:   8.70, h: 'they\'re going to' },
  { t:   9.00, h: 'be going onto' },
  { t:   9.58, h: 'the <gr>robinhood</gr> chain.' },
  { t:  10.40, h: 'they\'re going to' },
  { t:  10.74, h: 'learn how to' },
  { t:  11.20, h: 'swap.' },
  { t:  11.78, h: 'so maybe they' },
  { t:  12.20, h: 'don\'t need centralized' },
  { t:  12.92, h: 'exchanges as much.' },
  { t:  13.84, h: 'so in the long run' },
  { t:  15.02, h: 'the outlook is' },
  { t:  15.68, h: 'good and it\'s' },
  { t:  16.32, h: 'really good for' },
  { t:  16.88, h: 'anybody who\'s in' },
  { t:  17.56, h: 'crypto right now' },
  { t:  18.14, h: 'and hasn\'t checked' },
  { t:  18.80, h: 'out.' },
  { t:  19.12, h: 'we\'re going into' },
  { t:  19.66, h: 'economic expansion.' },
  { t:  20.88, h: 'we\'re not feeling' },
  { t:  21.52, h: 'it yet.' },
  { t:  21.92, h: 'eventually we\'re going' },
  { t:  22.50, h: 'to feel it.' },
  { t:  23.00, h: 'eventually we\'re going' },
  { t:  23.54, h: 'to start feeling' },
  { t:  24.20, h: 'it.' },
  { t:  24.44, h: 'the bull run is' },
  { t:  25.06, h: 'going to start' },
  { t:  25.62, h: 'over again.' },
  { t:  26.20, h: 'and a lot of you' },
  { t:  27.16, h: 'guys are going' },
  { t:  27.68, h: 'to be <y>lucky</y>' },
  { t:  28.36, h: 'that you just try to' },
  { t:  29.52, h: 'endure the pain' },
  { t:  30.76, h: 'that we\'ve been' },
  { t:  31.54, h: 'seeing.' },
];
