export const CAPTIONS_TRADING_AGAINST_OURSELVES: { t: number; h: string }[] = [
  { t:   0.00, h: 'i\'m over here with a' },
  { t:   0.82, h: 'lot of skepticism' },
  { t:   2.04, h: 'with these robinhood' },
  { t:   2.92, h: 'memes right now.' },
  { t:   3.88, h: 'good, i keep' },
  { t:   4.28, h: 'saying it\'s only' },
  { t:   5.30, h: 'us trading' },
  { t:   6.36, h: 'against ourselves with' },
  { t:   7.56, h: 'these robinhood memes' },
  { t:   8.78, h: 'right, with any' },
  { t:   9.70, h: 'new memes, it' },
  { t:  10.42, h: 'doesn\'t have to' },
  { t:  11.02, h: 'be robinhood, right?' },
  { t:  12.38, h: 'and because majority' },
  { t:  13.08, h: 'of us have all' },
  { t:  14.32, h: '<r>checked</r> out.' },
  { t:  14.86, h: 'i don\'t know what that' },
  { t:  15.52, h: 'percentage is.' },
  { t:  16.52, h: 'if it\'s 90%, if it\'s' },
  { t:  17.94, h: '70%, but i' },
  { t:  18.98, h: 'think it\'s like' },
  { t:  19.36, h: 'well over 50%.' },
  { t:  21.04, h: 'the first meme' },
  { t:  21.80, h: 'to really, really' },
  { t:  22.90, h: 'make a pump' },
  { t:  23.44, h: 'is cash cat.' },
  { t:  25.22, h: 'and all these' },
  { t:  26.16, h: 'people up here' },
  { t:  27.28, h: 'right?' },
  { t:  27.48, h: 'like all these' },
  { t:  28.34, h: 'people who were' },
  { t:  29.12, h: 'buying up here' },
  { t:  30.10, h: 'they\'ve already been' },
  { t:  30.80, h: '<gr>burned.</gr>' },
  { t:  31.42, h: 'like, oh, i\'m' },
  { t:  31.92, h: 'gonna get in' },
  { t:  32.42, h: 'on it.' },
  { t:  32.96, h: 'i\'m gonna get' },
  { t:  33.32, h: 'in on it.' },
  { t:  33.90, h: 'and they\'re buying' },
  { t:  34.52, h: 'up here.' },
  { t:  35.20, h: 'well, everybody down' },
  { t:  36.12, h: 'here who bought' },
  { t:  37.10, h: 'down here is' },
  { t:  37.94, h: 'selling up here' },
  { t:  38.68, h: 'and they\'re getting' },
  { t:  39.34, h: '<gr>burned.</gr>' },
  { t:  39.88, h: 'so there\'s a' },
  { t:  40.24, h: 'whole ton of' },
  { t:  40.74, h: 'people getting <gr>burned</gr>' },
  { t:  41.52, h: 'at this point' },
  { t:  42.24, h: 'and they\'re down.' },
  { t:  43.22, h: 'they\'ve probably <r>checked</r>' },
  { t:  43.94, h: 'out, i\'m like, yeah, i\'m' },
  { t:  45.80, h: 'done with robinhood' },
  { t:  46.62, h: 'memes.' },
  { t:  46.90, h: 'like a huge' },
  { t:  47.96, h: 'amount of them.' },
  { t:  48.88, h: 'this is one up to' },
  { t:  49.58, h: '<y>220</y> million.' },
  { t:  50.74, h: 'so that\'s a' },
  { t:  51.32, h: 'lot of people' },
  { t:  52.12, h: 'who are like not' },
  { t:  53.08, h: 'gonna rotate.' },
  { t:  53.96, h: 'they\'ve just got' },
  { t:  54.44, h: '<gr>burned.</gr>' },
  { t:  55.00, h: 'there\'s less people' },
  { t:  55.58, h: 'that are absorbing' },
  { t:  56.22, h: 'the hype about' },
  { t:  56.98, h: 'robinhood memes.' },
  { t:  58.66, h: 'the problem here' },
  { t:  59.22, h: 'is like again' },
  { t:  60.40, h: 'it\'s like, we\'re' },
  { t:  60.84, h: 'trading against' },
  { t:  61.40, h: 'ourselves here?' },
  { t:  62.38, h: 'there\'s no new' },
  { t:  63.08, h: 'retail.' },
  { t:  63.88, h: 'more than half of' },
  { t:  64.54, h: 'everybody in crypto' },
  { t:  65.28, h: 'is <r>checked</r> out' },
  { t:  65.96, h: 'until <y>october.</y>' },
  { t:  67.00, h: 'we just don\'t know.' },
  { t:  68.50, h: 'it\'ll be like, we\'re just' },
  { t:  69.30, h: 'buying blind right' },
  { t:  70.44, h: 'now.' },
  { t:  70.86, h: 'wait six months' },
  { t:  71.52, h: 'and see what' },
  { t:  72.02, h: 'happens.' },
  { t:  73.06, h: 'which could work' },
  { t:  73.64, h: 'out, spend $100' },
  { t:  74.76, h: 'on <y>10</y> different' },
  { t:  75.86, h: 'memes and you' },
  { t:  76.76, h: 'lose money on' },
  { t:  77.76, h: 'nine of them, but all' },
  { t:  78.86, h: 'it takes is' },
  { t:  79.36, h: 'one of them to do' },
  { t:  80.08, h: 'like a thousand' },
  { t:  80.80, h: 'x or something' },
  { t:  81.62, h: 'or even a' },
  { t:  82.04, h: 'hundred x.' },
];
