export const CAPTIONS_OCTOBER_NOT_ALLOWED_RED: { t: number; h: string }[] = [
  { t:   0.00, h: 'like a lot of' },
  { t:   0.48, h: 'people are <r>checked</r>' },
  { t:   1.24, h: 'out right now' },
  { t:   2.04, h: 'and they\'re not' },
  { t:   2.58, h: 'coming back in' },
  { t:   3.32, h: '<y>october.</y>' },
  { t:   3.94, h: 'they\'re gonna buy' },
  { t:   4.72, h: 'in <y>october.</y>' },
  { t:   5.46, h: 'i keep saying' },
  { t:   5.98, h: 'they\'re gonna cause' },
  { t:   6.66, h: '<y>october</y> to be' },
  { t:   7.50, h: '<gr>green.</gr>' },
  { t:   8.02, h: 'i mean personally' },
  { t:   8.56, h: 'i think' },
  { t:   9.22, h: 'something extraordinarily' },
  { t:  10.44, h: 'bad would have' },
  { t:  11.56, h: 'to happen for' },
  { t:  12.52, h: '<y>october</y> to be' },
  { t:  13.64, h: '<r>red</r> because there\'s' },
  { t:  14.48, h: 'so many people' },
  { t:  15.80, h: 'that\'ll be buying' },
  { t:  16.54, h: 'back in <y>october.</y>' },
  { t:  17.78, h: 'they\'re not even' },
  { t:  18.48, h: 'allowed, not' },
  { t:  19.44, h: 'allowed to' },
  { t:  20.12, h: 'go <r>red.</r>' },
  { t:  20.72, h: 'even if this' },
  { t:  21.18, h: 'really bad, like' },
  { t:  22.02, h: 'how bad could' },
  { t:  22.82, h: 'it get?' },
  { t:  23.28, h: 'let\'s say this is the' },
  { t:  24.20, h: 'whole thing everybody' },
  { t:  24.90, h: 'always gives us' },
  { t:  25.58, h: 'an example.' },
  { t:  26.26, h: 'china invades taiwan.' },
  { t:  27.84, h: 'okay, that\'s, you' },
  { t:  28.34, h: 'know, extraordinarily bearish.' },
  { t:  29.82, h: 'i still think' },
  { t:  30.56, h: 'there\'s gonna be' },
  { t:  31.06, h: 'a huge chunk' },
  { t:  31.88, h: 'of those four' },
  { t:  32.58, h: '-year cycle zombies' },
  { t:  33.52, h: 'that sold at the end' },
  { t:  34.66, h: 'of last year.' },
  { t:  35.66, h: 'maybe half of' },
  { t:  36.46, h: 'them are maybe' },
  { t:  37.02, h: 'even 20 or 10%.' },
  { t:  38.24, h: 'they\'re still gonna' },
  { t:  38.98, h: 'buy back in' },
  { t:  39.76, h: '<y>october.</y>' },
  { t:  40.48, h: 'and it was like, wow' },
  { t:  41.10, h: 'there\'s a good' },
  { t:  41.44, h: 'deal.' },
  { t:  41.78, h: 'let me buy back in.' },
  { t:  42.66, h: 'we\'ll see what' },
  { t:  43.14, h: 'happens.' },
  { t:  43.66, h: 'maybe i\'ll be' },
  { t:  44.06, h: 'proven wrong, but' },
  { t:  44.82, h: 'i can\'t imagine' },
  { t:  45.56, h: 'a very, very bad' },
  { t:  46.64, h: '<y>october.</y>' },
];
