// Captions for October-pumps clip #1 "whatif-cto-100x-call" (variant: full).
// COPIED VERBATIM from the clip folder's captions.ts, which is the output of the CANONICAL
// captions skill (video-creation/skills/captions/build_captions.py --style montserrat).
// Never hand-authored, never lifted from another composition.
// STT-ONLY corrections applied (grouping / lowercase / colour spans untouched, and mirrored
// back into the clip's captions.ts so both copies stay byte-identical):
//   89.42/90.54  'enlisted on robert' + 'hood, i think' -> 'enlisted on' + 'robinhood, i think'
//                (Whisper splits Robinhood into two words; regrouped on the word onset 90.32)
//   91.00        'whatever we'll make'                  -> 'whatif will make'
//                (Whisper mishears the coin name WHATIF as 'whatever'; flagged in clip-plan.json)
export const CAPTIONS_WHATIF_CTO_100X_CALL: { t: number; h: string }[] = [
  { t:   0.00, h: 'so when it' },
  { t:   0.38, h: 'comes to what' },
  { t:   0.98, h: 'if, what if is now' },
  { t:   2.52, h: 'so what if it\'s a' },
  { t:   3.24, h: 'cto right now?' },
  { t:   4.56, h: 'so the original' },
  { t:   5.38, h: 'person that launched' },
  { t:   6.60, h: 'the actual tokens' },
  { t:   7.66, h: 'was just somebody' },
  { t:   8.60, h: 'who just launched' },
  { t:   9.30, h: 'it and they' },
  { t:   9.68, h: 'didn\'t want to' },
  { t:  10.00, h: 'do anything with' },
  { t:  10.58, h: 'it.' },
  { t:  10.74, h: 'because my grief' },
  { t:  11.44, h: 'with what if was that' },
  { t:  12.50, h: 'it was just' },
  { t:  13.04, h: 'linked to a' },
  { t:  13.94, h: 'twitter community.' },
  { t:  15.06, h: 'it would constantly' },
  { t:  16.02, h: 'like every 12' },
  { t:  16.62, h: 'hours, switch to' },
  { t:  17.74, h: 'a new twitter' },
  { t:  18.24, h: 'community.' },
  { t:  18.92, h: 'i was like, this is' },
  { t:  19.56, h: 'crazy shady.' },
  { t:  20.72, h: 'and that\'s the' },
  { t:  21.06, h: 'only thing that' },
  { t:  21.50, h: 'prevented me from' },
  { t:  22.12, h: 'buying it.' },
  { t:  22.92, h: 'other than that' },
  { t:  23.60, h: 'the concept behind' },
  { t:  24.44, h: 'it is pretty' },
  { t:  25.06, h: 'good.' },
  { t:  25.44, h: 'what if?' },
  { t:  26.30, h: 'so i think' },
  { t:  27.02, h: 'it has some good' },
  { t:  27.54, h: 'potential just because' },
  { t:  28.44, h: 'of the meme' },
  { t:  28.84, h: 'itself.' },
  { t:  29.22, h: 'surprise, nobody ever' },
  { t:  30.10, h: 'thought of it' },
  { t:  30.48, h: 'before.' },
  { t:  31.12, h: 'but yeah, it' },
  { t:  31.68, h: 'makes sense if' },
  { t:  32.28, h: 'it\'s a cto.' },
  { t:  33.04, h: 'then they got a good' },
  { t:  33.56, h: 'website.' },
  { t:  34.44, h: 'so now it\'s a go' },
  { t:  35.28, h: 'on this.' },
  { t:  35.86, h: 'it\'s a go.' },
  { t:  36.62, h: 'i think where' },
  { t:  37.02, h: 'the community is' },
  { t:  37.70, h: 'being drawn around' },
  { t:  38.50, h: 'it, right?' },
  { t:  39.28, h: 'everybody, all the' },
  { t:  39.74, h: 'crypto influencers, everybody\'s' },
  { t:  41.08, h: 'rallying the communities' },
  { t:  42.10, h: 'around it.' },
  { t:  42.82, h: 'i think just' },
  { t:  43.30, h: 'because of that' },
  { t:  44.22, h: 'it\'s got some good' },
  { t:  45.06, h: 'strength.' },
  { t:  45.50, h: 'it could go' },
  { t:  45.96, h: 'in the short' },
  { t:  46.38, h: 'term to <y>20</y>' },
  { t:  47.02, h: 'million or something' },
  { t:  47.64, h: 'like that.' },
  { t:  48.12, h: 'we\'re talking about' },
  { t:  48.52, h: 'a <y>5x</y> from here.' },
  { t:  49.54, h: 'it could be' },
  { t:  49.88, h: 'a scenario, like' },
  { t:  50.58, h: 'i said, where' },
  { t:  51.24, h: 'we really do' },
  { t:  52.00, h: 'get a new' },
  { t:  52.50, h: 'bottom and in' },
  { t:  53.22, h: 'the few weeks' },
  { t:  53.82, h: 'in august and' },
  { t:  54.68, h: 'then the bulls' },
  { t:  55.70, h: 'start to run' },
  { t:  56.34, h: 'and like in the' },
  { t:  56.88, h: 'beginning of september' },
  { t:  57.68, h: 'and then everything' },
  { t:  59.12, h: 'is like flying' },
  { t:  59.92, h: 'in october, the' },
  { t:  60.90, h: 'opposite of what' },
  { t:  61.48, h: 'the four year' },
  { t:  61.88, h: 'cycle zombies are' },
  { t:  62.74, h: 'expecting, right?' },
  { t:  63.66, h: 'and this thing' },
  { t:  64.30, h: 'is, that\'s just' },
  { t:  64.96, h: 'a couple of' },
  { t:  65.44, h: 'months away, right?' },
  { t:  66.34, h: 'this thing is' },
  { t:  66.78, h: 'going to be' },
  { t:  67.12, h: 'around.' },
  { t:  67.56, h: 'and what happens' },
  { t:  68.00, h: 'with this?' },
  { t:  68.68, h: 'it could be' },
  { t:  69.36, h: 'forget about <y>20</y>' },
  { t:  70.10, h: 'million.' },
  { t:  70.56, h: 'it could go' },
  { t:  71.54, h: 'to 100 million' },
  { t:  72.34, h: 'or maybe, it' },
  { t:  73.64, h: 'could even be' },
  { t:  74.12, h: 'like <y>100x</y> from here.' },
  { t:  75.20, h: 'not financial advice.' },
  { t:  76.42, h: 'never financial advice' },
  { t:  77.60, h: 'in this video' },
  { t:  78.42, h: 'man.' },
  { t:  78.64, h: 'are you out of your' },
  { t:  79.30, h: 'mind?' },
  { t:  79.94, h: 'if crypto, twitter' },
  { t:  80.98, h: 'and all the' },
  { t:  81.32, h: 'communities are going' },
  { t:  82.06, h: 'to rally behind' },
  { t:  83.12, h: 'what if, and push this' },
  { t:  84.30, h: 'thing extremely high' },
  { t:  85.50, h: 'then if there\'s' },
  { t:  87.40, h: 'anything secondary to' },
  { t:  88.48, h: 'cashcat to be' },
  { t:  89.42, h: 'enlisted on' },
  { t:  90.32, h: 'robinhood, i think' },
  { t:  91.00, h: 'whatif will make' },
  { t:  91.76, h: 'it.' },
  { t:  91.98, h: 'and if that\'s' },
  { t:  92.42, h: 'the case, we\'re' },
  { t:  93.02, h: 'talking a lot' },
  { t:  94.12, h: 'an extraordinarily high' },
  { t:  95.06, h: 'market cap' },
];
