// captions for whatif-peanut-52x (batch: whatif, clip #3, variant: full).
//
// Built by the CANONICAL captions skill on the DESILENCED spine's own Whisper word timings:
//   python video-creation/skills/captions/build_captions.py \
//     --words video-creation/shorts/whatif/whatif-peanut-52x/spine16k.json \
//     --style montserrat --var CAPTIONS_WHATIF_PEANUT_52X \
//     --colorize "gr=robinhood,52x,bullish,crushing y=200k,billion,billions,thousand o=peanut"
//
// The ONLY hand edits are the STT-ONLY corrections below (documented so they can be mirrored /
// re-derived); grouping, timings and case all come verbatim from the builder. No em dashes.
//   - "dexgridder"  -> "dexscreener"  (Whisper mishears the site name; delegation STT fix)
//   - "conscious"   -> "conscience"   ("in good conscience"; NOT added to the global CORRECTIONS
//                                      dict because "conscious" is a real word that can occur legit
//                                      elsewhere in the catalogue, so it is fixed here per-clip)
//   - "<gr>floodgates</gr>"           (colour tag added; the Robinhood retail floodgates beat)
export const CAPTIONS_WHATIF_PEANUT_52X: { t: number; h: string }[] = [
  { t:   0.00, h: 'i think what' },
  { t:   0.60, h: 'if is <gr>crushing</gr>' },
  { t:   1.60, h: 'it?' },
  { t:   1.96, h: 'yeah, the crazy' },
  { t:   2.54, h: 'thing about this' },
  { t:   3.44, h: 'when i saw this as' },
  { t:   4.42, h: 'way back as far back' },
  { t:   6.02, h: 'as like <y>200k,</y> it was' },
  { t:   7.56, h: 'just like this' },
  { t:   8.26, h: 'really crappy profile' },
  { t:   9.38, h: 'with <gr>dexscreener,</gr> and' },
  { t:  10.34, h: 'it was just' },
  { t:  10.70, h: 'constantly switching between' },
  { t:  12.14, h: 'random twitter communities.' },
  { t:  13.64, h: 'and i told my' },
  { t:  14.22, h: 'discord today, i' },
  { t:  15.02, h: 'was like, i can\'t in' },
  { t:  15.74, h: 'good conscience call' },
  { t:  16.90, h: 'a coin that has' },
  { t:  18.04, h: 'something, some setup' },
  { t:  19.34, h: 'like that.' },
  { t:  19.92, h: 'but apparently like' },
  { t:  20.66, h: 'there\'s a <gr>cto</gr>' },
  { t:  22.22, h: 'with it.' },
  { t:  23.50, h: 'now there\'s a' },
  { t:  24.46, h: 'good <gr>team</gr> behind' },
  { t:  25.66, h: 'it.' },
  { t:  26.04, h: 'they are probably' },
  { t:  27.08, h: 'going to get' },
  { t:  27.40, h: 'centralized exchanges.' },
  { t:  28.54, h: 'and oh, it' },
  { t:  28.92, h: 'makes me ponder.' },
  { t:  29.60, h: 'yeah, i look at the' },
  { t:  31.22, h: '<o>peanut</o> scenario, right?' },
  { t:  32.54, h: 'so with <o>peanut,</o>' },
  { t:  33.88, h: 'i caught it' },
  { t:  34.22, h: 'at a very low' },
  { t:  34.82, h: 'market cap as' },
  { t:  35.86, h: '<o>peanut</o> was pumping.' },
  { t:  36.82, h: 'i was like, oh, let' },
  { t:  37.70, h: 'me just take a' },
  { t:  38.52, h: 'chance.' },
  { t:  39.06, h: 'and i bought' },
  { t:  39.70, h: 'some <o>peanut</o> and' },
  { t:  40.52, h: 'ended up doing' },
  { t:  41.08, h: 'a <gr>52x.</gr>' },
  { t:  42.50, h: 'so i mean, this' },
  { t:  43.02, h: 'could be one' },
  { t:  43.50, h: 'of those scenarios' },
  { t:  44.12, h: 'as well.' },
  { t:  44.64, h: 'so <gr>robinhood</gr> chain' },
  { t:  45.56, h: 'very, nice, very' },
  { t:  46.58, h: '<gr>bullish.</gr>' },
  { t:  47.50, h: 'just because it\'s' },
  { t:  48.54, h: '<gr>robinhood,</gr> i mean' },
  { t:  49.52, h: 'it\'s crazy.' },
  { t:  50.40, h: '<gr>robinhood</gr> is more' },
  { t:  51.24, h: '<gr>bullish</gr> than actually' },
  { t:  53.00, h: 'coinbase and base' },
  { t:  54.46, h: 'tokens, right?' },
  { t:  55.14, h: 'they can open up' },
  { t:  55.68, h: 'their doors, the' },
  { t:  56.60, h: '<gr>floodgates</gr> open to' },
  { t:  57.60, h: 'retail, you know' },
  { t:  58.46, h: 'lots and lots of' },
  { t:  59.22, h: 'retail, right?' },
  { t:  60.22, h: 'stock retail.' },
  { t:  60.94, h: 'now it\'s going' },
  { t:  61.50, h: 'to be listed' },
  { t:  62.16, h: 'on centralized exchanges.' },
  { t:  64.42, h: 'and the hopes' },
  { t:  65.14, h: 'is that in the long' },
  { t:  66.00, h: 'run, it gets' },
  { t:  66.74, h: 'recognized by <gr>robinhood</gr>' },
  { t:  68.38, h: 'and it gets' },
  { t:  68.68, h: 'listed on the' },
  { t:  69.26, h: 'app.' },
  { t:  69.54, h: 'because then it' },
  { t:  70.10, h: 'would be like' },
  { t:  70.52, h: 'a <y>billion</y> dollars.' },
  { t:  71.62, h: 'so like you\'re' },
  { t:  72.32, h: 'looking at like' },
  { t:  72.96, h: 'over a <y>billion.</y>' },
  { t:  73.86, h: 'who knows what' },
  { t:  74.48, h: 'will happen if' },
  { t:  75.24, h: 'it sticks around' },
  { t:  75.80, h: 'through the cycle' },
  { t:  76.64, h: 'top?' },
  { t:  77.08, h: 'multiple <y>billions,</y> right?' },
  { t:  78.32, h: 'it could be' },
  { t:  78.76, h: 'like almost a' },
  { t:  79.78, h: '<y>thousand</y> x for' },
  { t:  80.40, h: 'me.' },
];
