export const CAPTIONS_MFX: { t: number; h: string }[] = [
  { t:   0.00, h: 'people are talking' },
  { t:   1.48, h: 'a lot of' },
  { t:   2.06, h: 'smack about some' },
  { t:   2.72, h: 'of these coins' },
  { t:   3.72, h: 'that came out like 2024' },
  { t:   5.00, h: '2025 they\'re not' },
  { t:   6.66, h: 'gonna pump <b>toshi</b>' },
  { t:   8.04, h: 'and peanut and' },
  { t:   9.16, h: 'like you name it and' },
  { t:  10.04, h: '<b>pengu</b> and all' },
  { t:  10.78, h: 'this stuff' },
  { t:  14.00, h: 'but yeah, man, i we' },
  { t:  16.26, h: 'did this <y>94x</y> on' },
  { t:  18.68, h: '<o>$tut</o> on bnb just last' },
  { t:  20.50, h: 'september and then' },
  { t:  21.36, h: 'look at where' },
  { t:  22.48, h: 'we\'re officially at' },
  { t:  23.76, h: '<y>130x</y> look at this' },
  { t:  25.54, h: 'thing man.' },
  { t:  26.04, h: 'look at this thing.' },
  { t:  26.54, h: 'freaking <y>94x</y>' },
  { t:  28.24, h: 'holy crap.' },
  { t:  28.76, h: 'like what if you know' },
  { t:  30.08, h: 'what if <b>toshi</b>' },
  { t:  30.96, h: 'is gonna pump?' },
  { t:  32.12, h: 'what if <b>pengu</b>' },
  { t:  32.70, h: 'is gonna pump?' },
  { t:  33.60, h: 'what if all' },
  { t:  33.98, h: 'these others are' },
  { t:  34.58, h: 'gonna pump?' },
  { t:  35.10, h: 'now i know some of' },
  { t:  35.76, h: 'them are <r>dead</r> some of' },
  { t:  36.62, h: 'them died out in the' },
  { t:  37.64, h: 'bear market the' },
  { t:  38.44, h: 'devs are like ah hell' },
  { t:  39.58, h: 'with the hell with this' },
  { t:  40.82, h: 'you know they jump ship' },
  { t:  41.74, h: 'you know, look at here' },
  { t:  42.56, h: 'velvet velvet is' },
  { t:  43.60, h: '<gr>pumping</gr> too, right?' },
  { t:  44.28, h: 'this is my' },
  { t:  44.84, h: '<y>58x-er</y> from just' },
  { t:  46.18, h: 'two months ago' },
  { t:  46.86, h: 'yeah, man.' },
  { t:  47.80, h: 'holy crap.' },
  { t:  48.76, h: 'oh, you can see yeah' },
  { t:  49.52, h: 'this this thing' },
  { t:  50.06, h: 'is flying right now.' },
  { t:  50.94, h: 'the open interest' },
  { t:  51.98, h: 'right now is' },
  { t:  53.44, h: 'really up.' },
  { t:  54.40, h: 'there\'s a lot' },
  { t:  55.06, h: 'of volume.' },
  { t:  55.72, h: 'look at that' },
  { t:  56.30, h: 'crazy, right?' },
  { t:  56.98, h: 'nuts.' },
  { t:  57.66, h: 'and then people' },
  { t:  58.60, h: 'are shorting like' },
  { t:  59.58, h: 'crazy and people' },
  { t:  60.36, h: 'getting <r>liquidated.</r>' },
  { t:  61.30, h: 'it\'s like what if meme' },
  { t:  62.94, h: 'coins from last' },
  { t:  63.78, h: 'year can still' },
  { t:  64.44, h: 'pump because i\'m' },
  { t:  65.26, h: 'noticing like every' },
  { t:  66.46, h: 'single influencer spreading' },
  { t:  68.28, h: '<r>fud</r> about meme' },
  { t:  69.54, h: 'coins and some' },
  { t:  70.58, h: 'alts from just from last' },
  { t:  72.04, h: 'year just from last year' },
  { t:  74.02, h: 'what the hell so' },
  { t:  75.40, h: 'if you\'re spreading <r>fud</r>' },
  { t:  76.16, h: 'about <b>toshi?</b>' },
  { t:  77.12, h: 'what is going' },
  { t:  78.38, h: 'to replace <b>toshi</b>' },
  { t:  79.32, h: 'because i saw' },
  { t:  79.98, h: 'the base that\'s' },
  { t:  80.76, h: 'like <b>toshi</b> is' },
  { t:  81.54, h: 'the face of base.' },
  { t:  82.44, h: 'well, what is who\'s' },
  { t:  84.10, h: 'gonna you know' },
  { t:  84.66, h: 'what meme coin is' },
  { t:  85.32, h: 'gonna replace toshi now?' },
];
