export const CAPTIONS_TGR: { t: number; h: string }[] = [
  { t:   0.54, h: 'i just, i feel' },
  { t:   1.46, h: 'crazy weird about' },
  { t:   2.68, h: 'this, man.' },
  { t:   3.34, h: 'i feel crazy' },
  { t:   4.10, h: 'weird because it\'s' },
  { t:   5.36, h: 'this <b>toncoin.</b>' },
  { t:   6.40, h: 'like i would' },
  { t:   6.84, h: 'have been a' },
  { t:   7.24, h: '<b>toncoin</b> maxi if' },
  { t:   8.30, h: '<g>kaspa</g> had never' },
  { t:   9.10, h: 'existed.' },
  { t:   9.78, h: 'like i would' },
  { t:  10.06, h: 'have been a' },
  { t:  10.36, h: '<b>toncoin</b> maxi, right?' },
  { t:  11.58, h: 'but they changed' },
  { t:  12.14, h: 'their name to' },
  { t:  12.74, h: '<y>gram.</y>' },
  { t:  13.32, h: 'so it was like' },
  { t:  13.72, h: '<o>bittensor</o> right?' },
  { t:  15.26, h: 'that\'s the chain' },
  { t:  16.16, h: 'and then <o>tao</o> is the' },
  { t:  17.22, h: 'token.' },
  { t:  17.68, h: 'so it was like, okay' },
  { t:  18.58, h: '<b>toncoin</b> is the' },
  { t:  19.30, h: 'chain, and <y>gram</y>' },
  { t:  20.80, h: 'is the token.' },
  { t:  21.62, h: 'it\'s not <b>toncoin</b>' },
  { t:  22.36, h: 'is the chain.' },
  { t:  22.82, h: 'so it\'s <b>ton</b> is the' },
  { t:  23.98, h: 'chain.' },
  { t:  24.44, h: 'not <b>toncoin</b> anymore' },
  { t:  25.36, h: 'i think <y>gram</y>' },
  { t:  25.70, h: 'is the token.' },
  { t:  26.28, h: 'the token used' },
  { t:  26.80, h: 'to be <b>toncoin.</b>' },
  { t:  27.60, h: 'it\'s the telegram' },
  { t:  28.46, h: 'blockchain.' },
  { t:  28.98, h: 'so telegram, <y>gram,</y>' },
  { t:  30.74, h: 'so it kind of' },
  { t:  31.16, h: 'makes sense.' },
  { t:  31.76, h: 'i\'m trying to' },
  { t:  32.22, h: 'just like come to' },
  { t:  33.00, h: 'terms with that' },
  { t:  33.88, h: 'but i just feel so' },
  { t:  34.82, h: 'weird.' },
  { t:  35.12, h: 'either way, i' },
  { t:  35.80, h: 'think this is' },
  { t:  36.40, h: '<b>toncoin</b> is going' },
  { t:  37.28, h: 'to be another' },
  { t:  37.84, h: 'phenomenal play.' },
  { t:  38.84, h: 'i\'m looking forward' },
  { t:  39.52, h: 'to like a <y>$20</y>' },
  { t:  41.26, h: '<b>toncoin.</b>' },
  { t:  42.28, h: 'maybe it won\'t' },
  { t:  42.88, h: 'go that high, but i\'m' },
  { t:  43.82, h: 'looking forward to' },
  { t:  44.84, h: 'it.' },
  { t:  45.04, h: 'i\'m like, yeah, it has' },
  { t:  45.92, h: 'to go that high.' },
];
