export const CAPTIONS_WOD: { t: number; h: string }[] = [
  { t:   0.00, h: 'yeah, i still' },
  { t:   0.60, h: 'think that what' },
  { t:   1.32, h: 'if is like, so they' },
  { t:   2.62, h: 'people make the' },
  { t:   3.08, h: 'comparison to <o>pepe.</o>' },
  { t:   4.26, h: 'i\'m talking about' },
  { t:   4.68, h: 'what if.' },
  { t:   5.20, h: 'but with <o>pepe,</o> was like' },
  { t:   6.72, h: 'a totally an' },
  { t:   7.38, h: '<r>insider</r> coin, right?' },
  { t:   8.44, h: 'because within the' },
  { t:   9.44, h: 'same week, you see this' },
  { t:  10.64, h: 'candle right here.' },
  { t:  11.36, h: 'this is week two' },
  { t:  12.24, h: 'right?' },
  { t:  12.46, h: 'the high is <y>169m.</y>' },
  { t:  14.10, h: 'and then right' },
  { t:  14.38, h: 'after that, the' },
  { t:  15.24, h: 'high is <y>353m.</y>' },
  { t:  16.70, h: 'and then over here, the' },
  { t:  17.62, h: 'high is <y>1.8b.</y>' },
  { t:  18.88, h: 'because within in' },
  { t:  19.80, h: 'their first week' },
  { t:  20.80, h: 'they\'re getting listed' },
  { t:  21.42, h: 'on like tier ones.' },
  { t:  22.36, h: 'they got listed' },
  { t:  23.04, h: 'on the <o>htx.</o>' },
  { t:  24.18, h: 'and then like the next' },
  { t:  24.84, h: 'day it was <o>gate</o> and' },
  { t:  25.96, h: 'then <o>mexc.</o>' },
  { t:  26.52, h: 'it was like they just' },
  { t:  27.36, h: 'out of the blue.' },
  { t:  27.88, h: 'so they launched' },
  { t:  28.44, h: 'and then suddenly' },
  { t:  29.18, h: 'they\'re going to' },
  { t:  29.66, h: 'listen to all' },
  { t:  30.04, h: 'these <r>centralized</r> <r>exchanges.</r>' },
  { t:  31.28, h: 'so that doesn\'t' },
  { t:  32.12, h: 'you can\'t compare' },
  { t:  32.80, h: 'that to what if what' },
  { t:  33.86, h: 'if it just <gr>grew</gr>' },
  { t:  34.48, h: '<gr>organically</gr> to like' },
  { t:  35.64, h: 'near where near' },
  { t:  36.42, h: '<y>40</y> million without' },
  { t:  37.50, h: 'any <r>centralized</r> <r>exchanges</r>' },
  { t:  38.74, h: 'in a bear' },
  { t:  39.32, h: 'market nonetheless.' },
  { t:  40.30, h: '<b>cashcat</b> got listed' },
  { t:  41.46, h: 'on a whole' },
  { t:  41.86, h: 'bunch of <r>centralized</r>' },
  { t:  42.56, h: '<r>exchanges.</r>' },
  { t:  43.14, h: 'so they didn\'t' },
  { t:  43.98, h: 'pump.' },
  { t:  44.42, h: 'they didn\'t pump' },
  { t:  44.96, h: '<gr>organically</gr> the same' },
  { t:  46.06, h: 'way.' },
  { t:  46.32, h: 'what if that i made' },
  { t:  47.50, h: 'that comparison to' },
  { t:  48.48, h: 'more so like' },
  { t:  49.04, h: '<b>dogecoin.</b>' },
  { t:  49.48, h: 'it\'s like <b>dogecoin</b>' },
  { t:  50.18, h: 'just <gr>grew</gr> <gr>organically</gr>' },
  { t:  51.22, h: 'just from people' },
  { t:  51.98, h: 'just getting behind' },
  { t:  52.92, h: 'it and <gr>backing</gr>' },
  { t:  53.72, h: 'it.' },
  { t:  53.96, h: 'so like what i\'m' },
  { t:  54.84, h: 'saying is my' },
  { t:  55.44, h: 'point is if' },
  { t:  56.04, h: 'enough people can' },
  { t:  56.64, h: 'get behind what' },
  { t:  57.76, h: 'if to do what it' },
  { t:  59.34, h: 'has done in this' },
  { t:  60.50, h: 'short of a' },
  { t:  60.94, h: 'time period in' },
  { t:  61.70, h: 'a bear market' },
  { t:  62.36, h: 'nonetheless.' },
  { t:  63.08, h: 'that\'s like crazy.' },
  { t:  64.14, h: 'it just shows' },
  { t:  64.74, h: 'you how it' },
  { t:  65.34, h: 'shows you that' },
  { t:  66.00, h: 'has a really' },
  { t:  66.62, h: 'strong <gr>community.</gr>' },
  { t:  67.60, h: 'we need this' },
  { t:  68.26, h: 'thing to flip' },
  { t:  69.10, h: '<b>cashcat</b> in order' },
  { t:  70.24, h: 'to be, you know, i' },
  { t:  71.14, h: 'guess to be' },
  { t:  71.62, h: 'taken seriously by' },
  { t:  72.62, h: '<gr>vlad</gr> <gr>robinhood.</gr>' },
  { t:  74.04, h: 'obviously right now' },
  { t:  74.80, h: 'it\'s reached a' },
  { t:  75.94, h: 'point where, yeah' },
  { t:  76.94, h: 'it has to be' },
  { t:  77.74, h: 'taken seriously.' },
  { t:  78.46, h: 'but there could' },
  { t:  79.04, h: 'be no doubt' },
  { t:  79.68, h: 'in anybody\'s mind' },
  { t:  80.72, h: 'if this thing' },
  { t:  81.26, h: 'is trading above' },
  { t:  82.26, h: 'a market cap' },
  { t:  82.96, h: 'of <b>cashcat.</b>' },
  { t:  83.76, h: 'and yeah, it' },
  { t:  84.48, h: 'totally has to' },
  { t:  85.12, h: 'be taken seriously.' },
];
