// Captions for October-pumps clip #4 "rally-basket-ninehood-cashcat" (variant: full).
// COPIED VERBATIM from the clip folder's captions.ts, which is the output of the CANONICAL
// captions skill (video-creation/skills/captions/build_captions.py --style montserrat).
// Never hand-authored, never lifted from another composition.
// STT-ONLY corrections applied (grouping / timings / lowercase / colour spans untouched, and
// mirrored back into the clip's captions.ts so both copies stay byte-identical). Both are
// required by the cutter's note in shorts/October-pumps/progress.json:
//   32.76  'team has been boom on' -> 'team has been bomo on'  (Whisper hears the coin BOMO as "boom")
//   49.20  'cap yeah it's'         -> 'cat yeah it's'          (Whisper hears Cash Cat as "cash cap")
export const CAPTIONS_RALLY_BASKET: { t: number; h: string }[] = [
  { t:   0.00, h: 'just throw something' },
  { t:   0.96, h: 'into some of' },
  { t:   1.56, h: 'these because if' },
  { t:   2.08, h: 'they start running' },
  { t:   2.76, h: 'good rat is a' },
  { t:   3.36, h: 'pretty good play' },
  { t:   4.00, h: 'they got good' },
  { t:   4.58, h: 'content it\'s a' },
  { t:   5.40, h: 'math' },
  { t:   6.06, h: 'theory play it\'s' },
  { t:   6.92, h: 'down to one' },
  { t:   7.42, h: 'million right now' },
  { t:   8.10, h: 'just hit a' },
  { t:   8.52, h: 'million so it\'s' },
  { t:   9.04, h: 'probably going to' },
  { t:   9.52, h: 'go under a' },
  { t:  10.02, h: 'million like any' },
  { t:  11.04, h: 'minute right so' },
  { t:  11.90, h: 'some of these' },
  { t:  12.28, h: 'things could run' },
  { t:  13.16, h: 'ninehood is one' },
  { t:  14.36, h: 'of the ones i like' },
  { t:  15.44, h: 'it\'s bouncing around' },
  { t:  16.36, h: 'in this range' },
  { t:  17.08, h: 'between' },
  { t:  18.02, h: '<y>240</y> to <y>360</y>' },
  { t:  19.30, h: 'right i think' },
  { t:  20.22, h: 'it\'s pretty good' },
  { t:  20.90, h: 'what if you know we' },
  { t:  21.98, h: 'get a new a new' },
  { t:  22.76, h: 'bottom like i' },
  { t:  23.34, h: 'said and things' },
  { t:  23.86, h: 'start running in' },
  { t:  24.56, h: 'a few months' },
  { t:  25.12, h: 'and then what does this' },
  { t:  26.30, h: 'do is this just' },
  { t:  27.14, h: 'going to stay' },
  { t:  27.70, h: 'under' },
  { t:  28.60, h: 'a million market' },
  { t:  30.02, h: 'cap no it\'s' },
  { t:  30.74, h: 'probably going to' },
  { t:  31.28, h: 'go to <y>20</y>' },
  { t:  31.94, h: 'million right same' },
  { t:  32.76, h: 'team has been bomo on' },
  { t:  33.80, h: 'base and which' },
  { t:  34.96, h: 'ran 10 million' },
  { t:  35.82, h: 'so let\'s get a' },
  { t:  37.42, h: 'rally the good' },
  { t:  38.28, h: 'things happen in' },
  { t:  39.08, h: 'a rally in' },
  { t:  39.72, h: 'my community we' },
  { t:  40.44, h: 'do some hundred' },
  { t:  41.04, h: 'x\'s in a' },
  { t:  41.62, h: 'rally or more' },
  { t:  42.46, h: 'right even do' },
  { t:  43.20, h: 'a <y>350x</y> in a bear' },
  { t:  44.78, h: 'market with lab' },
  { t:  46.18, h: 'just a couple' },
  { t:  46.90, h: 'months ago crazy' },
  { t:  47.76, h: 'right definitely cash' },
  { t:  49.20, h: 'cat yeah it\'s' },
  { t:  50.06, h: 'really consolidated right' },
  { t:  51.70, h: 'here in this' },
  { t:  52.20, h: 'range i think' },
  { t:  52.82, h: 'it\'s just waiting' },
  { t:  53.52, h: 'for a rally' },
  { t:  54.18, h: 'just like all the' },
  { t:  54.90, h: 'others right' },
  { t:  55.92, h: 'now when it' },
  { t:  56.44, h: 'comes to robinhood' },
  { t:  57.48, h: 'yeah i think' },
  { t:  58.46, h: 'if they are' },
  { t:  59.12, h: 'going to list' },
  { t:  59.64, h: 'any memes in' },
  { t:  61.36, h: 'their robinhood app' },
  { t:  62.32, h: 'this is probably' },
  { t:  63.10, h: 'going to be' },
  { t:  63.48, h: 'the primary candidate' },
];
