// captionsK89.ts - captions for "89% Said Kaspa Over the Dollar" (batch whatif, clip #2)
// Built with the canonical captions skill (montserrat preset) from the desilenced spine's Whisper
// words, then hand-corrected per the clip's STT fixes:
//   Casper -> Kaspa (auto), Tau -> TAO (auto), "bleeds hotter" -> "bleeds harder",
//   split "2 .7 cents" -> "2.7 cents", awkward "i kaspa is pegged" -> "kaspa pegged",
//   "stablecoin" -> "stablecoins". No em dashes.
// <g> = Kaspa teal, <y> = yellow numbers/percent, <r> = red danger.
export const CAPTIONS_K89: { t: number; h: string }[] = [
  { t:   0.00, h: 'but somebody on' },
  { t:   1.10, h: 'like, my youtube' },
  { t:   1.98, h: 'post, right, i' },
  { t:   3.26, h: 'was talking about' },
  { t:   4.04, h: 'how everybody\'s talking' },
  { t:   5.24, h: 'about <g>kaspa.</g>' },
  { t:   6.16, h: 'and then somebody' },
  { t:   6.80, h: 'had a snarky' },
  { t:   8.26, h: 'comment saying, what' },
  { t:   9.18, h: 'are you talking' },
  { t:   9.68, h: 'about?' },
  { t:  10.12, h: 'you\'re the only' },
  { t:  10.68, h: 'one talking about' },
  { t:  11.50, h: '<g>kaspa.</g>' },
  { t:  12.14, h: 'so if you take a' },
  { t:  13.06, h: 'look at community' },
  { t:  13.52, h: 'sentiment, and <g>kaspa</g>' },
  { t:  14.94, h: 'is usually number' },
  { t:  15.84, h: 'one or two, most' },
  { t:  16.86, h: 'bullish sentiment.' },
  { t:  18.30, h: 'so i\'m not the only' },
  { t:  21.38, h: 'one talking about' },
  { t:  22.40, h: '<g>kaspa.</g>' },
  { t:  23.64, h: 'usually bleeds <r>harder</r>' },
  { t:  24.66, h: 'than tao.' },
  { t:  25.56, h: 'this is the' },
  { t:  25.98, h: 'pattern.' },
  { t:  26.22, h: 'so this is like a' },
  { t:  27.10, h: 'week ago, right' },
  { t:  27.86, h: 'when i posted' },
  { t:  28.38, h: 'the tao crack' },
  { t:  29.28, h: '<y>200</y> first, so' },
  { t:  30.54, h: 'tao went below' },
  { t:  31.10, h: '<y>200.</y>' },
  { t:  31.82, h: '<g>kaspa</g> pegged for' },
  { t:  32.48, h: '<y>2.7</y> cents.' },
  { t:  34.14, h: 'it\'s holding at' },
  { t:  34.68, h: '<y>2.8.</y>' },
  { t:  35.34, h: 'but what are you' },
  { t:  35.70, h: 'doing down here?' },
  { t:  36.84, h: 'so stacking every' },
  { t:  38.12, h: 'dip, <y>59%</y> says, yeah' },
  { t:  42.36, h: '<y>26%</y> are waiting' },
  { t:  43.84, h: 'for 2 cents' },
  { t:  44.44, h: 'in this pause.' },
  { t:  45.32, h: 'it might never' },
  { t:  46.00, h: 'happen.' },
  { t:  46.64, h: 'you\'re just waiting' },
  { t:  47.10, h: 'to <r>miss out.</r>' },
  { t:  47.88, h: 'every time america' },
  { t:  48.64, h: 'needs to sell' },
  { t:  49.74, h: 'more debt, it' },
  { t:  50.58, h: 'manufactures new dollar' },
  { t:  51.80, h: 'buyers, gold, oil' },
  { t:  53.74, h: 'now stablecoins.' },
  { t:  54.52, h: 'if you\'re getting' },
  { t:  55.22, h: 'out of the' },
  { t:  55.98, h: '<r>dollar</r> for the' },
  { t:  56.76, h: 'next 10 years' },
  { t:  58.06, h: 'where will your' },
  { t:  58.50, h: 'money go?' },
  { t:  59.48, h: '<y>89%</y> of people' },
  { t:  61.74, h: 'said <g>kaspa.</g>' },
  { t:  63.78, h: 'my goodness, man.' },
  { t:  68.22, h: 'wow.' },
  { t:  69.56, h: 'that\'s the type' },
  { t:  70.32, h: 'of result i' },
  { t:  71.02, h: 'like to see.' },
  { t:  71.68, h: 'that\'s the type' },
  { t:  72.22, h: 'of result i' },
  { t:  72.74, h: 'like to see.' },
];
