export const CAPTIONS: { t: number; h: string }[] = [
  { t:   0.00, h: 'now, this is the' },
  { t:   0.48, h: 'first time i\'ve' },
  { t:   1.16, h: 'found somebody that' },
  { t:   2.20, h: 'actually says' },
  { t:   3.22, h: 'the same things' },
  { t:   3.84, h: 'as me.' },
  { t:   4.36, h: 'although he doesn\'t' },
  { t:   5.02, h: 'use the phrase' },
  { t:   5.92, h: 'four-year cycle zombies.' },
  { t:   7.32, h: 'i don\'t know why, man.' },
  { t:   8.46, h: 'this is my' },
  { t:   8.92, h: 'phrase, right?' },
  { t:   9.70, h: 'do not wait' },
  { t:  10.30, h: 'until october to' },
  { t:  11.28, h: 'buy bitcoin.' },
  { t:  12.46, h: 'please.' },
  { t:  13.08, h: 'yeah.' },
  { t:  13.54, h: 'so the whole' },
  { t:  14.00, h: 'thing is, key' },
  { t:  15.18, h: 'like me, thinks' },
  { t:  16.66, h: 'that the bottom' },
  { t:  18.40, h: 'is being front-run' },
  { t:  19.72, h: 'right?' },
  { t:  20.08, h: 'so key either' },
  { t:  21.20, h: 'thinks that the' },
  { t:  22.00, h: 'bottom is behind' },
  { t:  22.88, h: 'us or is' },
  { t:  23.42, h: 'going to happen' },
  { t:  23.88, h: 'very soon, like in' },
  { t:  25.00, h: 'august.' },
  { t:  25.64, h: 'he leans towards' },
  { t:  26.78, h: 'it being behind' },
  { t:  27.62, h: 'us.' },
  { t:  27.90, h: 'the biggest example' },
  { t:  29.10, h: 'that i give' },
  { t:  29.86, h: 'about front-running' },
  { t:  30.86, h: 'a bottom is the' },
  { t:  31.90, h: 'september is always' },
  { t:  34.08, h: '<r>red</r> in a' },
  { t:  35.56, h: 'post-halving year thesis.' },
  { t:  36.98, h: 'september is always' },
  { t:  37.86, h: '<r>red</r> in the' },
  { t:  38.76, h: 'post-halving year, right?' },
  { t:  40.20, h: 'so that happened' },
  { t:  40.66, h: 'last year in a' },
  { t:  41.48, h: 'post-halving year.' },
  { t:  42.42, h: 'so that <r>red</r>' },
  { t:  43.54, h: 'september was front-run.' },
  { t:  44.94, h: 'because everybody and' },
  { t:  46.26, h: 'their grandma did' },
  { t:  47.16, h: 'not want to be' },
  { t:  47.78, h: 'caught up in' },
  { t:  48.44, h: 'a <r>red</r> september' },
  { t:  49.40, h: 'last year.' },
  { t:  50.40, h: 'so what they did was' },
  { t:  51.42, h: 'they started selling' },
  { t:  52.62, h: 'in august and' },
  { t:  53.76, h: 'they created that' },
  { t:  54.40, h: 'low in august' },
  { t:  55.52, h: 'and then september' },
  { t:  56.58, h: 'turned <gr>green.</gr>' },
  { t:  57.22, h: 'for the first' },
  { t:  57.70, h: 'time.' },
  { t:  58.14, h: 'so because everybody' },
  { t:  58.74, h: 'knew about it' },
  { t:  59.60, h: 'they changed it.' },
  { t:  60.54, h: 'so that\'s really' },
  { t:  61.06, h: 'the concept here' },
  { t:  61.84, h: 'with the bottom' },
  { t:  62.54, h: 'of the bear' },
  { t:  63.24, h: 'market.' },
  { t:  63.68, h: 'it\'s being front-run.' },
  { t:  64.84, h: 'now, what i say that' },
  { t:  67.14, h: 'all these four-year' },
  { t:  68.10, h: 'cycle zombies, they\'re' },
  { t:  69.82, h: 'going to come' },
  { t:  70.22, h: 'back in october' },
  { t:  71.00, h: 'and they\'re going' },
  { t:  71.70, h: 'to start buying' },
  { t:  72.38, h: 'up and they\'re' },
  { t:  72.96, h: 'going to start' },
  { t:  73.36, h: 'pushing those candles' },
  { t:  74.34, h: '<gr>green</gr> like crazy.' },
  { t:  75.66, h: 'they\'re going to' },
  { t:  76.00, h: 'be scared.' },
  { t:  76.54, h: 'they\'re going to' },
  { t:  76.80, h: 'be overwhelmed with' },
  { t:  78.08, h: 'fomo.' },
  { t:  78.60, h: 'to the point' },
  { t:  78.94, h: 'where we\'re going' },
  { t:  79.24, h: 'to probably have' },
  { t:  79.76, h: 'to schedule an' },
  { t:  80.36, h: 'appointment with a' },
  { t:  80.88, h: 'psychiatrist or something.' },
  { t:  81.90, h: 'they\'re going to' },
  { t:  82.20, h: 'be overwhelmed with' },
  { t:  82.96, h: 'fomo.' },
  { t:  83.60, h: 'like, oh my god, it\'s' },
  { t:  84.84, h: 'not bottoming out.' },
  { t:  85.76, h: 'it keeps going' },
  { t:  86.20, h: 'up.' },
  { t:  86.48, h: 'and they\'re going' },
  { t:  86.96, h: 'to buy back in and' },
  { t:  87.92, h: 'push it up even' },
  { t:  88.50, h: 'further.' },
  { t:  88.98, h: 'it keeps going' },
  { t:  89.88, h: 'up.' },
  { t:  90.30, h: 'i\'m going to' },
  { t:  90.56, h: 'buy back in.' },
  { t:  91.36, h: 'so that\'s my' },
  { t:  92.82, h: 'whole idea of' },
  { t:  93.56, h: 'what\'s going to' },
  { t:  93.96, h: 'happen in october.' },
];
