import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');

export const D_TIGR_1: ShortData = {
  clip: A("tigr-kaspa.mp4"), fps: FPS, durationS: 30.60, capY: 560,
  thumb: { title: "BITCOIN PROVED IT\nKASPA IMPROVED IT", chip: "ENERGY MONEY", chipColor: "#00e5ff", titleSize: 92 },
  captions: [
    { t:   0.06, h: "so elon musk" },
    { t:   1.00, h: "last year said" },
    { t:   1.70, h: "<o>bitcoin</o> is based" },
    { t:   2.60, h: "on <y>energy</y>" },
    { t:   3.40, h: "it is impossible" },
    { t:   4.00, h: "to fake <y>energy</y>" },
    { t:   4.80, h: "today he said" },
    { t:   5.70, h: "i don't think" },
    { t:   5.90, h: "dollars will be" },
    { t:   6.80, h: "used as currency" },
    { t:   7.90, h: "it's mass" },
    { t:   8.30, h: "and <y>energy</y>" },
    { t:   9.20, h: "just interesting, right?" },
    { t:  10.20, h: "very interesting" },
    { t:  10.90, h: "is <o>bitcoin</o> the" },
    { t:  11.50, h: "closest thing we" },
    { t:  12.20, h: "ever had to" },
    { t:  12.80, h: "<y>energy backed</y> money" },
    { t:  14.30, h: "i mean, it is" },
    { t:  15.30, h: "but it's not" },
    { t:  15.60, h: "as efficient as" },
    { t:  16.30, h: "<g>kaspa</g>, right?" },
    { t:  17.00, h: "that's the first" },
    { t:  17.40, h: "thing comes to mind" },
    { t:  18.50, h: "it's not as" },
    { t:  19.60, h: "efficient as <g>kaspa</g>" },
    { t:  21.10, h: "why don't we" },
    { t:  21.60, h: "adopt a phrase" },
    { t:  22.90, h: "he says" },
    { t:  23.30, h: "<o>bitcoin</o> proved it" },
    { t:  24.50, h: "<g>kaspa</g> improved it" },
    { t:  25.80, h: "i just love that" },
    { t:  27.60, h: "<o>bitcoin</o> proved it" },
    { t:  29.00, h: "<g>kaspa</g> improved it" },
    { t:  30.10, h: "perfect" },
  ],
  broll: [
    { src: A("broll-fa0d5dcf-tigr-energy.png"), tIn: 2.5, tOut: 9.0, mode: "full" },
    { src: A("broll-8ad56051-tigr-efficient.png"), tIn: 15.5, tOut: 20.6, mode: "full" },
    { src: A("broll-7d319304-tigr-podium.png"), tIn: 23.0, tOut: 30.6, mode: "full" },
  ],
  sounds: [{ t: 2.5, src: WHOOSH }, { t: 23.0, src: WHOOSH }, { t: 27.6, src: BOOM }],
};

export const D_TIGR_2: ShortData = {
  clip: A("tigr-bear.mp4"), fps: FPS, durationS: 77.07, capY: 560,
  thumb: { title: "THE BEAR WAS A\nSELF-FULFILLING\nPROPHECY", chip: "WHO CAUSED IT", chipColor: "#ff5252", titleSize: 82 },
  captions: [
    { t:   0.06, h: "<o>bitcoin</o> whales" },
    { t:   0.90, h: "stopped <r>selling</r>" },
    { t:   2.50, h: "resumed accumulation" },
    { t:   3.40, h: "remember this problem" },
    { t:   4.50, h: "we had going" },
    { t:   5.70, h: "back like <y>december</y>" },
    { t:   6.60, h: "<y>january, february</y>" },
    { t:   7.50, h: "<y>march</y>?" },
    { t:   8.10, h: "everybody, long-term" },
    { t:   9.30, h: "holders" },
    { t:  10.20, h: "were just <r>selling</r>" },
    { t:  11.40, h: "into the <r>dips</r>" },
    { t:  13.00, h: "which typically" },
    { t:  13.80, h: "every year in crypto" },
    { t:  15.10, h: "every <r>bear</r> market" },
    { t:  15.90, h: "every <gr>bull</gr> market" },
    { t:  17.40, h: "long-term holders" },
    { t:  18.30, h: "always <r>selling</r>" },
    { t:  19.10, h: "at the <gr>pumps</gr>" },
    { t:  19.90, h: "accumulating at" },
    { t:  21.00, h: "the <r>dumps</r>" },
    { t:  21.70, h: "in this case" },
    { t:  22.50, h: "the market was" },
    { t:  23.60, h: "<r>dumping</r>" },
    { t:  24.10, h: "they were <r>selling</r>" },
    { t:  25.20, h: "it was like" },
    { t:  25.70, h: "they were causing" },
    { t:  27.00, h: "the <r>dumps</r>" },
    { t:  27.30, h: "causing the" },
    { t:  28.00, h: "<r>bear</r> market" },
    { t:  28.50, h: "you know what" },
    { t:  28.80, h: "i'm gonna say?" },
    { t:  29.30, h: "four-year cycle" },
    { t:  30.20, h: "in this particular" },
    { t:  31.10, h: "instance" },
    { t:  31.80, h: "the <r>bear</r> market" },
    { t:  32.40, h: "is a" },
    { t:  33.10, h: "self-fulfilling" },
    { t:  33.70, h: "prophecy" },
    { t:  34.20, h: "because everybody" },
    { t:  34.70, h: "believed there's" },
    { t:  35.40, h: "gonna be a" },
    { t:  35.80, h: "<r>bear</r> market" },
    { t:  36.30, h: "so they <r>dumped</r>" },
    { t:  37.10, h: "and they caused" },
    { t:  37.50, h: "a <r>bear</r> market" },
    { t:  38.10, h: "and previous" },
    { t:  39.10, h: "<r>bear</r> markets" },
    { t:  39.90, h: "weren't like that" },
    { t:  41.10, h: "<r>bear</r> market happened" },
    { t:  42.10, h: "for other reasons" },
    { t:  43.20, h: "business cycle" },
    { t:  44.10, h: "went into contraction" },
    { t:  45.30, h: "like last" },
    { t:  45.70, h: "<r>bear</r> market" },
    { t:  46.50, h: "there was super" },
    { t:  47.00, h: "high <r>inflation</r>" },
    { t:  48.50, h: "it was tightening" },
    { t:  50.40, h: "at this time" },
    { t:  51.20, h: "there was nothing" },
    { t:  51.60, h: "like that" },
    { t:  52.20, h: "interest rates are" },
    { t:  52.90, h: "coming <gr>down</gr>" },
    { t:  53.90, h: "<gr>qe</gr> was starting" },
    { t:  55.40, h: "then employment" },
    { t:  55.80, h: "starts going <gr>up</gr>" },
    { t:  56.90, h: "and getting better" },
    { t:  58.20, h: "and at the" },
    { t:  59.60, h: "same time" },
    { t:  60.10, h: "everybody's like" },
    { t:  60.70, h: "there's gonna be" },
    { t:  61.30, h: "a <r>bear</r> market" },
    { t:  62.10, h: "let me <r>dump</r> now" },
    { t:  62.80, h: "so i can" },
    { t:  63.40, h: "get out before" },
    { t:  63.90, h: "it goes <r>down</r>" },
    { t:  64.40, h: "even lower" },
    { t:  65.20, h: "and it just" },
    { t:  65.60, h: "went <r>down</r> even lower" },
    { t:  66.50, h: "there was no" },
    { t:  66.80, h: "reason for the" },
    { t:  67.50, h: "<r>bear</r> market" },
    { t:  68.10, h: "but the good news" },
    { t:  69.40, h: "is, now this" },
    { t:  70.40, h: "has reversed" },
    { t:  71.30, h: "and rightfully so" },
    { t:  72.40, h: "the whales have" },
    { t:  73.00, h: "started to" },
    { t:  73.50, h: "<gr>accumulate</gr>" },
    { t:  73.80, h: "all over again" },
    { t:  74.60, h: "so that's good" },
    { t:  75.40, h: "that's <gr>bullish</gr>" },
    { t:  76.20, h: "that's <gr>bullish</gr> news" },
  ],
  broll: [
    { src: A("broll-420ba284-tigr-whales-stop.png"), tIn: 2.0, tOut: 11.0, mode: "full" },
    { src: A("broll-3540633d-tigr-sell-pumps.png"), tIn: 14.0, tOut: 21.5, mode: "full" },
    { src: A("broll-bd8c6ac3-tigr-cause-dump.png"), tIn: 21.5, tOut: 28.5, mode: "full" },
    { src: A("broll-f4ef69ec-tigr-prophecy.png"), tIn: 31.5, tOut: 38.0, mode: "full" },
    { src: A("broll-3c7e0377-tigr-old-bear.png"), tIn: 38.0, tOut: 45.0, mode: "full" },
    { src: A("broll-e53fdae0-tigr-macro-good.png"), tIn: 48.0, tOut: 58.0, mode: "full" },
    { src: A("broll-b84a3396-tigr-panic-dump.png"), tIn: 58.0, tOut: 67.5, mode: "full" },
    { src: A("broll-86d4c454-tigr-reversed-bull.png"), tIn: 70.0, tOut: 77.07, mode: "full" },
  ],
  sounds: [{ t: 2.0, src: WHOOSH }, { t: 31.5, src: WHOOSH }, { t: 58.0, src: WHOOSH }, { t: 70.0, src: BOOM }],
};

export const D_TIGR_3: ShortData = {
  clip: A("tigr-tao.mp4"), fps: FPS, durationS: 17.11, capY: 560,
  thumb: { title: "THE AI WITH NO\nOFF SWITCH", chip: "$TAO", chipColor: "#00e5ff", titleSize: 104 },
  captions: [
    { t:   0.06, h: "<g>tao</g> is ripping" },
    { t:   0.60, h: "last weekend" },
    { t:   1.20, h: "it's going to" },
    { t:   1.70, h: "be a powerhouse" },
    { t:   3.30, h: "people are looking" },
    { t:   4.00, h: "for decentralized" },
    { t:   4.80, h: "<g>ai</g>" },
    { t:   6.10, h: "because of this" },
    { t:   7.00, h: "situation with the" },
    { t:   7.80, h: "government <r>ban</r>" },
    { t:   8.90, h: "of that mythos" },
    { t:   9.70, h: "model called <y>fable</y>" },
    { t:  10.80, h: "with anthropic" },
    { t:  11.80, h: "on friday" },
    { t:  12.70, h: "so <g>bittensor</g>" },
    { t:  13.60, h: "<g>tao</g> is probably" },
    { t:  14.30, h: "going to be a" },
    { t:  15.00, h: "powerhouse" },
    { t:  15.80, h: "during this <gr>bull</gr> run" },
  ],
  broll: [
    { src: A("broll-b5c67163-tigr-tao-switchoff.png"), tIn: 1.5, tOut: 8.0, mode: "full" },
    { src: A("broll-8d434d09-tigr-tao-network.png"), tIn: 9.5, tOut: 17.11, mode: "full" },
  ],
  sounds: [{ t: 1.5, src: WHOOSH }, { t: 9.5, src: WHOOSH }, { t: 9.5, src: BOOM }],
};

export const FRAMES_TIGR = { c1: 918, c2: 2312, c3: 513 };
