import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');

export const D_MM_1: ShortData = {
  clip: A("projects/market-meltdown/mm-excavator.mp4"), fps: FPS, durationS: 12.88, capY: 560,
  thumb: { title: "I SOLD MY\nEXCAVATOR\nFOR KASPA", chip: "BOUGHT AT 11 CENTS", chipColor: "#00e5ff", titleSize: 92 },
  captions: [
    { t:   0.00, h: "my story i" },
    { t:   0.68, h: "sold my excavator" },
    { t:   1.52, h: "to buy more" },
    { t:   2.00, h: "<g>kaspa</g> bought em" },
    { t:   3.04, h: "at <y>11</y> cents" },
    { t:   4.32, h: "man man i" },
    { t:   5.98, h: "should have waited" },
    { t:   6.56, h: "man i was like" },
    { t:   7.34, h: "soon i'm" },
    { t:   8.00, h: "gonna have enough" },
    { t:   8.66, h: "money to buy" },
    { t:   9.28, h: "like a hundred" },
    { t:   9.92, h: "excavators" },
    { t:  11.58, h: "oh man that's" },
  ],
  broll: [
    { src: A("projects/market-meltdown/broll-0b1a79b8-exc-kaspa-coin.png"), tIn: 1.5, tOut: 6.5, mode: "full" },
  ],
  sounds: [{ t: 1.5, src: WHOOSH }, { t: 1.5, src: BOOM }],
};

export const D_MM_2: ShortData = {
  clip: A("projects/market-meltdown/mm-tao.mp4"), fps: FPS, durationS: 18.54, capY: 560,
  thumb: { title: "TAO AT $10K\nA TOKEN?", chip: "AT THE AI CYCLE TOP", chipColor: "#00e5ff", titleSize: 108 },
  captions: [
    { t:   0.00, h: "if <g>tao</g> is good," },
    { t:   0.78, h: "<g>tao</g> could literally" },
    { t:   1.48, h: "be like a <y>10k</y>" },
    { t:   3.04, h: "per token," },
    { t:   4.28, h: "right?" },
    { t:   4.52, h: "one day at the" },
    { t:   5.46, h: "glorious cycle top" },
    { t:   6.78, h: "whenever that may" },
    { t:   7.42, h: "be an ai" },
    { t:   8.10, h: "driven cycle top," },
    { t:   9.18, h: "right? <g>tao</g> could" },
    { t:   9.72, h: "be like <y>10k.</y> so" },
    { t:  10.72, h: "who cares if" },
    { t:  11.26, h: "you buy it at" },
    { t:  11.90, h: "<y>$207</y> versus you" },
    { t:  13.92, h: "know like <y>160?</y>" },
    { t:  15.36, h: "i mean, it" },
    { t:  15.74, h: "would be nice," },
    { t:  16.34, h: "but it's still" },
    { t:  16.94, h: "in the long run," },
    { t:  17.60, h: "you're" },
    { t:  17.78, h: "gonna make a" },
    { t:  18.12, h: "<g>ton</g> of money." },
  ],
  broll: [
    { src: A("projects/market-meltdown/broll-ce08bf0e-tao-rise.png"), tIn: 1.5, tOut: 7.5, mode: "full" },
    { src: A("projects/market-meltdown/broll-2be15c59-tao-peak-10k.png"), tIn: 11.0, tOut: 17.5, mode: "full" },
  ],
  sounds: [{ t: 1.5, src: WHOOSH }, { t: 11.0, src: WHOOSH }, { t: 11.0, src: BOOM }],
};

export const D_MM_3: ShortData = {
  clip: A("projects/market-meltdown/mm-saylor.mp4"), fps: FPS, durationS: 62.44, capY: 560,
  thumb: { title: "SAYLOR FORCED\nTHE CASCADE", chip: "THEN BOUGHT THE DIP", chipColor: "#f7931a", titleSize: 100 },
  captions: [
    { t:   0.00, h: "so we were in" },
    { t:   0.68, h: "this <y>116</y> day <r>bear</r>" },
    { t:   2.42, h: "flag." },
    { t:   2.96, h: "an ascending" },
    { t:   3.68, h: "channel right here" },
    { t:   4.48, h: "where the expectation" },
    { t:   5.40, h: "is that <y>70</y> %" },
    { t:   6.56, h: "of the time" },
    { t:   7.78, h: "you're going to" },
    { t:   8.08, h: "break out through" },
    { t:   8.60, h: "the downside." },
    { t:   9.30, h: "so what michael" },
    { t:   9.90, h: "sailor did is" },
    { t:  10.72, h: "he sold <y>$2</y> <y>.5</y>" },
    { t:  12.00, h: "million worth of" },
    { t:  13.74, h: "bitcoin, which is" },
    { t:  14.52, h: "like a fraction" },
    { t:  15.30, h: "of a percent" },
    { t:  15.92, h: "of his portfolio." },
    { t:  16.98, h: "right? and" },
    { t:  17.88, h: "what i did is" },
    { t:  18.74, h: "i <r>freaked</r> everybody" },
    { t:  19.62, h: "out and we" },
    { t:  20.70, h: "finally broke out" },
    { t:  21.80, h: "through out of" },
    { t:  23.10, h: "this channel after" },
    { t:  24.06, h: "<y>116</y> days. and" },
    { t:  25.80, h: "because of that" },
    { t:  26.72, h: "everybody took a" },
    { t:  27.70, h: "look at this" },
    { t:  28.06, h: "chart and they're" },
    { t:  28.76, h: "like, oh my god," },
    { t:  29.42, h: "it's going <r>down.</r>" },
    { t:  30.24, h: "so i'm going" },
    { t:  30.68, h: "to <r>sell</r> now and" },
    { t:  31.72, h: "get out. and then" },
    { t:  32.60, h: "those then in" },
    { t:  33.14, h: "the next day you" },
    { t:  33.90, h: "got this big <r>red</r>" },
    { t:  35.52, h: "candle right here" },
    { t:  36.36, h: "going all the" },
    { t:  37.12, h: "way <r>down.</r>" },
    { t:  37.84, h: "yeah, i mean" },
    { t:  38.92, h: "it was just one" },
    { t:  39.60, h: "of those things" },
    { t:  40.10, h: "that he caused" },
    { t:  40.86, h: "this price <r>drop.</r>" },
    { t:  42.12, h: "and then what does" },
    { t:  43.06, h: "he do when" },
    { t:  43.74, h: "we bought him out" },
    { t:  44.36, h: "<r>down</r> here when his" },
    { t:  45.22, h: "bitcoin is like" },
    { t:  45.78, h: "<y>59k</y> again, right?" },
    { t:  47.38, h: "he sold <y>$2</y> <y>.5</y>" },
    { t:  48.70, h: "million worth of" },
    { t:  49.58, h: "bitcoin <gr>up</gr> here." },
    { t:  50.40, h: "and when the" },
    { t:  50.82, h: "price goes <r>down</r>" },
    { t:  51.58, h: "here, he <gr>buys</gr> <y>$110</y>" },
    { t:  53.04, h: "million worth of" },
    { t:  54.70, h: "bitcoin. he is" },
    { t:  55.52, h: "a smart guy." },
    { t:  56.44, h: "he forced the" },
    { t:  57.10, h: "prices <r>down.</r> he" },
    { t:  58.20, h: "forced this <r>cascade</r>" },
    { t:  59.32, h: "event and <gr>bought</gr>" },
    { t:  60.26, h: "back in. it's" },
    { t:  61.32, h: "<gr>brilliant.</gr>" },
    { t:  61.90, h: "it's just <gr>brilliant.</gr>" },
  ],
  broll: [
    { src: A("projects/market-meltdown/broll-3897000e-saylor-channel-break.png"), tIn: 2.0, tOut: 12.0, mode: "full" },
    { src: A("projects/market-meltdown/broll-b0f43e0d-saylor-cascade-down.png"), tIn: 22.0, tOut: 34.0, mode: "full" },
    { src: A("projects/market-meltdown/broll-dc448e52-saylor-buys-bottom.png"), tIn: 46.0, tOut: 58.0, mode: "full" },
  ],
  sounds: [{ t: 2.0, src: WHOOSH }, { t: 22.0, src: WHOOSH }, { t: 22.0, src: BOOM }, { t: 46.0, src: WHOOSH }],
};

export const FRAMES_MM = { c1: 386, c2: 556, c3: 1873 };
