import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');
const LAB_LOGO = { src: A('lab-logo.png'), glow: '#39ff14', watermark: { width: 188, top: 26, left: 26 } };

export const D_ZC_1: ShortData = {
  clip: A('zc-birds-sun-analogy.mp4'), fps: FPS, durationS: 18.70, capY: 560,
  thumb: { title: "THE CYCLE IS A\nMAGIC TRICK", chip: "ZOMBIE CLASS", chipColor: '#00e5ff', titleSize: 120 },
  captions: [
    { t: 0.00, h: "you wake up" },
    { t: 0.98, h: "in the morning" },
    { t: 1.52, h: "and it's still" },
    { t: 2.82, h: "dark." },
    { t: 3.14, h: "it's like <y>5</y>" },
    { t: 3.90, h: "a.m." },
    { t: 4.52, h: "and you hear" },
    { t: 4.78, h: "that you start" },
    { t: 5.26, h: "hearing the birds" },
    { t: 5.88, h: "chirping, but the" },
    { t: 6.88, h: "sun hasn't come" },
    { t: 7.46, h: "out yet, right?" },
    { t: 8.48, h: "but then <y>20</y>" },
    { t: 9.00, h: "minutes later after" },
    { t: 9.74, h: "the birds start" },
    { t: 10.40, h: "chirping, you're like" },
    { t: 11.56, h: "wow, the sun" },
    { t: 12.32, h: "is coming up." },
    { t: 13.16, h: "so that means" },
    { t: 13.60, h: "that the birds" },
    { t: 14.40, h: "must have this" },
    { t: 15.04, h: "magical power." },
    { t: 16.32, h: "they start chirping" },
    { t: 17.14, h: "and they cause" },
    { t: 17.66, h: "the sun to" },
    { t: 18.24, h: "rise." },
  ],
  broll: [
    { src: A("broll-zombie-birds-dawn.png"), tIn: 2.50, tOut: 7.50, mode: 'full' },
    { src: A("broll-zombie-birds-zombiecrowd.png"), tIn: 10.50, tOut: 16.50, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 10.50, src: WHOOSH }, { t: 10.50, src: BOOM }],
};

export const D_ZC_2: ShortData = {
  clip: A('zc-crypto-winter-official.mp4'), fps: FPS, durationS: 30.99, capY: 560,
  thumb: { title: "IT'S OFFICIALLY\nCRYPTO WINTER", chip: "200-WEEK MA", chipColor: '#00e5ff', titleSize: 112 },
  captions: [
    { t: 0.00, h: "we are officially" },
    { t: 0.78, h: "in a crypto" },
    { t: 1.30, h: "winter." },
    { t: 1.92, h: "well, depending on" },
    { t: 3.64, h: "how you define" },
    { t: 4.58, h: "a crypto <r>winter</r>" },
    { t: 5.24, h: "because when bitcoin" },
    { t: 6.52, h: "made its bottom" },
    { t: 8.08, h: "when bitcoin made" },
    { t: 8.76, h: "its bottom, february" },
    { t: 10.46, h: "6th, it went" },
    { t: 12.12, h: "down to on" },
    { t: 13.20, h: "a thursday, it" },
    { t: 14.04, h: "was a single" },
    { t: 14.60, h: "wick, wasn't even" },
    { t: 15.66, h: "weekly close, it" },
    { t: 16.64, h: "went down to" },
    { t: 17.68, h: "<y>59k</y> when the" },
    { t: 19.28, h: "<y>200</y> -week moving" },
    { t: 20.20, h: "average was 50ak." },
    { t: 22.08, h: "so by many" },
    { t: 23.16, h: "definitions, you define" },
    { t: 24.36, h: "a crypto <r>winter</r>" },
    { t: 25.06, h: "by hitting the" },
    { t: 26.46, h: "<y>200</y> -week moving" },
    { t: 27.44, h: "average, which it" },
    { t: 28.14, h: "did not do." },
    { t: 28.68, h: "but we have" },
    { t: 29.22, h: "officially hit on" },
    { t: 30.40, h: "a wick." },
  ],
  broll: [
    { src: A("broll-zombie-winter-wick.png"), tIn: 2.50, tOut: 10.00, mode: 'full' },
    { src: A("broll-zombie-winter-frozen.png"), tIn: 16.00, tOut: 24.00, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 16.00, src: WHOOSH }, { t: 16.00, src: BOOM }],
};

export const D_ZC_3: ShortData = {
  clip: A('zc-saylor-breakdown.mp4'), fps: FPS, durationS: 39.49, capY: 560,
  thumb: { title: "SAYLOR SOLD.\nPANIC FOLLOWED.", chip: "BITCOIN", chipColor: '#ffe600', titleSize: 112 },
  captions: [
    { t: 0.00, h: "michael seller comes" },
    { t: 1.60, h: "out and says" },
    { t: 2.80, h: "i'm gonna buy" },
    { t: 3.54, h: "i'm gonna sell" },
    { t: 4.20, h: "a fraction of" },
    { t: 5.40, h: "a percent of" },
    { t: 6.16, h: "my portfolio." },
    { t: 7.10, h: "this is to" },
    { t: 7.48, h: "pay dividends to" },
    { t: 8.34, h: "my shareholder." },
    { t: 9.12, h: "and then a" },
    { t: 9.50, h: "whole bunch of" },
    { t: 10.02, h: "people who don't" },
    { t: 11.04, h: "believe in charts" },
    { t: 11.76, h: "right, you have" },
    { t: 12.70, h: "the chart people" },
    { t: 13.40, h: "and you have" },
    { t: 13.88, h: "the non -chart" },
    { t: 14.58, h: "people." },
    { t: 15.10, h: "you have a" },
    { t: 15.38, h: "lot of people" },
    { t: 15.82, h: "who don't believe" },
    { t: 16.56, h: "in charts." },
    { t: 17.20, h: "see that happening?" },
    { t: 18.08, h: "and i'm like" },
    { t: 18.42, h: "oh my god." },
    { t: 19.88, h: "michael seller just" },
    { t: 21.14, h: "sold holy crap." },
    { t: 23.90, h: "that means things" },
    { t: 24.60, h: "must be really" },
    { t: 25.38, h: "bad." },
    { t: 25.90, h: "i'm gonna get" },
    { t: 26.64, h: "out now." },
    { t: 27.46, h: "i'm gonna get" },
    { t: 28.80, h: "out before it" },
    { t: 29.82, h: "gets worse." },
    { t: 30.68, h: "and guess what" },
    { t: 31.28, h: "happens?" },
    { t: 32.18, h: "guess what happens?" },
    { t: 33.44, h: "they cause the" },
    { t: 35.08, h: "price of bitcoin" },
    { t: 36.02, h: "to break out" },
    { t: 37.20, h: "down below the" },
    { t: 38.94, h: "channel." },
  ],
  broll: [
    { src: A("broll-zombie-saylor-fraction.png"), tIn: 3.00, tOut: 9.50, mode: 'full' },
    { src: A("broll-zombie-saylor-chickens.png"), tIn: 15.00, tOut: 21.00, mode: 'full' },
    { src: A("broll-zombie-saylor-channelbreak.png"), tIn: 29.00, tOut: 36.00, mode: 'full' },
  ],
  sounds: [{ t: 3.00, src: WHOOSH }, { t: 15.00, src: WHOOSH }, { t: 29.00, src: WHOOSH }, { t: 29.00, src: BOOM }],
};

export const D_ZC_4: ShortData = {
  clip: A('zc-not-rocket-science.mp4'), fps: FPS, durationS: 11.78, capY: 560,
  thumb: { title: "THE CYCLE IS\nINTACT? NO.", chip: "ZOMBIE CLASS", chipColor: '#00e5ff', titleSize: 120 },
  captions: [
    { t: 1.50, h: "this is not" },
    { t: 2.34, h: "rocket science folks." },
    { t: 4.22, h: "this is not" },
    { t: 5.06, h: "some magical thing" },
    { t: 6.12, h: "that can't be" },
    { t: 6.74, h: "explained." },
    { t: 7.62, h: "everybody's telling me" },
    { t: 8.64, h: "that for your" },
    { t: 9.30, h: "cycle is intact." },
    { t: 10.76, h: "like no, it's" },
    { t: 11.26, h: "not me." },
  ],
  broll: [
    { src: A("broll-zombie-rocket-brain.png"), tIn: 2.50, tOut: 6.00, mode: 'full' },
    { src: A("broll-zombie-rocket-zombie.png"), tIn: 7.60, tOut: 11.40, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 7.60, src: WHOOSH }, { t: 7.60, src: BOOM }],
};

export const D_ZC_5: ShortData = {
  clip: A('zc-economy-since-1948.mp4'), fps: FPS, durationS: 20.69, capY: 560,
  thumb: { title: "STRONGEST\nSINCE 1948", chip: "MACRO", chipColor: '#39ff14', titleSize: 120 },
  captions: [
    { t: 0.00, h: "and the economy" },
    { t: 0.68, h: "itself, the business" },
    { t: 1.48, h: "cycle has been" },
    { t: 2.36, h: "in its bear" },
    { t: 3.24, h: "market for the" },
    { t: 4.12, h: "first time since" },
    { t: 4.90, h: "1948." },
    { t: 6.20, h: "just treading below" },
    { t: 7.30, h: "this sideways truck" },
    { t: 8.68, h: "with the business" },
    { t: 9.64, h: "cycle, the ismpmi" },
    { t: 11.26, h: "below expansionary territory" },
    { t: 12.62, h: "below <y>50</y>, for" },
    { t: 13.68, h: "four years has" },
    { t: 14.46, h: "never happened before." },
    { t: 15.44, h: "never happened before." },
    { t: 16.40, h: "then suddenly in" },
    { t: 16.96, h: "january, right, we" },
    { t: 18.40, h: "switched from contractionary" },
    { t: 19.64, h: "to expansionary." },
  ],
  broll: [
    { src: A("broll-zombie-econ-1948.png"), tIn: 2.50, tOut: 9.00, mode: 'full' },
    { src: A("broll-zombie-econ-gauge.png"), tIn: 12.50, tOut: 19.50, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 12.50, src: WHOOSH }, { t: 12.50, src: BOOM }],
};

export const D_ZC_6: ShortData = {
  clip: A('zc-bull-run-next-month.mp4'), fps: FPS, durationS: 45.69, capY: 560,
  thumb: { title: "BULL RUN:\nNEXT MONTH?", chip: "MACRO", chipColor: '#39ff14', titleSize: 120 },
  captions: [
    { t: 0.00, h: "if the war" },
    { t: 0.50, h: "ends tomorrow and" },
    { t: 1.58, h: "it's really officially" },
    { t: 2.50, h: "announced as an" },
    { t: 3.24, h: "ending to the" },
    { t: 4.22, h: "war and as" },
    { t: 4.84, h: "agreement on both" },
    { t: 5.98, h: "sides and the" },
    { t: 6.72, h: "straight -of -home" },
    { t: 7.12, h: "moves opens, then" },
    { t: 7.84, h: "it could be" },
    { t: 8.14, h: "like the bull" },
    { t: 8.56, h: "run starts tomorrow." },
    { t: 9.56, h: "because people want" },
    { t: 10.12, h: "to go buy" },
    { t: 10.50, h: "into the news" },
    { t: 11.14, h: "and they're going" },
    { t: 11.74, h: "to send the" },
    { t: 12.08, h: "markets up." },
    { t: 12.88, h: "and by the" },
    { t: 13.40, h: "time the markets" },
    { t: 13.98, h: "want to come" },
    { t: 14.44, h: "into retracement, because" },
    { t: 15.66, h: "of all everybody" },
    { t: 16.26, h: "buying into the" },
    { t: 17.06, h: "news, it's going" },
    { t: 17.60, h: "to want to" },
    { t: 17.92, h: "come back down." },
    { t: 18.66, h: "by the time" },
    { t: 19.12, h: "it wants to" },
    { t: 19.58, h: "come into retracement" },
    { t: 21.04, h: "the economy is" },
    { t: 21.60, h: "going to be" },
    { t: 21.88, h: "flying everywhere." },
    { t: 22.92, h: "it's like this" },
    { t: 23.76, h: "economic data combined" },
    { t: 25.68, h: "with the fact" },
    { t: 26.30, h: "that we're not" },
    { t: 26.72, h: "being restricted by" },
    { t: 27.94, h: "the problem with" },
    { t: 28.48, h: "the straight -of" },
    { t: 28.82, h: "-home moves." },
    { t: 29.60, h: "and things are" },
    { t: 29.86, h: "gradually getting better" },
    { t: 30.96, h: "from that front" },
    { t: 32.10, h: "right?" },
    { t: 32.26, h: "because the price" },
    { t: 33.08, h: "is not going" },
    { t: 33.42, h: "to go suddenly" },
    { t: 34.02, h: "back down overnight." },
    { t: 34.94, h: "it's going to" },
    { t: 35.14, h: "take a few" },
    { t: 35.46, h: "months." },
    { t: 35.94, h: "but by the" },
    { t: 36.52, h: "time the economy" },
    { t: 37.20, h: "wants to come" },
    { t: 37.80, h: "into retracement, from" },
    { t: 39.12, h: "buying into the" },
    { t: 40.76, h: "news, and it's" },
    { t: 41.48, h: "just like the" },
    { t: 41.92, h: "economy is going" },
    { t: 42.42, h: "to be flying." },
    { t: 42.98, h: "it's like we" },
    { t: 43.24, h: "could literally go" },
    { t: 44.18, h: "into a bull" },
    { t: 44.58, h: "run next month." },
  ],
  broll: [
    { src: A("broll-zombie-bull-hormuz.png"), tIn: 4.00, tOut: 13.00, mode: 'full' },
    { src: A("broll-zombie-bull-rocket.png"), tIn: 31.00, tOut: 42.00, mode: 'full' },
  ],
  sounds: [{ t: 4.00, src: WHOOSH }, { t: 31.00, src: WHOOSH }, { t: 31.00, src: BOOM }],
};

export const D_ZC_7: ShortData = {
  clip: A('zc-best-month-353x.mp4'), fps: FPS, durationS: 36.84, capY: 560,
  thumb: { title: "BEST MONTH\nEVER", chip: "353x ON LAB", chipColor: '#39ff14', titleSize: 120 },
  captions: [
    { t: 0.00, h: "remember when we" },
    { t: 0.50, h: "had the best" },
    { t: 1.70, h: "month ever, like" },
    { t: 3.48, h: "look quite literally" },
    { t: 4.14, h: "the best month" },
    { t: 4.68, h: "ever." },
    { t: 5.22, h: "the number of" },
    { t: 6.04, h: "coins that had" },
    { t: 7.68, h: "those multipliers plus" },
    { t: 8.96, h: "the quantity, the" },
    { t: 10.08, h: "<y>550x</y> on nwx." },
    { t: 11.90, h: "so just" },
    { t: 12.78, h: "now, we could" },
    { t: 13.98, h: "go, we had" },
    { t: 14.70, h: "our second biggest" },
    { t: 15.64, h: "play, the <y>353x</y>" },
    { t: 17.88, h: "on lab." },
    { t: 18.58, h: "it was cold" },
    { t: 18.94, h: "in october, it" },
    { t: 19.86, h: "was cold in" },
    { t: 20.30, h: "october, and we" },
    { t: 21.04, h: "finally did a" },
    { t: 21.68, h: "<y>350x</y>, <y>353x</y> on" },
    { t: 24.06, h: "<gr>lab</gr>, but that" },
    { t: 24.64, h: "was just one" },
    { t: 25.24, h: "token, right?" },
    { t: 27.08, h: "in september, it" },
    { t: 27.74, h: "was like a" },
    { t: 28.16, h: "whole bunch of" },
    { t: 29.30, h: "them." },
    { t: 29.48, h: "like every week" },
    { t: 30.34, h: "there are a" },
    { t: 30.74, h: "couple." },
    { t: 31.48, h: "whether it be" },
    { t: 32.06, h: "a <y>10x</y> or" },
    { t: 33.02, h: "<y>47x</y> or <y>100x</y>" },
    { t: 35.22, h: "or whatever." },
    { t: 35.74, h: "so that was" },
    { t: 36.44, h: "september." },
  ],
  broll: [
    { src: A("broll-zombie-best-lab.png"), tIn: 2.50, tOut: 8.50, mode: 'full' },
    { src: A("broll-zombie-best-wall.png"), tIn: 13.50, tOut: 20.50, mode: 'full' },
    { src: A("broll-zombie-best-candles.png"), tIn: 27.00, tOut: 35.00, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 13.50, src: WHOOSH }, { t: 27.00, src: WHOOSH }, { t: 27.00, src: BOOM }],
  logo: LAB_LOGO,
};

export const D_ZC_8: ShortData = {
  clip: A('zc-selling-into-the-crash.mp4'), fps: FPS, durationS: 12.72, capY: 560,
  thumb: { title: "NEVER HAPPENED\nBEFORE", chip: "FIRST EVER", chipColor: '#ff5252', titleSize: 116 },
  captions: [
    { t: 0.00, h: "usually you sell" },
    { t: 0.92, h: "at the pumps" },
    { t: 1.58, h: "where this" },
    { t: 2.52, h: "is the first" },
    { t: 2.98, h: "time in history" },
    { t: 3.64, h: "where masses of" },
    { t: 4.98, h: "people horns and" },
    { t: 5.98, h: "hordes of <r>zombies</r>" },
    { t: 7.30, h: "are selling when" },
    { t: 8.34, h: "the prices go" },
    { t: 9.04, h: "down and there's" },
    { t: 9.88, h: "no pump it" },
    { t: 10.46, h: "was just the" },
    { t: 10.92, h: "opposite of how" },
    { t: 11.90, h: "it's always been" },
  ],
  broll: [
    { src: A("broll-zombie-sell-dump.png"), tIn: 2.50, tOut: 6.80, mode: 'full' },
    { src: A("broll-zombie-sell-whale.png"), tIn: 8.20, tOut: 12.40, mode: 'full' },
  ],
  sounds: [{ t: 2.50, src: WHOOSH }, { t: 8.20, src: WHOOSH }, { t: 8.20, src: BOOM }],
};

export const FRAMES_ZC = { c1: 561, c2: 930, c3: 1185, c4: 353, c5: 621, c6: 1371, c7: 1105, c8: 382 };
