import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');

export const D_WCG_1: ShortData = {
  clip: A("wcg-aijobs.mp4"), fps: FPS, durationS: 78.94, capY: 560,
  thumb: { title: "AI IS COMING FOR\nEVERY JOB", chip: "HERE'S THE HEDGE", chipColor: "#00e5ff", titleSize: 100 },
  captions: [
    { t:   0.00, h: "can you imagine" },
    { t:   0.56, h: "a robot drawing" },
    { t:   1.46, h: "your blood on" },
    { t:   2.22, h: "a hospital?" },
    { t:   3.34, h: "ha ha ha ha." },
    { t:   4.62, h: "oh my god dude." },
    { t:   6.32, h: "uh." },
    { t:   8.46, h: "yeah, but you know" },
    { t:   9.36, h: "the craziest thing." },
    { t:  11.70, h: "like this thing," },
    { t:  12.62, h: "like if you look" },
    { t:  13.52, h: "at it there" },
    { t:  14.06, h: "and these robots," },
    { t:  15.34, h: "like these robots," },
    { t:  16.60, h: "i don't know" },
    { t:  17.00, h: "what you call them," },
    { t:  17.50, h: "surgeon tables." },
    { t:  18.48, h: "they have the arms" },
    { t:  19.00, h: "and all this" },
    { t:  19.44, h: "stuff like that." },
    { t:  20.16, h: "you know, it's not" },
    { t:  20.44, h: "like a humanoid" },
    { t:  21.20, h: "form robot, but" },
    { t:  22.08, h: "it's just, i'm sure" },
    { t:  22.96, h: "they could do" },
    { t:  23.38, h: "a humanoid form" },
    { t:  24.04, h: "robot as well" },
    { t:  24.92, h: "to do surgery." },
    { t:  25.56, h: "but they're saying" },
    { t:  26.38, h: "that that a" },
    { t:  27.12, h: "robot can now" },
    { t:  28.48, h: "do a better" },
    { t:  29.94, h: "job than an" },
    { t:  31.34, h: "experienced surgeon to" },
    { t:  32.76, h: "do surgery. so" },
    { t:  33.58, h: "it's like from the" },
    { t:  34.40, h: "hospital's perspective," },
    { t:  35.68, h: "from a financial" },
    { t:  36.22, h: "perspective," },
    { t:  36.88, h: "right?" },
    { t:  37.36, h: "so um," },
    { t:  38.22, h: "but like why" },
    { t:  38.78, h: "would you want" },
    { t:  39.22, h: "to spend," },
    { t:  39.96, h: "you know, let's" },
    { t:  40.56, h: "say <y>300</y> <y>,000</y> a" },
    { t:  41.82, h: "year on a" },
    { t:  42.30, h: "single employee that's" },
    { t:  44.04, h: "a human there," },
    { t:  44.92, h: "it'll take vacation," },
    { t:  45.96, h: "they'll, you know," },
    { t:  47.00, h: "get sick and then" },
    { t:  47.82, h: "won't be working" },
    { t:  48.52, h: "<y>24</y> seven and" },
    { t:  49.52, h: "things like that." },
    { t:  50.26, h: "when you can just" },
    { t:  50.74, h: "spend like, you" },
    { t:  51.42, h: "know, half the" },
    { t:  52.04, h: "price or a" },
    { t:  53.14, h: "fourth of the" },
    { t:  55.00, h: "price on a" },
    { t:  55.84, h: "robot they can" },
    { t:  56.72, h: "do the same" },
    { t:  57.64, h: "thing, you know," },
    { t:  58.80, h: "with, with better" },
    { t:  59.96, h: "precision." },
    { t:  60.70, h: "so unfortunately, that's" },
    { t:  61.78, h: "the world we'll" },
    { t:  62.20, h: "get into." },
    { t:  62.84, h: "like <r>nobody</r> is" },
    { t:  63.96, h: "<r>safe.</r> i mean, one" },
    { t:  64.52, h: "of the best" },
    { t:  64.80, h: "things you can" },
    { t:  65.30, h: "do is to" },
    { t:  65.96, h: "prepare yourself by" },
    { t:  66.78, h: "getting into <g>crypto</g>" },
    { t:  67.52, h: "because that's going" },
    { t:  68.42, h: "to be the" },
    { t:  68.66, h: "money that's going" },
    { t:  69.16, h: "to be used. it's" },
    { t:  69.84, h: "really a hedge" },
    { t:  70.54, h: "not only against" },
    { t:  71.14, h: "affiliation, it's a" },
    { t:  72.00, h: "hedge against the" },
    { t:  74.12, h: "whole, all these" },
    { t:  75.14, h: "dynamics that are" },
    { t:  75.96, h: "changing against, against" },
    { t:  77.12, h: "all of this is" },
    { t:  77.74, h: "happening against a," },
  ],
  broll: [
    { src: A("broll-wcg-robot-surgeon.png"), tIn: 1.5, tOut: 12.0, mode: "full" },
    { src: A("broll-wcg-robot-delivery.png"), tIn: 30.0, tOut: 38.0, mode: "full" },
    { src: A("broll-wcg-nobody-safe.png"), tIn: 54.0, tOut: 66.0, mode: "full" },
    { src: A("broll-wcg-kaspa-hedge.png"), tIn: 66.0, tOut: 79.0, mode: "full" },
  ],
  sounds: [{ t: 1.5, src: WHOOSH }, { t: 1.5, src: BOOM }, { t: 30.0, src: WHOOSH }, { t: 54.0, src: WHOOSH }, { t: 66.0, src: WHOOSH }],
};

export const D_WCG_2: ShortData = {
  clip: A("wcg-punch.mp4"), fps: FPS, durationS: 10.24, capY: 560,
  thumb: { title: "A ROBOT JUST BEAT\nYOUR SURGEON", chip: "NOBODY IS SAFE", chipColor: "#ff4444", titleSize: 104 },
  captions: [
    { t:   0.00, h: "uh you know can" },
    { t:   1.18, h: "now do a" },
    { t:   2.74, h: "better job than" },
    { t:   3.90, h: "an experienced surgeon" },
    { t:   5.58, h: "to do surgery." },
    { t:   6.60, h: "so unfortunately that's" },
    { t:   7.70, h: "the world we'll" },
    { t:   8.10, h: "get into." },
    { t:   8.78, h: "like <r>nobody</r> is" },
    { t:   9.86, h: "<r>safe.</r>" },
  ],
  broll: [
    { src: A("broll-wcg-punch-surgeon.png"), tIn: 0.5, tOut: 5.5, mode: "full" },
    { src: A("broll-wcg-punch-looming-ai.png"), tIn: 5.5, tOut: 10.2, mode: "full" },
  ],
  sounds: [{ t: 0.5, src: WHOOSH }, { t: 0.5, src: BOOM }, { t: 5.5, src: WHOOSH }],
};

export const FRAMES_WCG = { c1: 2368, c2: 307 };
