import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');

export const D_DIL_1: ShortData = {
  clip: A("dil-jobs.mp4"), fps: FPS, durationS: 22.68, capY: 560,
  thumb: { title: "THE JOBS REPORT\nTHAT BROKE\nBITCOIN", chip: "172K JOBS", chipColor: "#ffe600", titleSize: 100 },
  captions: [
    { t:   0.00, h: "here's the caveat" },
    { t:   1.26, h: "here. it was so" },
    { t:   2.80, h: "goddamn good that" },
    { t:   4.80, h: "the market interpreted" },
    { t:   6.14, h: "as <r>bad.</r>" },
    { t:   7.20, h: "combined with this" },
    { t:   8.08, h: "inflation problem because" },
    { t:   9.36, h: "of the strait" },
    { t:   9.78, h: "of hormuz that" },
    { t:  10.70, h: "this is going" },
    { t:  11.46, h: "to be the" },
    { t:  11.92, h: "excuse to raise" },
    { t:  13.54, h: "interest rates." },
    { t:  14.62, h: "so the market" },
    { t:  15.16, h: "interpreted as <r>bad</r>" },
    { t:  16.12, h: "and then guess" },
    { t:  16.70, h: "what? people started" },
    { t:  17.58, h: "selling off, the" },
    { t:  18.40, h: "stock market went" },
    { t:  19.16, h: "<r>down.</r>" },
    { t:  19.68, h: "the market was" },
    { t:  20.26, h: "due for retracement," },
    { t:  21.20, h: "but i guess" },
    { t:  21.70, h: "this was the" },
    { t:  22.30, h: "excuse." },
  ],
  broll: [
    { src: A("broll-dil-jobs-dump.png"), tIn: 2.5, tOut: 8.5, mode: "full" },
    { src: A("broll-dil-jobs-strong-economy.png"), tIn: 13.0, tOut: 19.0, mode: "full" },
  ],
  sounds: [{ t: 2.5, src: WHOOSH }, { t: 2.5, src: BOOM }, { t: 13.0, src: WHOOSH }],
};

export const D_DIL_2: ShortData = {
  clip: A("dil-cycle.mp4"), fps: FPS, durationS: 29.46, capY: 560,
  thumb: { title: "THE 4-YEAR CYCLE\nIS NOT MAGIC", chip: "MACRO LIQUIDITY", chipColor: "#00e5ff", titleSize: 104 },
  captions: [
    { t:   0.00, h: "people like always" },
    { t:   1.12, h: "commenting on me," },
    { t:   2.32, h: "you know, like the" },
    { t:   2.72, h: "four year cycles" },
    { t:   3.44, h: "on me so i'm" },
    { t:   5.82, h: "like i know what" },
    { t:   6.60, h: "to say just" },
    { t:   7.18, h: "because i no" },
    { t:   8.02, h: "longer believe in" },
    { t:   8.78, h: "a four year" },
    { t:   9.16, h: "cycle doesn't mean" },
    { t:   9.98, h: "i don't believe" },
    { t:  10.68, h: "in a crypto" },
    { t:  11.06, h: "<r>winter</r> like i've" },
    { t:  11.86, h: "been saying that" },
    { t:  12.64, h: "we're gonna have" },
    { t:  13.28, h: "a crypto <r>winter</r>" },
    { t:  14.12, h: "since as far" },
    { t:  14.96, h: "back as last" },
    { t:  15.52, h: "summer in august." },
    { t:  16.54, h: "i mean, i've said" },
    { t:  17.28, h: "in live streams" },
    { t:  17.90, h: "too, but i said" },
    { t:  19.56, h: "that you know that" },
    { t:  20.34, h: "they were gonna" },
    { t:  20.72, h: "get a really" },
    { t:  21.44, h: "really disappointing local" },
    { t:  23.04, h: "top at the end" },
    { t:  23.96, h: "of the year and" },
    { t:  24.74, h: "i didn't call" },
    { t:  25.14, h: "it a cycle" },
    { t:  25.64, h: "top because i" },
    { t:  26.32, h: "no longer no" },
    { t:  26.86, h: "longer believe the" },
    { t:  27.66, h: "cycle top was" },
    { t:  28.38, h: "gonna be in" },
    { t:  28.74, h: "<y>2025</y>" },
  ],
  broll: [
    { src: A("broll-dil-cycle-zombie.png"), tIn: 2.5, tOut: 9.0, mode: "full" },
    { src: A("broll-dil-cycle-winter.png"), tIn: 16.0, tOut: 23.0, mode: "full" },
  ],
  sounds: [{ t: 2.5, src: WHOOSH }, { t: 2.5, src: BOOM }, { t: 16.0, src: WHOOSH }],
};

export const D_DIL_3: ShortData = {
  clip: A("dil-kaspa.mp4"), fps: FPS, durationS: 93.95, capY: 560,
  thumb: { title: "I THOUGHT KASPA\nWOULD HIT $3", chip: "BOY WAS I WRONG", chipColor: "#00e5ff", titleSize: 104 },
  captions: [
    { t:   0.00, h: "the gio <g>kaspa</g>" },
    { t:   0.82, h: "was like the" },
    { t:   1.40, h: "biggest performer of" },
    { t:   2.74, h: "the... i'm good." },
    { t:   3.38, h: "i guess i" },
    { t:   3.62, h: "wasn't... i just" },
    { t:   4.08, h: "wasn't paying attention" },
    { t:   4.72, h: "to it. when i" },
    { t:   5.38, h: "finally started paying" },
    { t:   6.10, h: "attention to it," },
    { t:   6.92, h: "it was like four" },
    { t:   7.44, h: "cents," },
    { t:   8.14, h: "and when i" },
    { t:   8.46, h: "finally started buying" },
    { t:   9.16, h: "into it, i just" },
    { t:   9.96, h: "suddenly jumped in" },
    { t:  10.82, h: "nine that day i" },
    { t:  11.68, h: "remember, then it" },
    { t:  12.34, h: "was like <y>10,</y> <y>11</y>" },
    { t:  13.10, h: "cents," },
    { t:  13.70, h: "and i was like," },
    { t:  14.00, h: "oh, well," },
    { t:  14.86, h: "i just buy into" },
    { t:  15.60, h: "it. because i" },
    { t:  16.08, h: "was like, i'm" },
    { t:  16.46, h: "gonna buy it," },
    { t:  17.10, h: "so it was" },
    { t:  17.44, h: "probably... because it's" },
    { t:  18.12, h: "probably gonna go" },
    { t:  18.84, h: "to like <y>$3,</y>" },
    { t:  19.78, h: "and by the end" },
    { t:  20.66, h: "of <y>2025...</y>" },
    { t:  23.44, h: "oh, man!" },
    { t:  25.72, h: "boy," },
    { t:  26.26, h: "it was i" },
    { t:  26.76, h: "<r>wrong,</r>" },
    { t:  27.46, h: "man." },
    { t:  32.00, h: "i believe it" },
    { t:  33.04, h: "will, right?" },
    { t:  33.92, h: "i think a" },
    { t:  34.28, h: "lot of us were" },
    { t:  35.34, h: "<r>wrong.</r>" },
    { t:  35.94, h: "i guess at" },
    { t:  36.32, h: "least like around" },
    { t:  37.34, h: "quarter two of" },
    { t:  38.06, h: "last year, i" },
    { t:  38.74, h: "started to realize" },
    { t:  39.44, h: "that this is not" },
    { t:  40.20, h: "gonna happen." },
    { t:  41.16, h: "i was like, at" },
    { t:  41.52, h: "least i realized" },
    { t:  42.10, h: "that early. some" },
    { t:  42.74, h: "people they just" },
    { t:  43.38, h: "got completely <r>blindsided</r>" },
    { t:  45.10, h: "at the end of" },
    { t:  45.70, h: "last year. i" },
    { t:  46.38, h: "remember like in" },
    { t:  47.28, h: "november when the" },
    { t:  49.20, h: "government shutdown was" },
    { t:  50.24, h: "sucking liquidity out" },
    { t:  51.46, h: "of the market" },
    { t:  51.96, h: "and drollpal came" },
    { t:  53.34, h: "out in the end" },
    { t:  53.86, h: "of october saying" },
    { t:  55.00, h: "that it's not a" },
    { t:  56.16, h: "foregone conclusion or" },
    { t:  57.24, h: "whatever words he" },
    { t:  57.90, h: "used about the" },
    { t:  58.64, h: "rate cut in" },
    { t:  59.28, h: "december so we" },
    { t:  60.34, h: "imply that the" },
    { t:  61.16, h: "rate cut is not" },
    { t:  61.76, h: "going to happen" },
    { t:  62.16, h: "so he sucked" },
    { t:  62.92, h: "search into the" },
    { t:  63.64, h: "other market." },
    { t:  64.40, h: "i was like, yeah," },
    { t:  65.36, h: "we're going to" },
    { t:  65.70, h: "have a really," },
    { t:  66.16, h: "really <r>bad</r> november." },
    { t:  67.92, h: "and then in" },
    { t:  68.50, h: "november, i'm over" },
    { t:  69.76, h: "this washing the" },
    { t:  71.02, h: "other youtubers," },
    { t:  72.06, h: "other youtube channels" },
    { t:  73.72, h: "they're telling their" },
    { t:  75.22, h: "subscribers that they" },
    { t:  77.10, h: "think they're still" },
    { t:  77.84, h: "time for a" },
    { t:  79.42, h: "parabolic top like" },
    { t:  80.82, h: "just like <y>2017.</y>" },
    { t:  83.36, h: "it's going to" },
    { t:  83.84, h: "start happening like" },
    { t:  84.64, h: "in the end of" },
    { t:  85.16, h: "november and will" },
    { t:  85.90, h: "top out in" },
    { t:  86.46, h: "december. i'm like," },
    { t:  87.44, h: "damn, no, it's not." },
    { t:  89.82, h: "i was like," },
    { t:  90.78, h: "where are they" },
    { t:  91.10, h: "getting this from?" },
    { t:  92.50, h: "it's like, it's" },
    { t:  93.20, h: "magic." },
  ],
  broll: [
    { src: A("broll-dil-kaspa-coin.png"), tIn: 3.0, tOut: 10.0, mode: "full" },
    { src: A("broll-dil-kaspa-november-red.png"), tIn: 58.0, tOut: 67.0, mode: "full" },
    { src: A("broll-dil-kaspa-parabolic-zombies.png"), tIn: 78.0, tOut: 86.0, mode: "full" },
  ],
  sounds: [{ t: 3.0, src: WHOOSH }, { t: 3.0, src: BOOM }, { t: 58.0, src: WHOOSH }, { t: 78.0, src: WHOOSH }],
};

export const FRAMES_DIL = { c1: 680, c2: 884, c3: 2818 };
