import { staticFile } from 'remotion';
import type { ShortData } from './LivestreamShort';

const FPS = 30;
const A = (f: string) => staticFile(f);
const WHOOSH = A('sfx/Cinematic Whoosh 02.wav');
const BOOM = A('sfx/Boom - Big Reveal.wav');

export const D_UH_1: ShortData = {
  clip: A("uhoh-october-green.mp4"), fps: FPS, durationS: 35.74, capY: 560,
  thumb: { title: "WHY OCTOBER\nTURNS GREEN", chip: "THE ZOMBIE TRAP", chipColor: "#00e5ff", titleSize: 112 },
  captions: [
    { t:   0.00, h: "the four -year" },
    { t:   0.70, h: "cycle zombies that" },
    { t:   1.94, h: "they all say that" },
    { t:   3.12, h: "the <r>bottom</r> is" },
    { t:   3.88, h: "going to be" },
    { t:   4.46, h: "in october and" },
    { t:   5.14, h: "therefore the october" },
    { t:   6.50, h: "i believe just" },
    { t:   7.52, h: "because of that" },
    { t:   8.12, h: "october is going" },
    { t:   8.80, h: "to be very" },
    { t:   9.20, h: "<gr>green</gr> because you're" },
    { t:  10.46, h: "gonna get a" },
    { t:  10.78, h: "lot of people" },
    { t:  11.26, h: "that we're thinking" },
    { t:  12.26, h: "the <r>bottom</r> is" },
    { t:  12.90, h: "gonna be in" },
    { t:  13.24, h: "october and some" },
    { t:  14.14, h: "people just small" },
    { t:  15.66, h: "percentages of those" },
    { t:  16.96, h: "people who are" },
    { t:  17.76, h: "gonna buy they're" },
    { t:  18.78, h: "gonna push the" },
    { t:  19.52, h: "october a little" },
    { t:  20.20, h: "bit <gr>green</gr> and" },
    { t:  20.98, h: "then others are" },
    { t:  22.18, h: "gonna see that" },
    { t:  22.80, h: "october is becoming" },
    { t:  24.10, h: "a little bit" },
    { t:  24.60, h: "<gr>green</gr> so they're" },
    { t:  25.42, h: "gonna want to" },
    { t:  25.86, h: "foam away and then" },
    { t:  26.82, h: "get in and then" },
    { t:  27.76, h: "others on top" },
    { t:  28.96, h: "of that are" },
    { t:  29.56, h: "gonna see that" },
    { t:  30.38, h: "october is turning" },
    { t:  31.28, h: "<gr>green</gr> and they're" },
    { t:  32.14, h: "gonna want to" },
    { t:  32.58, h: "get in so i" },
    { t:  33.24, h: "think just because" },
    { t:  34.02, h: "of that october" },
    { t:  34.74, h: "is gonna be" },
    { t:  35.32, h: "a <gr>green</gr>" },
  ],
  broll: [
    { src: A("broll-37832a65-uhoh-oct-zombies.png"), tIn: 3.0, tOut: 10.0, mode: "full" },
    { src: A("broll-9b61dd4f-uhoh-oct-rocket.png"), tIn: 24.0, tOut: 33.0, mode: "full" },
  ],
  sounds: [{ t: 3.0, src: WHOOSH }, { t: 24.0, src: WHOOSH }, { t: 24.0, src: BOOM }],
};

export const D_UH_2: ShortData = {
  clip: A("uhoh-still-here.mp4"), fps: FPS, durationS: 36.11, capY: 560,
  thumb: { title: "STILL HERE IN\nTHE WORST OF\nTIMES?", chip: "YOU'RE AHEAD", chipColor: "#39ff14", titleSize: 100 },
  captions: [
    { t:   0.00, h: "you're in the" },
    { t:   0.60, h: "<r>bear</r> market," },
    { t:   1.40, h: "you're in the" },
    { t:   1.66, h: "<r>worst</r> of times" },
    { t:   2.56, h: "and you're sticking" },
    { t:   3.24, h: "around." },
    { t:   3.98, h: "i mean that" },
    { t:   4.36, h: "shows," },
    { t:   5.04, h: "that shows something." },
    { t:   6.28, h: "you're gonna," },
    { t:   6.70, h: "you're at least" },
    { t:   7.32, h: "gonna be at" },
    { t:   7.86, h: "least a little" },
    { t:   8.42, h: "bit of a step" },
    { t:   9.28, h: "<gr>up</gr> from all the" },
    { t:  10.66, h: "other people have" },
    { t:  11.26, h: "checked out and" },
    { t:  11.96, h: "coming back into" },
    { t:  12.64, h: "in october," },
    { t:  13.60, h: "right?" },
    { t:  13.96, h: "depending on what" },
    { t:  14.42, h: "you do, sometimes" },
    { t:  15.26, h: "there's a little" },
    { t:  15.70, h: "bit of luck as" },
    { t:  16.36, h: "well. but for the" },
    { t:  17.20, h: "most part, even if" },
    { t:  18.30, h: "you don't have" },
    { t:  18.70, h: "that good of luck," },
    { t:  19.60, h: "you're still gonna" },
    { t:  20.26, h: "get something better" },
    { t:  21.10, h: "than the four" },
    { t:  21.90, h: "-year cycle zombies" },
    { t:  22.64, h: "were checked out." },
    { t:  23.46, h: "because if you're" },
    { t:  23.96, h: "in the game and" },
    { t:  24.48, h: "you're sticking through," },
    { t:  25.18, h: "then yeah, you're" },
    { t:  25.84, h: "doing, i would" },
    { t:  26.56, h: "say you're doing" },
    { t:  26.98, h: "pretty good. it's" },
    { t:  27.62, h: "gonna take a" },
    { t:  27.88, h: "while," },
    { t:  28.46, h: "it's gonna be" },
    { t:  28.74, h: "a lot of <r>pain,</r>" },
    { t:  29.30, h: "there's definitely gonna" },
    { t:  30.06, h: "be a lot of" },
    { t:  30.58, h: "<r>pain.</r>" },
    { t:  31.98, h: "don't doubt that." },
    { t:  33.40, h: "and it's gonna" },
    { t:  33.80, h: "take a while," },
    { t:  34.48, h: "but in the long" },
    { t:  34.88, h: "run you're probably" },
    { t:  35.40, h: "gonna be doing" },
    { t:  35.84, h: "good." },
  ],
  broll: [
    { src: A("broll-8cc35382-uhoh-still-storm.png"), tIn: 3.0, tOut: 10.0, mode: "full" },
    { src: A("broll-39210bc4-uhoh-still-sunrise.png"), tIn: 24.0, tOut: 34.0, mode: "full" },
  ],
  sounds: [{ t: 3.0, src: WHOOSH }, { t: 24.0, src: WHOOSH }, { t: 24.0, src: BOOM }],
};

export const D_UH_3: ShortData = {
  clip: A("uhoh-elizaos.mp4"), fps: FPS, durationS: 30.97, capY: 560,
  thumb: { title: "THE AI COIN THAT\nALREADY PROVED IT", chip: "ELIZAOS", chipColor: "#00e5ff", titleSize: 92 },
  captions: [
    { t:   0.00, h: "my favorite ai" },
    { t:   0.84, h: "coin," },
    { t:   1.56, h: "that would be" },
    { t:   1.94, h: "<g>elizaos</g> i would" },
    { t:   4.70, h: "just consider <g>elizaos</g>" },
    { t:   6.08, h: "in the same" },
    { t:   6.56, h: "realm as the" },
    { t:   7.82, h: "tensor and virtuals," },
    { t:   9.98, h: "which were the" },
    { t:  10.58, h: "only two ai" },
    { t:  11.42, h: "coins that were" },
    { t:  12.54, h: "bigger than ai16z" },
    { t:  14.92, h: "which is <g>elizaos</g>" },
    { t:  15.88, h: "back in <y>2024.</y>" },
    { t:  17.42, h: "so it has a" },
    { t:  18.34, h: "lot of safety" },
    { t:  18.92, h: "because of the" },
    { t:  19.68, h: "backing," },
    { t:  20.26, h: "the vcs and" },
    { t:  20.92, h: "their reputation from" },
    { t:  21.84, h: "the past." },
    { t:  22.48, h: "they just migrated" },
    { t:  23.22, h: "the coin." },
    { t:  24.72, h: "it's just now it's" },
    { t:  25.42, h: "<g>elizaos</g> instead of" },
    { t:  26.50, h: "ai16z. so it" },
    { t:  27.88, h: "has a lot more" },
    { t:  28.40, h: "multipliers than virtuals" },
    { t:  30.32, h: "and..." },
  ],
  broll: [
    { src: A("broll-28c989c7-uhoh-elizaos-rise.png"), tIn: 3.0, tOut: 10.0, mode: "full" },
    { src: A("broll-f8065d5a-uhoh-elizaos-podium.png"), tIn: 20.0, tOut: 29.0, mode: "full" },
  ],
  sounds: [{ t: 3.0, src: WHOOSH }, { t: 20.0, src: WHOOSH }, { t: 20.0, src: BOOM }],
};

export const D_UH_4: ShortData = {
  clip: A("uhoh-lab-353x.mp4"), fps: FPS, durationS: 22.09, capY: 560,
  thumb: { title: "WE JUST DID\nA 353X", chip: "ON $LAB", chipColor: "#39ff14", titleSize: 120 },
  captions: [
    { t:   0.00, h: "i have that" },
    { t:   0.46, h: "recent experience with" },
    { t:   1.58, h: "lab, with the lab" },
    { t:   2.52, h: "token." },
    { t:   3.10, h: "for those of" },
    { t:   3.60, h: "you guys who" },
    { t:   4.10, h: "don't know, just" },
    { t:   4.64, h: "a few weeks" },
    { t:   5.20, h: "ago," },
    { t:   5.72, h: "me and my" },
    { t:   6.22, h: "community did a" },
    { t:   6.96, h: "<y>353x.</y> i called" },
    { t:   8.90, h: "this back in" },
    { t:   9.48, h: "october," },
    { t:  10.42, h: "and i thought" },
    { t:  11.44, h: "it was only" },
    { t:  12.02, h: "gonna do like" },
    { t:  12.58, h: "a <y>20x.</y>" },
    { t:  13.60, h: "and we went all" },
    { t:  14.44, h: "the way <gr>up</gr> here." },
    { t:  15.54, h: "so you never" },
    { t:  16.06, h: "know, man." },
    { t:  17.04, h: "you never know." },
    { t:  17.54, h: "it was a nice" },
    { t:  17.92, h: "surprise." },
    { t:  18.52, h: "i only expected" },
    { t:  19.06, h: "a <y>20x,</y> get a" },
    { t:  19.98, h: "<y>350x.</y> so that's" },
    { t:  21.44, h: "a very nice" },
    { t:  21.88, h: "surprise." },
  ],
  broll: [
    { src: A("broll-09512800-uhoh-lab-explode.png"), tIn: 2.5, tOut: 8.0, mode: "full" },
    { src: A("broll-e92079b2-uhoh-lab-candles.png"), tIn: 13.0, tOut: 20.5, mode: "full" },
  ],
  sounds: [{ t: 2.5, src: WHOOSH }, { t: 2.5, src: BOOM }, { t: 13.0, src: WHOOSH }],
};

export const D_UH_5: ShortData = {
  clip: A("uhoh-linea.mp4"), fps: FPS, durationS: 42.31, capY: 560,
  thumb: { title: "SWIFT PICKED\nLINEA, NOT XRP", chip: "THE REAL PLAY", chipColor: "#00e5ff", titleSize: 104 },
  captions: [
    { t:   0.00, h: "i actually like" },
    { t:   0.82, h: "<g>linea</g> because xrp's" },
    { t:   3.16, h: "whole narrative is" },
    { t:   4.66, h: "that they're supposed" },
    { t:   5.54, h: "to replace swift," },
    { t:   7.18, h: "right? but if" },
    { t:   8.06, h: "swift now has" },
    { t:   9.78, h: "a partnership with" },
    { t:  10.62, h: "<g>linea</g> so they" },
    { t:  11.54, h: "have a blockchain," },
    { t:  12.58, h: "it just makes" },
    { t:  13.90, h: "like xrp <r>useless.</r>" },
    { t:  15.32, h: "i think that" },
    { t:  15.84, h: "the pumps that" },
    { t:  16.62, h: "people expect out" },
    { t:  17.78, h: "of xrp are" },
    { t:  18.80, h: "going to happen" },
    { t:  19.34, h: "with <g>linea</g>" },
    { t:  20.64, h: "and it's going" },
    { t:  21.10, h: "to be, there's" },
    { t:  21.40, h: "going to be" },
    { t:  21.54, h: "a lot of" },
    { t:  21.78, h: "multipliers too because" },
    { t:  22.68, h: "you look at the" },
    { t:  23.12, h: "market cap," },
    { t:  24.42, h: "it's <y>37</y> million." },
    { t:  25.40, h: "i think in" },
    { t:  26.24, h: "the long run," },
    { t:  26.96, h: "i think that" },
    { t:  27.98, h: "people are not" },
    { t:  28.58, h: "really realizing it" },
    { t:  29.52, h: "right now. but" },
    { t:  30.16, h: "i think in" },
    { t:  30.62, h: "the long run, this" },
    { t:  31.42, h: "layer two, <g>linea</g>" },
    { t:  32.38, h: "is going to" },
    { t:  32.72, h: "be like a big" },
    { t:  33.98, h: "one." },
    { t:  35.22, h: "oh, like many, many" },
    { t:  36.48, h: "multipliers, many xs." },
    { t:  38.12, h: "if it's a" },
    { t:  38.82, h: "three billion market" },
    { t:  39.60, h: "cap, it'll be" },
    { t:  40.34, h: "<y>100</y> xs. or it" },
    { t:  41.12, h: "could be like" },
    { t:  41.54, h: "way, way beyond" },
    { t:  42.20, h: "that." },
  ],
  broll: [
    { src: A("broll-7b072bbc-uhoh-linea-swift.png"), tIn: 3.0, tOut: 11.0, mode: "full" },
    { src: A("broll-af7ac951-uhoh-linea-vs-xrp.png"), tIn: 28.0, tOut: 40.0, mode: "full" },
  ],
  sounds: [{ t: 3.0, src: WHOOSH }, { t: 28.0, src: WHOOSH }, { t: 28.0, src: BOOM }],
};

export const D_UH_6: ShortData = {
  clip: A("uhoh-kaspa.mp4"), fps: FPS, durationS: 15.80, capY: 560,
  thumb: { title: "KASPA REFUSED\nTO BREAK DOWN", chip: "STRONGEST IN MY BAG", chipColor: "#00e5ff", titleSize: 100 },
  captions: [
    { t:   0.00, h: "<g>kaspa</g> has been" },
    { t:   1.40, h: "really really strong" },
    { t:   2.48, h: "during this last" },
    { t:   3.50, h: "week or so in" },
    { t:   4.28, h: "this time period" },
    { t:   5.26, h: "you'd expect it" },
    { t:   6.06, h: "to go <r>down</r> to" },
    { t:   6.90, h: "like <y>2</y> <y>.7</y>" },
    { t:   7.66, h: "cents and it" },
    { t:   8.52, h: "did not right?" },
    { t:   9.82, h: "it got far it" },
    { t:  10.76, h: "got as far as" },
    { t:  11.40, h: "<y>2</y> <y>.8.</y> i was" },
    { t:  12.80, h: "gonna put in" },
    { t:  13.28, h: "another box. i" },
    { t:  14.02, h: "was i was" },
    { t:  14.56, h: "looking for below" },
    { t:  15.26, h: "<y>2</y> <y>.7</y>" },
  ],
  broll: [
    { src: A("broll-1a0eda6e-uhoh-kaspa-pedestal.png"), tIn: 2.0, tOut: 7.0, mode: "full" },
    { src: A("broll-3776b982-uhoh-kaspa-holds-line.png"), tIn: 9.5, tOut: 14.5, mode: "full" },
  ],
  sounds: [{ t: 2.0, src: WHOOSH }, { t: 2.0, src: BOOM }, { t: 9.5, src: WHOOSH }],
};

export const FRAMES_UH = { c1: 1072, c2: 1083, c3: 929, c4: 663, c5: 1269, c6: 474 };
