// GoldenKittyShortCaptions.ts: GENERATED by the longform graph's short lane (build_captions.py montserrat 2/4 on FINAL-TIME words, COVER-sourced frames only). NEVER hand-edit.
// Times are SHORT seconds (already remapped through the span table).
export const CAPTION_WINDOWS: [number, number][] = [[9.667, 9.685], [9.700, 15.150], [15.133, 22.188], [22.200, 26.550]];
export const ZCAPTIONS: { t: number; h: string }[] = [
  { t:    9.84, h: 'most meme' },
  { t:   10.44, h: 'coins trade' },
  { t:   11.39, h: 'against ethereum' },
  { t:   12.36, h: 'or a' },
  { t:   12.89, h: 'stablecoin.' },
  { t:   13.47, h: 'this one' },
  { t:   14.13, h: 'trades against' },
  { t:   14.81, h: 'gold.' },
  { t:   15.22, h: 'the pool' },
  { t:   15.60, h: 'holds two' },
  { t:   16.36, h: 'things, golden' },
  { t:   17.52, h: 'kitty and' },
  { t:   18.54, h: 'tokenized gold.' },
  { t:   19.44, h: 'when somebody' },
  { t:   19.96, h: 'buys, gold goes into' },
  { t:   21.56, h: 'the pool.' },
  { t:   22.47, h: 'robinhood\\\'s own' },
  { t:   23.13, h: 'trophy on' },
  { t:   24.17, h: 'its own' },
  { t:   24.79, h: 'chain' },
  { t:   25.69, h: 'priced in' },
  { t:   26.25, h: 'gold.' },
];
