// Kaspa 30bps -> 40-second VERTICAL SHORT: captions for the UNCAPTIONED (cover-sourced) spans.
// GENERATED by video-creation/skills/captions/build_captions.py
//   --words <ALL.e.desilenced.medium-words.json shifted to FINAL-VIDEO time> --style montserrat --max-words 2 --max-short 4 --var ZCAPTIONS
// Times are FINAL-VIDEO seconds of spine/ALL.f.paused.mp4 (source time already shifted +1s per baked
// chapter-card pause at 52.81 / 137.0667). The short's comp remaps them into output time itself.
// Windows: 4.70-11.48 (span 1 tail; 0.00-4.70 already has burned-in captions), 330.41-344.79, 427.30-438.11.
// DO NOT HAND-EDIT: re-run the builder (captions-builder agent) instead.
export const ZCAPTIONS: { t: number; h: string }[] = [
  // window 4.70-11.48s  (9 groups)
  { t:   4.74, h: 'this is' },
  { t:   5.22, h: 'where kaspa' },
  { t:   5.88, h: 'is headed' },
  { t:   6.28, h: 'next.' },
  { t:   6.98, h: 'not someday' },
  { t:   7.98, h: 'not in five' },
  { t:   8.82, h: 'years.' },
  { t:   9.54, h: 'the target' },
  { t:  10.10, h: 'is this year.' },
  // window 330.41-344.79s  (17 groups)
  { t: 330.48, h: 'bitcoin' },
  { t: 331.68, h: 'one block' },
  { t: 332.20, h: 'every 10' },
  { t: 332.88, h: 'minutes.' },
  { t: 333.56, h: 'ethereum' },
  { t: 334.60, h: 'every 12' },
  { t: 335.26, h: 'seconds.' },
  { t: 336.20, h: 'kaspa right' },
  { t: 336.86, h: 'now, today' },
  { t: 338.40, h: '10 every' },
  { t: 339.08, h: 'second.' },
  { t: 339.62, h: 'and dagknight' },
  { t: 340.52, h: 'in the' },
  { t: 340.92, h: 'dagknight era' },
  { t: 341.80, h: 'it\'ll be one' },
  { t: 342.60, h: 'block every' },
  { t: 343.32, h: '25 milliseconds.' },
  // window 427.30-438.11s  (12 groups)
  { t: 427.40, h: 'one to 10' },
  { t: 428.70, h: 'done.' },
  { t: 429.76, h: 'programmability, done.' },
  { t: 431.52, h: 'ship this' },
  { t: 432.02, h: 'summer, done.' },
  { t: 433.24, h: 'up to 40' },
  { t: 434.02, h: 'blocks per' },
  { t: 434.60, h: 'second targeted' },
  { t: 435.32, h: 'before the' },
  { t: 435.88, h: 'end of this year.' },
  { t: 436.56, h: 'and then 100 next' },
  { t: 437.78, h: 'year.' },
];
