import React from 'react';
import { AbsoluteFill, Audio, Img, Sequence, interpolate, staticFile, useCurrentFrame } from 'remotion';
import { NLG_CHUNKS, NLG_VO_END, NLG_TAIL, NLG_FPS } from './needLangGraphTimeline';

// need-lang-graph (ai-engineering track) — pure MIKE-CLONE VO over standalone containers.
// One container per chunk, slow zoom, cross-dissolve at each boundary, low corporate music bed.
// Timings come from needLangGraphTimeline.ts (generated by scripts/build-timeline.js off the
// real chunk mp3 durations + 0.35s gaps). Render with
//   --public-dir=../ai-engineering/media/need lang-graph

export const NLG_FPS_EXPORT = NLG_FPS;
export const NLG_DURATION = Math.round((NLG_VO_END + NLG_TAIL) * NLG_FPS);

const XFADE = 10; // frames of cross-dissolve at each visual boundary
const toF = (s: number) => Math.round(s * NLG_FPS);

// Music: reuse the python-ai-libraries corporate bed at the same "very low" mix
// (measured there at ~19 dB under the VO => volume ~= 0.056). Re-measure for final if needed.
const MUSIC_VOL = 0.056;
const MUSIC_SRC = 'render-assets/music-corporate.mp3';

const ZoomStill: React.FC<{ src: string; durF: number; fadeIn: boolean }> = ({ src, durF, fadeIn }) => {
  const f = useCurrentFrame();
  const opacity = fadeIn ? interpolate(f, [0, XFADE], [0, 1], { extrapolateRight: 'clamp' }) : 1;
  const scale = interpolate(f, [0, durF], [1.0, 1.045]);
  return (
    <AbsoluteFill style={{ opacity, background: '#0a0c10' }}>
      <Img src={staticFile(src)} style={{ width: '100%', height: '100%', transform: `scale(${scale})` }} />
    </AbsoluteFill>
  );
};

export const NeedLangGraph: React.FC = () => {
  type Seg = { start: number; end: number; src: string };
  const segs: Seg[] = NLG_CHUNKS.map((c, i) => ({
    start: c.start,
    end: i < NLG_CHUNKS.length - 1 ? NLG_CHUNKS[i + 1].start : NLG_VO_END + NLG_TAIL,
    src: c.visual,
  }));

  const musicVolume = (f: number) =>
    MUSIC_VOL *
    interpolate(f, [0, 30], [0, 1], { extrapolateRight: 'clamp' }) *
    interpolate(f, [NLG_DURATION - 60, NLG_DURATION - 6], [1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill style={{ background: '#0a0c10' }}>
      {segs.map((s, i) => {
        const fromF = Math.max(0, toF(s.start) - (i === 0 ? 0 : XFADE));
        const durF = toF(s.end) - fromF;
        return (
          <Sequence key={i} from={fromF} durationInFrames={durF} name={`v-${i + 1}`}>
            <ZoomStill src={s.src} durF={durF} fadeIn={i !== 0} />
          </Sequence>
        );
      })}

      {NLG_CHUNKS.map((c, i) => (
        <Sequence key={`a-${i}`} from={toF(c.start)} name={`vo-${i + 1}`}>
          <Audio src={staticFile(c.audio)} />
        </Sequence>
      ))}

      <Audio loop src={staticFile(MUSIC_SRC)} volume={musicVolume} />
    </AbsoluteFill>
  );
};
