// AUTO-GENERATED by scripts/build-timeline.js — do not hand-edit.
// all durations measured from real mp3s.
export const ST_FPS = 30;
export const ST_VO_END = 354.678;
export const ST_TAIL = 1.6;
export const ST_DURATION_FRAMES = 10688;
export const ST_CHUNKS: { start: number; audio: string; visual: string }[] = [
  { start: 0, audio: 'audio/chunk-01.mp3', visual: 'render-assets/container-01.png' },
  { start: 13.19, audio: 'audio/chunk-02.mp3', visual: 'render-assets/container-02.png' },
  { start: 26.236, audio: 'audio/chunk-03.mp3', visual: 'render-assets/container-03.png' },
  { start: 43.242, audio: 'audio/chunk-04.mp3', visual: 'render-assets/container-04.png' },
  { start: 60.656, audio: 'audio/chunk-05.mp3', visual: 'render-assets/container-05.png' },
  { start: 73.27, audio: 'audio/chunk-06.mp3', visual: 'render-assets/container-06.png' },
  { start: 85.692, audio: 'audio/chunk-07.mp3', visual: 'render-assets/container-07.png' },
  { start: 100.49, audio: 'audio/chunk-08.mp3', visual: 'render-assets/container-08.png' },
  { start: 115.696, audio: 'audio/chunk-09.mp3', visual: 'render-assets/container-09.png' },
  { start: 131.694, audio: 'audio/chunk-10.mp3', visual: 'render-assets/container-10.png' },
  { start: 142.676, audio: 'audio/chunk-11.mp3', visual: 'render-assets/container-11.png' },
  { start: 157.066, audio: 'audio/chunk-12.mp3', visual: 'render-assets/container-12.png' },
  { start: 169.872, audio: 'audio/chunk-13.mp3', visual: 'render-assets/container-13.png' },
  { start: 185.702, audio: 'audio/chunk-14.mp3', visual: 'render-assets/container-14.png' },
  { start: 200.092, audio: 'audio/chunk-15.mp3', visual: 'render-assets/container-15.png' },
  { start: 220.458, audio: 'audio/chunk-16.mp3', visual: 'render-assets/container-16.png' },
  { start: 239.648, audio: 'audio/chunk-17.mp3', visual: 'render-assets/container-17.png' },
  { start: 253.846, audio: 'audio/chunk-18.mp3', visual: 'render-assets/container-18.png' },
  { start: 281.844, audio: 'audio/chunk-19.mp3', visual: 'render-assets/container-19.png' },
  { start: 304.85, audio: 'audio/chunk-20.mp3', visual: 'render-assets/container-20.png' },
  { start: 323.08, audio: 'audio/chunk-21.mp3', visual: 'render-assets/container-21.png' },
  { start: 336.654, audio: 'audio/chunk-22.mp3', visual: 'render-assets/container-22.png' },
];
