export const CAPTIONS_ETAO: { t: number; h: string }[] = [
  { t:   0.00, h: 'and my concern' },
  { t:   0.82, h: 'is that i, you know' },
  { t:   1.80, h: 'i keep saying' },
  { t:   2.42, h: 'this, like we\'re' },
  { t:   3.14, h: 'trading against ourselves' },
  { t:   4.54, h: 'when it comes' },
  { t:   5.12, h: 'to like these' },
  { t:   6.08, h: 'memes, all of' },
  { t:   7.28, h: 'us that are in' },
  { t:   8.00, h: 'crypto that haven\'t' },
  { t:   8.66, h: 'checked out are' },
  { t:   9.48, h: 'jumping on these' },
  { t:  10.52, h: '<gr>robinhood</gr> memes because' },
  { t:  11.50, h: 'it seems exciting.' },
  { t:  12.68, h: 'and we keep' },
  { t:  14.12, h: 'bouncing.' },
  { t:  14.64, h: 'maybe one is' },
  { t:  15.78, h: '<gr>pumping</gr> and then' },
  { t:  16.36, h: 'the next one we' },
  { t:  17.36, h: 'rotate into, you' },
  { t:  18.64, h: 'know, another meme' },
  { t:  19.56, h: 'and so on.' },
  { t:  20.36, h: 'but it\'s going' },
  { t:  20.90, h: 'to <r>dwindle</r> out' },
  { t:  21.68, h: 'if there\'s no' },
  { t:  22.24, h: 'new retail.' },
  { t:  23.14, h: 'like i can' },
  { t:  24.00, h: 'assure you that' },
  { t:  25.56, h: 'now let\'s go to what' },
  { t:  26.36, h: 'if this pump' },
  { t:  27.32, h: 'right here that' },
  { t:  27.92, h: 'just happened a' },
  { t:  28.54, h: 'couple hours ago.' },
  { t:  29.18, h: 'that\'s from <gr>robinhood</gr>' },
  { t:  30.16, h: 'retail.' },
  { t:  30.48, h: 'but i can tell you' },
  { t:  31.24, h: 'there\'s probably been' },
  { t:  31.92, h: 'a lot of' },
  { t:  32.40, h: 'people who are' },
  { t:  33.08, h: 'buying in like' },
  { t:  33.96, h: 'up here, right?' },
  { t:  34.90, h: 'like up at the top' },
  { t:  35.70, h: 'and you know, they just' },
  { t:  36.92, h: '<r>lost</r> all their' },
  { t:  37.40, h: 'money.' },
  { t:  37.76, h: 'you know, these' },
  { t:  38.22, h: 'guys over here' },
  { t:  39.12, h: 'these guys bought' },
  { t:  40.18, h: 'down here and' },
  { t:  41.32, h: 'they\'re selling up' },
  { t:  42.22, h: 'here.' },
  { t:  42.72, h: 'maybe they\'re going' },
  { t:  43.34, h: 'to rotate into' },
  { t:  44.08, h: 'another <gr>robinhood</gr> token' },
  { t:  45.28, h: 'right?' },
  { t:  45.60, h: 'but the ones over here' },
  { t:  46.44, h: 'were still buying' },
  { t:  47.16, h: 'in and they just, you' },
  { t:  48.30, h: 'know, they just' },
  { t:  49.02, h: 'bought in for' },
  { t:  49.70, h: 'the first time' },
  { t:  50.52, h: 'and they\'re <r>losing</r>' },
  { t:  51.10, h: 'the money.' },
  { t:  51.58, h: 'maybe they got' },
  { t:  52.44, h: 'pissed off and' },
  { t:  53.12, h: 'they just checked' },
  { t:  53.70, h: 'out.' },
  { t:  54.04, h: 'so over time, all the' },
  { t:  55.40, h: 'hype is just' },
  { t:  56.08, h: 'going to phase' },
  { t:  57.00, h: 'away, you know' },
  { t:  57.84, h: 'fiddle away or' },
  { t:  58.40, h: 'whatever you want' },
  { t:  58.70, h: 'to say.' },
  { t:  59.02, h: 'it\'s going to' },
  { t:  59.58, h: 'disappear over the' },
  { t:  60.74, h: 'next few <y>weeks</y>' },
  { t:  61.42, h: 'and they\'re not' },
  { t:  62.18, h: 'going to be' },
  { t:  62.50, h: 'putting any cash' },
  { t:  63.60, h: 'into other <gr>robinhood</gr>' },
  { t:  64.88, h: 'tokens.' },
  { t:  65.40, h: 'so it goes back to' },
  { t:  66.80, h: 'the whole thing.' },
  { t:  67.30, h: 'the whole thing' },
  { t:  67.86, h: 'that we need more' },
  { t:  68.78, h: 'people in crypto.' },
  { t:  70.06, h: 'we have a lot of' },
  { t:  72.68, h: 'outflows of cash' },
  { t:  74.46, h: 'coming out of' },
  { t:  75.64, h: 'stable coins right' },
  { t:  76.58, h: 'now, which happens' },
  { t:  77.28, h: 'every bear market' },
  { t:  78.24, h: 'which happens every' },
  { t:  78.92, h: 'bear market, which' },
  { t:  79.72, h: 'means there\'s more' },
  { t:  80.40, h: 'people checking out' },
  { t:  81.72, h: 'of crypto.' },
  { t:  82.24, h: 'there\'s more people' },
  { t:  82.90, h: 'checking out and' },
  { t:  84.00, h: 'that\'s going to' },
  { t:  84.74, h: 'create a lot' },
  { t:  85.12, h: 'of <r>weakness.</r>' },
  { t:  85.54, h: 'these outflows of' },
  { t:  87.38, h: 'stable coins started' },
  { t:  88.20, h: 'in <y>may.</y>' },
  { t:  89.02, h: 'so it stands' },
  { t:  89.64, h: 'to reason that' },
  { t:  90.44, h: 'it\'s going to' },
  { t:  91.10, h: 'end in <y>december.</y>' },
  { t:  92.14, h: 'and then after' },
  { t:  92.70, h: 'that, the money' },
  { t:  93.44, h: 'is going to' },
  { t:  93.74, h: 'come back in the <gr>bull</gr>' },
  { t:  94.52, h: 'run starts again.' },
];
