export const CAPTIONS_TUT_BKI: { t: number; h: string }[] = [
  { t:   0.00, h: 'there was a' },
  { t:   0.76, h: 'blog article on' },
  { t:   1.56, h: 'the <y>binance</y> website' },
  { t:   2.40, h: 'talking about how' },
  { t:   3.28, h: 'they\'re looking for' },
  { t:   3.96, h: 'community-driven coins.' },
  { t:   5.27, h: '<y>binance</y> gives the' },
  { t:   6.84, h: 'argument about neiro' },
  { t:   7.88, h: 'that it\'s a' },
  { t:   8.28, h: 'community-driven coin, but' },
  { t:   9.50, h: 'it\'s a meme coin.' },
  { t:  10.44, h: 'they don\'t apply' },
  { t:  11.30, h: 'the same logic' },
  { t:  12.12, h: 'to <g>kaspa</g> because' },
  { t:  13.10, h: 'if they did' },
  { t:  14.53, h: '<g>kaspa</g> would be' },
  { t:  15.40, h: 'listed on <y>binance</y>' },
  { t:  16.30, h: 'by now.' },
  { t:  16.90, h: 'so it\'s kind of a' },
  { t:  18.02, h: 'strange <r>catch-22.</r>' },
];
