#!/usr/bin/env python3
"""Build Mother-Satori karaoke caption data for the Kaspa Wise Man fl-07 video.

Clone of prototype-intro/_build_captions_intro.py. The two delivery clips play
AFTER the 6.08s machine-birth hook, so word times are offset by HOOK_OFFSET to
land on the full assembled timeline (Remotion captions run at top level in
absolute time). Transcribe each clip on its own clean audio, group into <=4-word
karaoke beats, write _captions/captions.json AND emit
remotion/src/wiseManFl07Captions.ts (consumed by WiseManFl07.tsx).

Run: python _build_captions_fl07.py   (offline local whisper)
"""
import json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_VIDEO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))   # video-creation/
TS_OUT = os.path.join(REPO_VIDEO, "remotion", "src", "wiseManFl07Captions.ts")
CAP_JSON = os.path.join(HERE, "_captions", "captions.json")

WHISPER = r"C:/Users/mnede/AppData/Local/Programs/Python/Python312/Scripts/whisper.exe"
CLIPS = ["delivery-a-white1x1", "delivery-b-white1x1"]   # 1:1 white-bg cutout clips; talking from frame 0
HOOK_OFFSET = 0.0                      # corner layout: delivery talks from frame 0 (no silent hook)
MAX_WORDS = 4
MAX_GROUP_SECS = 1.8   # wise-man cadence is slower than the promo

# On-screen corrections. The pronunciation respelling (Kaspa->"caspa") is AUDIO-ONLY;
# captions must show the real brand word. Whisper hears the "caspa" audio as KASHPA/CASPA/KASPA.
SUBS = {
    "KASHPA": "KASPA",
    "KASHPA'S": "KASPA'S",
    "CASPA": "KASPA",
    "CASPA'S": "KASPA'S",
    "CASPER": "KASPA",      # legacy fallback
    "CASPER'S": "KASPA'S",
    "CASPIAN": "KASPIAN",
}

def apply_subs(words):
    out = []
    for w in words:
        repl = SUBS.get(w["w"], w["w"])
        parts = repl.split()
        if len(parts) <= 1:
            out.append({"w": repl, "start": w["start"], "end": w["end"]})
        else:
            span = (w["end"] - w["start"]) / len(parts)
            for k, p in enumerate(parts):
                out.append({"w": p, "start": round(w["start"] + k * span, 3),
                            "end": round(w["start"] + (k + 1) * span, 3)})
    return out

def dur(path):
    r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                        "-of","default=noprint_wrappers=1:nokey=1", path],
                       capture_output=True, text=True)
    return float(r.stdout.strip())

def transcribe_words(clip_path, outdir):
    wav = os.path.join(outdir, "a.wav")
    subprocess.run(["ffmpeg","-hide_banner","-loglevel","error","-y","-i",clip_path,
                    "-vn","-ar","16000","-ac","1",wav], check=True)
    subprocess.run([WHISPER, wav, "--model","small","--language","en",
                    "--output_format","json","--word_timestamps","True",
                    "--output_dir",outdir,"--fp16","False"],
                   capture_output=True, text=True)
    j = json.load(open(os.path.join(outdir,"a.json"), encoding="utf-8"))
    words = []
    for seg in j["segments"]:
        for w in seg.get("words", []):
            tok = w["word"].strip()
            if tok:
                words.append({"w": tok, "start": w["start"], "end": w["end"]})
    return words

def main():
    import tempfile
    os.makedirs(os.path.dirname(CAP_JSON), exist_ok=True)
    base = HOOK_OFFSET
    all_words = []
    for clip in CLIPS:
        path = os.path.join(HERE, "clips", clip + ".mp4")
        d = dur(path)
        with tempfile.TemporaryDirectory() as td:
            ws = transcribe_words(path, td)
        for w in ws:
            all_words.append({"w": w["w"], "start": round(w["start"]+base, 3),
                              "end": round(w["end"]+base, 3)})
        print(f"  {clip:12s} {d:6.2f}s  +{len(ws)} words  (base now {base:.2f})", file=sys.stderr)
        base += d

    groups = []
    cur = []
    def flush():
        if cur:
            groups.append({
                "text": " ".join(x["w"] for x in cur).upper(),
                "start": cur[0]["start"], "end": cur[-1]["end"],
                "words": [{"w": x["w"].upper(), "start": x["start"], "end": x["end"]} for x in cur],
            })
    for w in all_words:
        if cur and (len(cur) >= MAX_WORDS or (w["end"] - cur[0]["start"]) > MAX_GROUP_SECS):
            flush(); cur = []
        cur.append(w)
        if re.search(r"[.!?]$", w["w"]):
            flush(); cur = []
    flush()

    for g in groups:
        g["text"] = re.sub(r"[.,!?]", "", g["text"])
        for w in g["words"]:
            w["w"] = re.sub(r"[.,!?]", "", w["w"])

    for g in groups:
        g["words"] = apply_subs(g["words"])
        g["text"] = " ".join(w["w"] for w in g["words"])

    json.dump(groups, open(CAP_JSON,"w",encoding="utf-8"), indent=2, ensure_ascii=False)

    ts = ("// AUTO-GENERATED by _build_captions_fl07.py - karaoke caption data for the Kaspa Wise Man fl-07 video\n"
          "export type CapWord = { w: string; start: number; end: number };\n"
          "export type CapGroup = { text: string; start: number; end: number; words: CapWord[] };\n"
          "export const CAPTIONS: CapGroup[] = " + json.dumps(groups, ensure_ascii=False) + ";\n")
    open(TS_OUT, "w", encoding="utf-8").write(ts)
    print(f"\nwrote {len(groups)} groups -> {CAP_JSON}\n   and -> {TS_OUT}", file=sys.stderr)

if __name__ == "__main__":
    main()
