// Builds render-assets/ with normalized names AND emits zebecCovers.ts (names guaranteed consistent).
const fs = require('fs'); const path = require('path');
const ROOT = __dirname;
const plan = JSON.parse(fs.readFileSync(path.join(ROOT, 'COVER-PLAN.json'), 'utf8'));
const A = (p) => path.join(ROOT, 'assets', p);
const RA = path.join(ROOT, 'render-assets');
for (const d of ['', 'deck', 'charts', 'receipts', 'vid', 'img']) fs.mkdirSync(path.join(RA, d), { recursive: true });

const ALIAS = { 'R2': 'receipts/R1-R2-R2B_cmc-top.png', 'R2B': 'receipts/R1-R2-R2B_cmc-full.png', 'R1': 'receipts/R1_cmc-unlocks.png' };
function refFor(b){const w=b.what||'';
  if(b.cover_type==='receipt'||b.cover_type==='real-chart'){const m=w.match(/^(R\d+[A-Z]?)/);return m?m[1]:null;}
  if(b.cover_type==='envato-video'){const m=w.match(/^(E\d+)/);return m?m[1]:null;}
  if(b.cover_type==='chatgpt-image'){const m=w.match(/^(CG\d+)/);return m?m[1]:null;}
  if(b.cover_type==='animated-chart'){const m=w.match(/^([a-z-]+)/);return m?m[1].replace(/-$/,''):null;}
  const m=w.match(/^([a-z0-9-]+)/);return m?m[1]:null;}
function srcFor(b,ref){
  if(ref==='R8B') return 'containers/sam-vs-simon.png';           // factual fallback container
  if(ALIAS[ref]) return ALIAS[ref];
  if(b.cover_type==='receipt'||b.cover_type==='real-chart'){const d=A('receipts');const h=fs.readdirSync(d).find(f=>f.startsWith(ref+'_')||f.startsWith(ref+'-'));return h?'receipts/'+h:null;}
  if(b.cover_type==='envato-video'){const d=A('video');const h=fs.readdirSync(d).find(f=>f.startsWith(ref+'_')&&f.endsWith('.cap.mp4'));return h?'video/'+h:null;}
  if(b.cover_type==='chatgpt-image'){const d=A('images');const h=fs.readdirSync(d).find(f=>f.startsWith(ref+'_'));return h?'images/'+h:null;}
  if(b.cover_type==='animated-chart'){if(fs.existsSync(A('animated-charts/'+ref+'.png')))return 'animated-charts/'+ref+'.png';return null;}
  if(fs.existsSync(A('containers/'+ref+'.png')))return 'containers/'+ref+'.png';
  if(fs.existsSync(A('animated-charts/'+ref+'.png')))return 'animated-charts/'+ref+'.png';return null;}

const covers = []; let n=0;
for (const b of plan.cover_beats) {
  const ref = refFor(b); const src = srcFor(b, ref); if(!src){console.log('!! no src',b.chapter,b.tIn,ref);continue;}
  let kind, dir, name, ext=path.extname(src);
  if (b.cover_type==='envato-video'){kind='vid';dir='vid';name=ref;}
  else if (b.cover_type==='chatgpt-image'){kind='still';dir='img';name=ref;}
  else if (b.cover_type==='receipt'||b.cover_type==='real-chart'){
    if(ref==='R8B'){kind='deck';dir='deck';name='sam-vs-simon';} else {kind='receipt';dir='receipts';name=ref;}}
  else if (src.includes('animated-charts/')){kind='chart';dir='charts';name=path.basename(src,'.png');}
  else {kind='deck';dir='deck';name=path.basename(src,'.png');}
  const dest = path.join(RA, dir, name+ext);
  fs.copyFileSync(A(src.replace(/^[^/]+\//,m=>m)), path.join(ROOT,'assets',src)); // noop guard
  fs.copyFileSync(path.join(ROOT,'assets',src), dest);
  covers.push({tIn:+b.tIn.toFixed(2), tOut:+b.tOut.toFixed(2), kind, ref:name});
  n++;
}
// copy spine
fs.copyFileSync(path.join(ROOT,'spine','ALL.c.desilenced.mp4'), path.join(RA,'spine.mp4'));

const ts = `// AUTO-GENERATED by _build_renderassets.js - do not hand-edit.\n`+
`export type ZCover = { tIn: number; tOut: number; kind: 'deck'|'chart'|'receipt'|'vid'|'still'; ref: string };\n`+
`export const ZCOVERS: ZCover[] = [\n`+
covers.map(c=>`  { tIn: ${c.tIn}, tOut: ${c.tOut}, kind: '${c.kind}', ref: '${c.ref}' },`).join('\n')+
`\n];\n`;
fs.writeFileSync(path.join(ROOT,'..','..','..','remotion','src','zebecCovers.ts'), ts);
console.log('render-assets built:', n, 'covers; spine copied; zebecCovers.ts written');
// sanity: list render-assets counts
for(const d of ['deck','charts','receipts','vid','img']) console.log(' ',d, fs.readdirSync(path.join(RA,d)).length);
