// captionsTutEuphImpact.ts - batch tutorial / clip #6 `tut-94x-euphoria-impact` (variant: impact).
// Title: "Look, Look, Holy Crap: The 94X, Then a 550X One Week Later"
//
// GENERATED by the canonical caption skill (video-creation/skills/captions/captions.md, montserrat
// preset). NEVER hand-edited below this header; regenerate byte-identically with:
//   python video-creation/skills/captions/build_captions.py \
//     --words video-creation/shorts/tutorial/tut-94x-euphoria-impact/whisper-words-verified.json \
//     --style montserrat --var CAPTIONS_TUT_EUPHORIA_IMPACT \
//     --colorize "y=94x,550x gr=insane,crap" --max-secs 2.8 \
//     --out video-creation/remotion/src/captionsTutEuphImpact.ts
//
// ⚠ BUILT FROM `whisper-words-verified.json` (clip folder `_patch_words.py`, idempotent + documented),
// NOT the shipped word pass. Three measured patches, no taste calls: the HELD VOWEL (the shipped pass
// shows a 1.80 s hole 5.86->7.66 where an 0.1 s RMS sweep measures unbroken -18 to -19 dBFS - Mike
// sustaining "ohhh" into "man"; the token is re-seated at 5.94 as " Ohhh" so ONE caption stays alive
// across it, which is the tighten plan's binding CAPTION GATE), and "October." + "We're" -> "October"
// + "were" (both a medium.en pass on an isolated 8.6-13.0 s of this clip's own audio and the master's
// large pass at 338.12-343.02 return ONE sentence, "...because that's September and October were
// absolutely insane"). "because that's" is the abandoned connective the tighten plan CONSIDERED and
// deliberately kept, so it stays as spoken.
//
// Every STT fix lives in build_captions.py (tutorial 2026-08-09 block), so nothing here is
// hand-authored. Caption gates from tighten-plan.json, each verified against this clip's OWN pass:
//   * "on my X on BNB" -> "on NYX on BNB"  -> PHRASE ("memoy","x") -> ["nyx"]. Ear-verified four ways
//     on this clip's own spine (small "Memoy X", medium.en "MemYX", large-v3 "Memoy X", 0.5x "MemYX");
//     the master's own later utterance of the same call reads "a 550X on an NYX, man" (4205.92).
//   * "Code Monkey Mike" -> "CodeMonkey Mike"  -> PHRASE ("code","monkey") -> ["codemonkey"]. The
//     montserrat preset renders all-lowercase via CSS, so only the TOKEN MERGE is visible on screen.
//   * "94 X" -> "94X" and "550 X" -> "550X"  -> already single tokens in the word pass; cleanup()'s
//     number+x merge covers the split form. Both carry the <y> accent.
//   * "September and October" -> ear-verified (see above).
//   * DO NOT DEDUPE the cold open. cleanup() would have collapsed the adjacent "Look, look." pair, so
//     the run is keyed in PROTECTED_DOUBLES as ("this","look","look","holy"). "look at, look at this"
//     alternates with "at" and never needed protection. Confirmed on the built array below.
//   * No token is named in this clip, so no $TUT styling appears in it.
//
// --max-secs 2.8: this clip STRETCHES words ("550x" alone runs 1.98 s), so the 3/5 word caps and the
// 0.45 s gap break bound nothing - the default build put "550x on nyx on bnb" on screen for 4.86 s of
// continuous speech. 2.80 is the smallest cap that still keeps the protected 2.74 s "ohhh man" as ONE
// caption. Longest group after it = 2.86 s (the held vowel itself), in line with shipped shorts.
export const CAPTIONS_TUT_EUPHORIA_IMPACT: { t: number; h: string }[] = [
  { t:   0.00, h: 'now look at this man.' },
  { t:   2.44, h: 'look at look at this.' },
  { t:   4.00, h: 'look look.' },
  { t:   4.72, h: 'holy <gr>crap.</gr>' },
  { t:   5.94, h: 'ohhh man.' },
  { t:   8.80, h: 'i hope these' },
  { t:   9.18, h: 'days come back' },
  { t:   9.94, h: 'because that\'s september' },
  { t:  11.06, h: 'and october were' },
  { t:  11.96, h: 'absolutely <gr>insane.</gr>' },
  { t:  12.76, h: 'and then one week' },
  { t:  13.74, h: 'after we did' },
  { t:  14.56, h: 'this <y>94x</y> we did' },
  { t:  17.02, h: 'the <y>550x</y>' },
  { t:  19.52, h: 'on nyx on' },
  { t:  22.04, h: 'bnb again.' },
  { t:  23.34, h: 'and that\'s why' },
  { t:  24.06, h: 'codemonkey mike has' },
  { t:  25.36, h: 'the greatest crypto' },
  { t:  26.56, h: 'community on the' },
  { t:  27.42, h: 'planet.' },
];
