export const CAPTIONS_TUT_FED: { t: number; h: string }[] = [
  { t:   0.00, h: 'i\'m not looking' },
  { t:   0.72, h: 'at the short' },
  { t:   1.44, h: 'term what\'s going' },
  { t:   2.32, h: 'to pump in the next' },
  { t:   3.00, h: 'two weeks, you' },
  { t:   3.58, h: 'know, what\'s going' },
  { t:   3.88, h: 'to pump and then <r>die</r>' },
  { t:   4.90, h: 'and i\'m going' },
  { t:   5.32, h: 'to get out' },
  { t:   5.68, h: 'before it <r>dies,</r>' },
  { t:   6.38, h: 'you know, that\'s' },
  { t:   6.92, h: 'that\'s the <r>degen</r>' },
  { t:   7.64, h: 'mindset.' },
  { t:   8.02, h: 'i don\'t really' },
  { t:   9.44, h: 'i don\'t really' },
  { t:  10.00, h: 'trade like that.' },
  { t:  11.05, h: 'listed on all' },
  { t:  11.94, h: 'these centralized exchanges' },
  { t:  12.86, h: 'become mainstream when' },
  { t:  14.06, h: 'retail starts coming' },
  { t:  14.86, h: 'back in when the bull' },
  { t:  16.02, h: 'when the bull run' },
  { t:  16.80, h: 'starts up again' },
  { t:  17.88, h: 'and everybody\'s coming' },
  { t:  18.80, h: 'back in' },
  { t:  20.29, h: 'i want to get into' },
  { t:  21.18, h: 'all these tokens' },
  { t:  22.06, h: 'that' },
  { t:  23.05, h: 'you know retail' },
  { t:  24.10, h: 'is going to' },
  { t:  24.44, h: 'be looking at' },
  { t:  25.14, h: 'all these tokens' },
  { t:  25.86, h: 'that i\'ve just' },
  { t:  26.44, h: 'listed' },
  { t:  27.23, h: 'and they\'re going' },
  { t:  27.60, h: 'to be buying' },
  { t:  28.04, h: 'in i\'m going' },
  { t:  28.56, h: 'to be like holy crap' },
  { t:  30.23, h: 'i was so' },
  { t:  31.16, h: 'freaking <gr>early</gr> like' },
  { t:  32.08, h: 'this particular token' },
  { t:  34.77, h: 'is like 700 million' },
  { t:  36.28, h: 'and i got in at' },
  { t:  37.32, h: 'like 1.8 million.' },
  { t:  38.58, h: 'that that\'s what' },
  { t:  39.44, h: 'i\'m looking for' },
  { t:  40.14, h: 'i\'m not looking' },
  { t:  40.64, h: 'for the ones that are' },
  { t:  41.42, h: 'going to pump' },
  { t:  41.82, h: 'you know in two' },
  { t:  42.32, h: 'weeks and then' },
  { t:  42.90, h: '<r>die</r>' },
];
