export const CAPTIONS_TUT_BKC: { t: number; h: string }[] = [
  { t:   0.00, h: 'when it comes' },
  { t:   0.96, h: 'to the tech, you know' },
  { t:   1.90, h: '<g>kaspa\'s</g> a gem.' },
  { t:   2.84, h: '<g>kaspa\'s</g> the most' },
  { t:   3.74, h: 'beautiful thing ever.' },
  { t:   5.82, h: 'it is absolutely' },
  { t:   6.34, h: 'the most beautiful' },
  { t:   7.06, h: 'thing.' },
  { t:   7.80, h: 'there was a' },
  { t:   8.34, h: 'blog article on' },
  { t:   9.14, h: 'the <y>binance</y> website' },
  { t:  10.00, h: 'talking about how' },
  { t:  10.86, h: 'they\'re looking for' },
  { t:  11.54, h: 'community-driven coins.' },
  { t:  13.08, h: '<y>binance</y> gives the' },
  { t:  14.40, h: 'argument about neiro' },
  { t:  15.56, h: 'it\'s a community-driven' },
  { t:  16.38, h: 'coin, but it\'s a meme' },
  { t:  17.56, h: 'coin.' },
  { t:  18.00, h: 'they don\'t apply' },
  { t:  18.86, h: 'the same logic' },
  { t:  19.68, h: 'to <g>kaspa</g> because' },
  { t:  20.64, h: 'if they did' },
  { t:  22.10, h: '<g>kaspa</g> would be' },
  { t:  22.98, h: 'listed on <y>binance</y>' },
  { t:  23.84, h: 'by now.' },
  { t:  24.42, h: 'so it\'s kind of a' },
  { t:  25.54, h: 'strange <r>catch-22.</r>' },
  { t:  26.48, h: 'so like i said, you' },
  { t:  27.98, h: 'know, when the' },
  { t:  28.40, h: 'bulls start to' },
  { t:  29.02, h: 'run, you know, like i' },
  { t:  29.90, h: 'would expect <g>kaspa</g>' },
  { t:  30.82, h: 'to be <gr>skyrocketing.</gr>' },
];
