export const CAPTIONS_GK2: { t: number; h: string }[] = [
  { t:   0.00, h: 'you know, i\'m even' },
  { t:   0.90, h: 'open to <y>golden</y>' },
  { t:   1.74, h: '<y>kitty</y>' },
  { t:   2.08, h: 'like' },
  { t:   2.82, h: '<r>rugging</r> tomorrow' },
  { t:   3.58, h: 'like if you tell' },
  { t:   4.34, h: 'me why, but' },
  { t:   5.16, h: 'i don\'t think' },
  { t:   5.82, h: 'it\'s going to' },
  { t:   6.30, h: 'happen like' },
  { t:   7.18, h: '<y>golden</y> <y>kitty.</y>' },
  { t:   7.80, h: 'i don\'t, i don\'t' },
  { t:   8.48, h: 'think, i think' },
  { t:   8.90, h: 'it\'s just too' },
  { t:   9.52, h: '<r>dispersed</r> for that' },
  { t:  10.12, h: 'to happen at' },
  { t:  10.72, h: 'this point and' },
  { t:  11.36, h: 'it\'s going to' },
  { t:  11.88, h: '<gr>pump.</gr>' },
  { t:  12.12, h: 'and if we do' },
  { t:  12.74, h: 'get a nice <gr>run</gr>' },
  { t:  13.60, h: 'up and i\'m' },
  { t:  14.46, h: 'sure it\'s going' },
  { t:  15.14, h: 'to <gr>pump,</gr> it\'ll' },
  { t:  15.96, h: '<gr>pump</gr> really hard.' },
  { t:  16.86, h: 'i do' },
  { t:  17.34, h: 'believe' },
  { t:  17.88, h: 'that this' },
  { t:  18.66, h: 'is probably' },
  { t:  19.38, h: 'one of the' },
  { t:  20.16, h: '<gr>best</gr> <gr>plays</gr>' },
  { t:  21.08, h: 'out there' },
  { t:  21.68, h: 'because there\'s' },
  { t:  22.38, h: 'so many' },
  { t:  23.00, h: 'influencers that' },
  { t:  23.80, h: 'are pushing it.' },
  { t:  24.36, h: 'so there\'s a' },
  { t:  25.04, h: 'lot, a' },
  { t:  25.92, h: 'lot, a' },
  { t:  26.62, h: 'lot of' },
  { t:  27.18, h: 'influencers that are' },
  { t:  27.96, h: 'pushing <y>golden</y>' },
  { t:  28.70, h: '<y>kitty</y>' },
  { t:  29.30, h: 'and' },
  { t:  29.76, h: 'it' },
  { t:  30.58, h: 'has like one of' },
  { t:  31.30, h: 'the <gr>best</gr> <gr>charts</gr>' },
  { t:  32.04, h: 'out there because' },
  { t:  32.76, h: 'everything else, man' },
  { t:  33.68, h: 'just looks like' },
  { t:  34.40, h: '<r>crap.</r>' },
  { t:  34.82, h: '"<y>golden</y> <y>kitty</y> going' },
  { t:  35.76, h: 'to <r>dump</r>' },
  { t:  36.28, h: 'hard' },
  { t:  37.20, h: 'bet you."' },
  { t:  37.72, h: 'i mean, it\'s' },
  { t:  38.64, h: 'possible.' },
  { t:  39.30, h: 'i mean, what if' },
  { t:  39.84, h: 'it goes to' },
  { t:  40.42, h: '<y>100m</y> and' },
  { t:  41.20, h: 'then <r>dumps</r> hard?' },
  { t:  41.98, h: 'you know, you' },
  { t:  42.80, h: 'get in now' },
  { t:  43.60, h: 'at <y>four</y> <y>million</y>' },
  { t:  44.50, h: 'and you take' },
  { t:  45.08, h: '<gr>profits</gr> along the' },
  { t:  45.98, h: 'way.' },
  { t:  46.58, h: 'everything is, every' },
  { t:  47.32, h: 'meme is going' },
  { t:  47.90, h: 'to <r>dump</r> hard.' },
  { t:  48.78, h: 'every meme that' },
  { t:  49.30, h: 'we talked about' },
  { t:  49.94, h: 'today eventually is' },
  { t:  50.86, h: 'going to <r>dump</r>' },
  { t:  51.26, h: 'hard.' },
  { t:  51.62, h: 'it\'s just a' },
  { t:  52.04, h: 'matter of when.' },
  { t:  52.80, h: 'but the point' },
  { t:  53.12, h: 'is, you got to' },
  { t:  53.74, h: 'get in, make some' },
  { t:  54.66, h: '<gr>money</gr> and' },
  { t:  55.58, h: 'take some' },
  { t:  56.22, h: '<gr>profits.</gr>' },
  { t:  56.84, h: 'it\'s a <y>four</y>' },
  { t:  57.16, h: '<y>million</y> market' },
  { t:  57.84, h: 'cap right now.' },
  { t:  58.74, h: 'if this is a' },
  { t:  59.36, h: '<y>billion</y> dollar' },
  { t:  60.02, h: 'token, there\'s a' },
  { t:  60.90, h: 'lot of <gr>gains</gr>' },
  { t:  61.62, h: 'that' },
  { t:  62.36, h: 'we can make' },
  { t:  63.14, h: 'over the course' },
  { t:  63.70, h: 'of this <gr>bull</gr> <gr>run.</gr>' },
];
