export const CAPTIONS_GK2: { t: number; h: string }[] = [
  { t:   0.00, h: 'you know, i\'m even' },
  { t:   0.90, h: 'open to <y>golden</y>' },
  { t:   1.74, h: '<y>kitty</y> like <r>rugging</r>' },
  { t:   3.08, h: 'tomorrow, like if' },
  { t:   4.08, h: 'you tell me why' },
  { t:   5.00, h: 'but i don\'t' },
  { t:   5.60, h: 'think it\'s going' },
  { t:   6.12, h: 'to happen like' },
  { t:   7.18, h: '<y>golden</y> <y>kitty.</y>' },
  { t:   7.80, h: 'i don\'t, i don\'t' },
  { t:   8.48, h: 'think, i think' },
  { t:   8.90, h: 'it\'s just too' },
  { t:   9.52, h: '<r>dispersed</r> for that' },
  { t:  10.12, h: 'to happen at' },
  { t:  10.72, h: 'this point and' },
  { t:  11.36, h: 'it\'s going to' },
  { t:  11.88, h: '<gr>pump.</gr>' },
  { t:  12.12, h: 'and if we do' },
  { t:  12.74, h: 'get a nice <gr>run</gr>' },
  { t:  13.60, h: 'up and i\'m sure' },
  { t:  14.80, h: 'it\'s going to' },
  { t:  15.36, h: '<gr>pump,</gr> it\'ll <gr>pump</gr>' },
  { t:  16.20, h: 'really hard.' },
  { t:  16.86, h: 'i do believe' },
  { t:  17.88, h: 'that this is' },
  { t:  19.06, h: 'probably one of' },
  { t:  19.76, h: 'the <gr>best</gr> <gr>plays</gr>' },
  { t:  21.08, h: 'out there because' },
  { t:  22.04, h: 'there\'s so many' },
  { t:  23.00, h: 'influencers that are' },
  { t:  23.96, h: 'pushing it.' },
  { t:  24.36, h: 'so there\'s a' },
  { t:  25.04, h: 'lot, a lot, a' },
  { t:  26.62, h: 'lot of influencers' },
  { t:  27.58, h: 'that are pushing' },
  { t:  28.26, h: '<y>golden</y> <y>kitty</y> and' },
  { t:  29.76, h: 'it has like one' },
  { t:  31.20, h: 'of the <gr>best</gr>' },
  { t:  31.74, h: '<gr>charts</gr> out there' },
  { t:  32.46, h: 'because everything else' },
  { t:  33.46, h: 'man, just looks' },
  { t:  34.10, h: 'like <r>crap.</r>' },
  { t:  34.82, h: '"<y>golden</y> <y>kitty</y> going' },
  { t:  35.76, h: 'to <r>dump</r> hard, bet' },
  { t:  37.32, h: 'you."' },
  { t:  37.72, h: 'i mean, it\'s' },
  { t:  38.64, h: 'possible.' },
  { t:  39.30, h: 'i mean, what if' },
  { t:  39.84, h: 'it goes to <y>100m</y>' },
  { t:  41.00, h: 'and then <r>dumps</r>' },
  { t:  41.70, h: 'hard?' },
  { t:  41.98, h: 'you know, you get' },
  { t:  43.04, h: 'in now at <y>four</y>' },
  { t:  44.06, h: '<y>million</y> and you' },
  { t:  44.88, h: 'take <gr>profits</gr> along' },
  { t:  45.76, h: 'the way.' },
  { t:  46.58, h: 'everything is, every' },
  { t:  47.32, h: 'meme is going' },
  { t:  47.90, h: 'to <r>dump</r> hard.' },
  { t:  48.78, h: 'every meme that' },
  { t:  49.30, h: 'we talked about' },
  { t:  49.94, h: 'today eventually is' },
  { t:  50.86, h: 'going to <r>dump</r>' },
  { t:  51.26, h: 'hard.' },
  { t:  51.62, h: 'it\'s just a' },
  { t:  52.04, h: 'matter of when.' },
  { t:  52.80, h: 'but the point' },
  { t:  53.12, h: 'is, you got to' },
  { t:  53.74, h: 'get in, make some' },
  { t:  54.66, h: '<gr>money</gr> and take' },
  { t:  56.04, h: 'some <gr>profits.</gr>' },
  { t:  56.84, h: 'it\'s a <y>four</y>' },
  { t:  57.16, h: '<y>million</y> market cap' },
  { t:  58.12, h: 'right now.' },
  { t:  58.74, h: 'if this is a' },
  { t:  59.36, h: '<y>billion</y> dollar token' },
  { t:  60.68, h: 'there\'s a lot' },
  { t:  61.02, h: 'of <gr>gains</gr> that' },
  { t:  62.36, h: 'we can make over' },
  { t:  63.34, h: 'the course of' },
  { t:  63.88, h: 'this <gr>bull</gr> <gr>run.</gr>' },
];
