// captionsEcMoon.ts - batch early-crash / clip #3 `way-off-moon-calls` (variant: full).
// Title (Mike's exact 4b wording, do NOT "fix" the $IF spelling): "What $IF to a 10 billion market cap"
//
// GENERATED by the canonical caption skill (video-creation/skills/captions/captions.md, montserrat
// preset). NEVER hand-edited below this header; regenerate byte-identically with:
//   python video-creation/skills/captions/build_captions.py //     --words video-creation/shorts/early-crash/way-off-moon-calls/whisper-words.json //     --style montserrat --var CAPTIONS_EC_MOON //     --colorize "gr=$lab,350x,58x y=20x,30x,off g=velvet r=scared" //     --out video-creation/remotion/src/captionsEcMoon.ts
//
// Every STT fix lives in build_captions.py PHRASE_CORRECTIONS (early-crash block), so nothing here is
// hand-authored. Caption gates from tighten-plan.json, each VERIFIED against THIS clip's OWN
// whisper-words.json plus isolated re-transcribes of its own final spine:
//   * 'lab token' -> '$lab token' (3x: 7.16 / 12.78 / 16.62). Lowercased by the preset's CSS, so the
//     cashtag is the ONLY thing that separates the token from the English word "lab". House spelling
//     in the queued copy about this same moment is "$LAB" + bare "Velvet" (x-tweets.json), so velvet
//     stays bare and is colour-tagged only.
//   * 'on a lab token' (16.92) -> gate guessed "on THE lab token": REJECTED. Three 1x passes (shipped
//     word pass, large-v3 whole-clip, medium.en on an isolated 16.2-18.0 s) all return "on a lab
//     token". The two earlier occurrences really are "on the lab token" and are untouched.
//   * 'velvet' (27.12) confirmed by large-v3 whole-clip + the shipped pass: "the 58x on the velvet
//     token." Bare "velvet", teal.
//   * 'do the 58x' (29.34) -> "i did a 58x": large-v3 whole-clip AND medium.en on an isolated
//     28.3-31.0 s both return "like a 30x. I did a 58x"; the shipped pass's "a new to" contains a
//     ZERO-duration hallucinated token. Audio was never altered.
//   * the garbled 'we bought that end up at the bottom' (7.98) is captioned FROM AUDIO: the 0.20 s
//     mumble between "that" and "at" merges into "that" (no invented words) -> "we bought that at
//     the bottom in december."
//   * 'moon boyish' -> 'moon-boyish' (20.62), house spelling.
//   * SIGNATURE DOUBLING "i put a 20x price prediction on the $lab token" renders TWICE by design
//     (4.86-7.16 and 10.86-12.78). Verified present twice in the built array; cleanup()'s stutter
//     collapse only eats ADJACENT repeats, so no PROTECTED_DOUBLES entry is needed.
//   * Spoken multiples stay exactly as spoken: 20x / 350x / 58x / 30x.
//   * NO em dashes anywhere (checked mechanically before render).
export const CAPTIONS_EC_MOON: { t: number; h: string }[] = [
  { t:   0.00, h: 'if i give' },
  { t:   0.54, h: 'these high price' },
  { t:   1.64, h: 'predictions and it' },
  { t:   2.76, h: 'might sound like' },
  { t:   3.30, h: 'unrealistic, but i\'m' },
  { t:   4.28, h: 'telling you, man' },
  { t:   4.86, h: 'i put a <y>20x</y>' },
  { t:   6.20, h: 'price prediction on' },
  { t:   7.16, h: 'the <gr>$lab</gr> token.' },
  { t:   7.98, h: 'we bought that' },
  { t:   8.96, h: 'at the bottom' },
  { t:   9.70, h: 'in december.' },
  { t:  10.86, h: 'i put a <y>20x</y>' },
  { t:  11.80, h: 'price prediction on' },
  { t:  12.78, h: 'the <gr>$lab</gr> token' },
  { t:  13.46, h: 'and we did a <gr>350x</gr>' },
  { t:  16.62, h: 'on a <gr>$lab</gr>' },
  { t:  17.16, h: 'token and just' },
  { t:  18.00, h: 'a couple of' },
  { t:  18.38, h: 'months back.' },
  { t:  18.80, h: 'so i guess' },
  { t:  19.28, h: 'sometimes i get' },
  { t:  19.86, h: '<r>scared</r> to give' },
  { t:  20.62, h: 'these like moon-boyish' },
  { t:  21.74, h: 'price predictions.' },
  { t:  22.42, h: 'and i realized' },
  { t:  23.14, h: 'it was like, holy crap' },
  { t:  24.10, h: 'man, i was way <y>off.</y>' },
  { t:  25.86, h: 'the <gr>58x</gr> on the' },
  { t:  27.12, h: '<g>velvet</g> token.' },
  { t:  27.86, h: 'i think i' },
  { t:  28.22, h: 'gave it like a <y>30x.</y>' },
  { t:  29.34, h: 'i did a <gr>58x</gr> and' },
  { t:  30.56, h: 'i still think' },
  { t:  31.06, h: 'it has room to grow' },
  { t:  31.90, h: 'again.' },
];
