#!/usr/bin/env python3
# _gen_editplan.py — regenerate EDIT-PLAN.md (time-ordered event log) from the built comp + spine transcript.
# Per-project convenience script (edit-plan-and-cue-sheet.md §1). Re-run after every comp edit.
#   python _gen_editplan.py
import re, json, os
ROOT = r"C:\Users\mnede\Documents\Claude\social-media\video-creation"
COMP = os.path.join(ROOT, "remotion", "src", "KaspaFounderGenius.tsx")
# transcript: whisper word/segment json of the SOURCE spine (kaspa-genius.f.final.mp4)
TRANS = r"C:\Users\mnede\AppData\Local\Temp\claude\C--Users-mnede-Documents-Claude-social-media\9fc43f70-2e96-4c78-a413-78c63b2366ce\scratchpad\ffinal_full.json"
OUT = os.path.join(os.path.dirname(__file__), "EDIT-PLAN.md")

src = open(COMP, encoding="utf-8").read()
ins = [(float(a), float(d)) for a, d in re.findall(r'at:\s*([\d.]+)\s*,\s*dur:\s*([\d.]+)', re.search(r'INSERTS\s*=\s*\[(.*?)\];', src, re.S).group(1))]
def sh(t): return t + sum(d for a, d in ins if a <= t)
def before(t): return t + sum(d for a, d in ins if a < t)
def fmt(t):
    m = int(t // 60); return f"{m}:{t-m*60:04.1f}"
def clean(s): return s.encode('ascii', 'replace').decode()

DIAG = {'s3', 's5', 's6'}
ev = []  # (time, text)

# SAY lines
if os.path.exists(TRANS):
    for seg in json.load(open(TRANS))['segments']:
        ev.append((sh(float(seg['start'])), f'SAY:  "{clean(seg["text"].strip())}"'))

# COVERS -> layer events
blk = re.search(r'COVERS[^=]*=\s*\[(.*?)\];', src, re.S).group(1)
for m in re.finditer(r"\{\s*tIn:\s*([\d.]+)\s*,\s*tOut:\s*([\d.]+)\s*,\s*kind:\s*'([^']+)'(?:\s*,\s*ref:\s*'([^']+)')?[^}]*\}([^\n]*)", blk):
    tIn, tOut, kind, ref, cm = m.groups(); tIn, tOut = float(tIn), float(tOut); ref = ref or ''
    cm = clean(re.sub(r'^[^/]*//\s*', '', cm).strip())[:62]
    dur = sh(tOut) - sh(tIn)
    if kind in ('deck',):
        lab = 'DIAGRAM' if ref in DIAG else 'CONTAINER'
    elif kind == 'chart': lab = 'CHART'
    elif kind == 'split': lab = 'CONTAINER'; ref = 'C-SPLIT'
    elif kind == 'receipt': lab = 'RECEIPT'
    elif kind in ('vid', 'vidglitch'): lab = 'VIDEO'
    elif kind in ('photo', 'still', 'stillglitch'): lab = 'IMAGE'
    elif kind == 'overlay': lab = 'CTA'
    else: lab = kind.upper()
    ev.append((sh(tIn), f'[{lab}] {ref} ({dur:.1f}s) — {cm}'))

# FACE cut-in glitches
for t in re.findall(r'FACE_CUTS\s*=\s*\[([^\]]+)\]', src)[0].split(','):
    t = float(t)
    if t > 0: ev.append((sh(t), '[TRANSITION] face cut in — blocks-max glitch'))

# cube cards + bed changes
beds = ['Revenant', 'Press Play', 'I Will Deliver']
for i, (t, title) in enumerate(re.findall(r"t:\s*([\d.]+),\s*title:\s*'([^']+)'", re.search(r'CARDS\s*=\s*\[(.*?)\];', src, re.S).group(1))):
    tc = before(float(t))
    ev.append((tc, f'[TRANSITION] cube card "{clean(title).replace(chr(92)+"n", " ")}"  ·  [MUSIC] bed → {beds[i+1]}  ·  [IMPACT] card hit'))

# captions
for a, b in re.findall(r'\[\s*([\d.]+)\s*,\s*([\d.]+)\s*\]', re.search(r'CAPTION_SRC[^=]*=\s*\[(.*?)\]\s*;', src, re.S).group(1)):
    ev.append((sh(float(a)), f'[CAPTION] ON → {fmt(sh(float(b)))} (montserrat 1-2 word)'))

# R-TALK inserts
for a, d in [(a, d) for a, d in ins if d > 5]:
    ev.append((before(a), f'[RECEIPT] ⏸ R-TALK clip ({d:.0f}s full-screen) — [MUSIC] bed CUT to 0 · speech +17dB · [CTA] lower-third credit'))
ev.append((0.0, '[MUSIC] bed → Revenant  ·  [CAPTION] captions ON (FACE beats only, not the plug)'))
ev.append((sh(382.7), '[CTA] MID plug — CryptoRich CTA (>50% covered by CR screenshots, subscribe overlay @7:00); NO captions'))

ev.sort(key=lambda x: x[0])
with open(OUT, 'w', encoding='utf-8') as f:
    f.write("# Kaspa Founder: Genius or Over-Rated? — EDIT-PLAN  (time-ordered event log)\n\n")
    f.write("> GENERATED by `_gen_editplan.py` from the built comp `remotion/src/KaspaFounderGenius.tsx` + the spine\n")
    f.write("> transcript. FINAL-render timecodes (~10:11). Re-run after every comp edit. Layer-grouped view: `CUE-SHEET.md`.\n")
    f.write("> Zero-orphan check: every VIDEO/IMAGE/CONTAINER/RECEIPT asset in `render-assets/` appears below PLACED.\n\n")
    f.write("```\n")
    for t, txt in ev:
        f.write(f"{fmt(t):>7}  {txt}\n")
    f.write("```\n")
print(f"wrote {OUT}  ({len(ev)} events)")
