export const CAPTIONS_TUT_FEI: { t: number; h: string }[] = [
  { t:   0.00, h: 'you know retail' },
  { t:   1.18, h: 'is gonna be' },
  { t:   1.70, h: 'looking at all' },
  { t:   2.44, h: 'these tokens that' },
  { t:   3.12, h: 'i\'ve just listed' },
  { t:   4.29, h: 'and they\'re gonna' },
  { t:   4.70, h: 'be buying in' },
  { t:   5.36, h: 'i\'m gonna be' },
  { t:   5.80, h: 'like "holy crap.' },
  { t:   7.30, h: '"i was so' },
  { t:   8.22, h: 'freaking <gr>early</gr> like' },
  { t:   9.16, h: 'this particular token' },
  { t:  11.84, h: '"is like 700 million' },
  { t:  13.34, h: 'and i got in at' },
  { t:  14.44, h: 'like 1.8 million."' },
  { t:  15.64, h: 'that\'s what i\'m' },
  { t:  16.50, h: 'looking for i\'m' },
  { t:  17.12, h: 'not looking for' },
  { t:  17.66, h: 'the ones that are' },
  { t:  18.26, h: 'gonna pump you' },
  { t:  18.78, h: 'know in two' },
  { t:  19.12, h: 'weeks and then' },
  { t:  19.70, h: '<r>die</r>' },
];
